### PR TITLE
[Azure.Core] Disable TCP_FAST_OPEN to avoid a WinHttp issue

### LINKED ISSUE #4490: WinHTTP memory leak during failed requests
Repro code

```C++
// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

#include <iostream>
#include <stdexcept>

#include <azure/core/http/curl_transport.hpp>
#include <azure/storage/blobs.hpp>

int main()
{
  using namespace Azure::Storage::Blobs;

  std::string connectionStrign
      = "DefaultEndpointsProtocol=https;AccountName=nonexistingaccount;AccountKey="
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==;"
        "EndpointSuffix=core.windows.net";

  BlobClientOptions clientOptions;
  // clientOptions.Transport.Transport = std::make_shared<Azure::Core::Http::CurlTransport>();
  auto containerClient = Azure::Storage::Blobs::BlobContainerClient::CreateFromConnectionString(
      connectionStrign, "containername", clientOptions);

  while (true)
  {
    try
    {
      containerClient.CreateIfNotExists();
    }
    catch (std::exception& e)
    {
      std::cout << e.what() << std::endl;
    }
  }

  return 0;
}
```

### PR DESCRIPTION
**Pull request by RickWinter**
Fixes #4490 - There is an issue with TCP_FAST_OPEN when the address is invalid or not found.

### CODE REVIEW

File: sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp [hunk 1]
```diff
@@ -705,7 +705,7 @@ Azure::Core::_internal::UniqueHandle<HINTERNET> WinHttpTransport::CreateSessionH
 // set successfully, we shouldn't fail the request and continue as if the options don't exist.
 // Therefore, we just ignore the error and move on.
 #ifdef WINHTTP_OPTION_TCP_FAST_OPEN
-  BOOL tcp_fast_open = TRUE;
+  BOOL tcp_fast_open = FALSE;
```
Comment (LarryOsterman) [inline sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp:708]: I would add a comment explaining why the comment says that it's enabling the fast open option but the code says it's disabling the fast open option.

Alternatively, you could change the #ifdef at line 707 to:

```cpp
#if defined(WINHTTP_OPTION_TCP_FAST_OPEN) && FALSE
```

which completely removes the code.

Without a comment, someone is going to come along next year and send an email to the C++ SDK team asking "Does anyone know why this code claims to enable fast open but it doesn't actually do that?" :)

**Review by LarryOsterman — APPROVED** [review]

File: sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp (hunk 1 above)
Comment (RickWinter) [reply sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp:708]: Excellent point.  I'll make that change as I figure we will have this code in here for some time will we wait on the fix.

**Comment by ahsonkhan** [comment]
Fixes https://github.com/Azure/azure-sdk-for-cpp/issues/4490

**Review by antkmsft — APPROVED** [review]

File: sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp [hunk 2]
```diff
@@ -554,10 +554,10 @@ namespace Azure { namespace Core { namespace Http { namespace _detail {
...
    * Special consideration for the WINHTTP_CALLBACK_STATUS_SENDING_REQUEST - this callback is
-   * called during the TLS connection - if a TLS root certificate is configured, we verify that the
-   * certificate chain sent from the server contains the certificate the HTTP client was configured
-   * with. If it is, we accept the connection, if it is not, we abort the connection, closing the
-   * incoming request handle.
+   * called during the TLS connection - if a TLS root certificate is configured, we verify that
+   * the certificate chain sent from the server contains the certificate the HTTP client was
+   * configured with. If it is, we accept the connection, if it is not, we abort the connection,
+   * closing the incoming request handle.
    */
```
Comment (ahsonkhan) [inline sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp:561]: What's causing these comment/line break changes? They are unrelated, correct?

File: sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp [hunk 3]
```diff
@@ -700,11 +700,15 @@ Azure::Core::_internal::UniqueHandle<HINTERNET> WinHttpTransport::CreateSessionH
...
-// Therefore, we just ignore the error and move on.
-#ifdef WINHTTP_OPTION_TCP_FAST_OPEN
+  // These options are only available starting from Windows 10 Version 2004, starting 06/09/2020.
+  // These are primarily round trip time (RTT) performance optimizations, and hence if they don't
+  // get set successfully, we shouldn't fail the request and continue as if the options don't exist.
+  // Therefore, we just ignore the error and move on.
+
+  // TCP_FAST_OPEN has a bug when the DNS resolution fails which can result
+  // in a leak.  Until that issue is fixed we've disable this option.
+
```
Comment (ahsonkhan) [inline sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp:710]: 👍

**Review by ahsonkhan — APPROVED** [review]

File: sdk/core/azure-core/CHANGELOG.md [hunk 4]
```diff
@@ -14,6 +14,7 @@
 
 - [[#4213]](https://github.com/Azure/azure-sdk-for-cpp/issues/4213) Fixed a bug where `Host` request header is not set for non-default port (80, 443).
 - [[#4443]](https://github.com/Azure/azure-sdk-for-cpp/issues/4443) Fixed potentially high CPU usage on Windows.
+- [[#4490]](https://github.com/Azure/azure-sdk-for-cpp/issues/4490) Fixed WinHTTP memory leak during failed requests.
```
Comment (antkmsft) [inline sdk/core/azure-core/CHANGELOG.md:17]: I am surprised you don't have merge conflicts here.
Please update your local sources. The change will go to the entries for the next release (be it `1.8.2`, `1.9.0`, or `1.9.0-beta.2`)

File: sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp (hunk 2 above)
Comment (RickWinter) [reply sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp:561]: I had to run clang-format on the file since I added a comment.  Clang-format did them.  

The change is still more than 1 line b/c I had to add comments.  I'd rather leave these comment fixes as they are correct and are only comments.
