### PR TITLE
Json library update and Xcode15

### LINKED ISSUE #5670: Failure to build with Xcode 15.0.1
Building with Xcode 15.0.1 results in the following errors:

```
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:4668:19: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
    typename std::char_traits<char_type>::int_type get_character()
                  ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:14: note: in instantiation of template class 'Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:8386:41: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
    using char_int_type = typename std::char_traits<char_type>::int_type;
                                        ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9831:33: note: in instantiation of template class 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
    using token_type = typename lexer_t::token_type;
                                ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of template class 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9744:34: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
    char_int_type current = std::char_traits<char_type>::eof();
                                 ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:8391:14: note: in instantiation of default member initializer 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::current' requested here
    explicit lexer(InputAdapterType&& adapter)
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9839:25: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::lexer' requested here
        : callback(cb), m_lexer(std::move(adapter)), allow_exceptions(allow_exceptions_)
                        ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:16000:14: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::parser' requested here
      return ::Azure::Core::Json::_internal::detail::parser<basic_json, InputAdapterType>(
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parser<Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9729:19: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
        case std::char_traits<char_type>::eof():
                  ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:10244:58: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan' requested here
    token_type get_token() { return last_token = m_lexer.scan(); }
                                                         ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9842:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get_token' requested here
      get_token();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:16000:14: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::parser' requested here
      return ::Azure::Core::Json::_internal::detail::parser<basic_json, InputAdapterType>(
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parser<Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9571:50: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
      if (_az_JSON_HEDLEY_LIKELY(current != std::char_traits<char_type>::eof()))
                                                 ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9658:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::unget' requested here
      unget();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9665:46: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::skip_bom' requested here
      if (position.chars_read_total == 0 && !skip_bom())
                                             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:10244:58: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan' requested here
    token_type get_token() { return last_token = m_lexer.scan(); }
                                                         ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9842:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get_token' requested here
      get_token();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:16000:14: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::parser' requested here
      return ::Azure::Core::Json::_internal::detail::parser<basic_json, InputAdapterType>(
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parser<Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9530:50: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
      if (_az_JSON_HEDLEY_LIKELY(current != std::char_traits<char_type>::eof()))
                                                 ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9674:9: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get' requested here
        get();
        ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:10244:58: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan' requested here
    token_type get_token() { return last_token = m_lexer.scan(); }
                                                         ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9842:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get_token' requested here
      get_token();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:16000:14: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::parser' requested here
      return ::Azure::Core::Json::_internal::detail::parser<basic_json, InputAdapterType>(
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parser<Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9532:37: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
        token_string.push_back(std::char_traits<char_type>::to_char_type(current));
                                    ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:4672:28: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
        auto result = std::char_traits<char_type>::to_int_type(*current);
                           ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9527:22: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>::get_character' requested here
        current = ia.get_character();
                     ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9674:9: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get' requested here
        get();
        ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:10244:58: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan' requested here
    token_type get_token() { return last_token = m_lexer.scan(); }
                                                         ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9842:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get_token' requested here
      get_token();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:16000:14: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::parser' requested here
      return ::Azure::Core::Json::_internal::detail::parser<basic_json, InputAdapterType>(
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parser<Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:4678:21: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
        return std::char_traits<char_type>::eof();
                    ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9484:22: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
                std::char_traits<char_type>::to_char_type(get()) != literal_text[i]))
                     ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9696:18: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan_literal' requested here
          return scan_literal(true_literal.data(), true_literal.size(), token_type::literal_true);
                 ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:10244:58: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan' requested here
    token_type get_token() { return last_token = m_lexer.scan(); }
                                                         ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9842:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get_token' requested here
      get_token();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:16000:14: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::parser' requested here
      return ::Azure::Core::Json::_internal::detail::parser<basic_json, InputAdapterType>(
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parser<Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:8535:21: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
          case std::char_traits<char_type>::eof(): {
                    ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9710:18: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan_string' requested here
          return scan_string();
                 ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:10244:58: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan' requested here
    token_type get_token() { return last_token = m_lexer.scan(); }
                                                         ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9842:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get_token' requested here
      get_token();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:16000:14: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::parser' requested here
      return ::Azure::Core::Json::_internal::detail::parser<basic_json, InputAdapterType>(
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parser<Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^
In file included from /Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:8:
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9502:35: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
      token_string.push_back(std::char_traits<char_type>::to_char_type(current));
                                  ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:8524:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::reset' requested here
      reset();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9710:18: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan_string' requested here
          return scan_string();
                 ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:10244:58: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::lexer<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::scan' requested here
    token_type get_token() { return last_token = m_lexer.scan(); }
                                                         ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:9842:7: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::get_token' requested here
      get_token();
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:16000:14: note: in instantiation of member function 'Azure::Core::Json::_internal::detail::parser<Azure::Core::Json::_internal::basic_json<>, Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>::parser' requested here
      return ::Azure::Core::Json::_internal::detail::parser<basic_json, InputAdapterType>(
             ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/inc/azure/core/internal/json/json.hpp:22345:7: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parser<Azure::Core::Json::_internal::detail::iterator_input_adapter<std::__wrap_iter<const unsigned char *>>>' requested here
      parser(detail::input_adapter(std::forward<InputType>(i)), cb, allow_exceptions)
      ^
/Users/runner/work/1/azuresdkforcpp/sdk/core/azure-core/src/exception.cpp:67:61: note: in instantiation of function template specialization 'Azure::Core::Json::_internal::basic_json<>::parse<std::vector<unsigned char> &>' requested here
      auto jsonParser = Azure::Core::Json::_internal::json::parse(bodyBuffer);
                                                            ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__string/char_traits.h:79:8: note: 'char_traits<unsigned char>' has been explicitly marked deprecated here
struct _LIBCPP_DEPRECATED_("char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it.")
       ^
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
                                                    ^

```

### PR DESCRIPTION
**Pull request by gearama**
closes #5670 
Updated json library 
Updated macos tests to ver 14 
Readmes have been touched with add/remove spaces at the end to trigger all Ci pipelines in order to run all tests to verify the json library behaves as expected

Ran all the CI pipelines , since i have to revert the readme files i paste the result here

image

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

File: sdk/eventhubs/azure-messaging-eventhubs/test/perf/inc/azure/messaging/eventhubs/test/eventhubs_batch_perf_test.hpp [hunk 1]
```diff
@@ -183,6 +183,8 @@ namespace Azure { namespace Messaging { namespace EventHubs { namespace PerfTest
 
       auto events = partitionClient.ReceiveEvents(m_batchSize, context);
       total += events.size();
+      std::cout << "[r: " << round << "/" << m_rounds << "p: " << m_partitionId
+                << "] Received: " << total << " messages" << std::endl;
```
Comment (LarryOsterman) [inline sdk/eventhubs/azure-messaging-eventhubs/test/perf/inc/azure/messaging/eventhubs/test/eventhubs_batch_perf_test.hpp:187]: This change confuses me. Did something get merged strangely?

Comment (gearama) [reply sdk/eventhubs/azure-messaging-eventhubs/test/perf/inc/azure/messaging/eventhubs/test/eventhubs_batch_perf_test.hpp:187]: yeah i was getitng an issue with unused variables

Comment (LarryOsterman) [reply sdk/eventhubs/azure-messaging-eventhubs/test/perf/inc/azure/messaging/eventhubs/test/eventhubs_batch_perf_test.hpp:187]: Ok. That seems reasonable.

File: sdk/keyvault/azure-security-keyvault-keys/test/ut/mocked_transport_adapter_test.hpp [hunk 2]
```diff
@@ -90,14 +90,14 @@ namespace Azure { namespace Security { namespace KeyVault { namespace Keys { nam
...
       }
-
-      result = new char[std::string(fakeKey).size() + keyType.size()];
+      size_t bufferSize = std::string(fakeKey).size() + keyType.size();
+      result = new char[bufferSize];
 
 #if defined(_MSC_VER)
 #pragma warning(push)
 #pragma warning(disable : 4996)
 #endif
```
Comment (antkmsft) [inline sdk/keyvault/azure-security-keyvault-keys/test/ut/mocked_transport_adapter_test.hpp:99]: Given that now we use `snprintf()` instead of `sprintf()`, this warning suppression is no longer needed?

Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/test/ut/mocked_transport_adapter_test.hpp]: done

File: sdk/core/azure-core-test/inc/azure/core/test/test_proxy_manager.hpp [hunk 3]
```diff
@@ -56,7 +56,7 @@ namespace Azure { namespace Core { namespace Test {
     // Using a reference because the context lives in the test_base class and we don't want to make
     // a copy.
     Azure::Core::Test::TestContextManager& m_testContext;
-    const std::string m_proxy = "https://localhost:5001";
+    const std::string m_proxy = "http://localhost:5000";
```
[the remark this answers is not in the document]
Comment (gearama) [reply sdk/core/azure-core-test/inc/azure/core/test/test_proxy_manager.hpp:59]: yes , macos latest version test-proxy doesn't work properly with the test proxy https endpoint. since this is internal local call i'm not worried abouyt it

File: eng/pipelines/templates/jobs/ci.tests.yml [hunk 4]
```diff
@@ -184,6 +184,10 @@ jobs:
             ServiceDirectory: ${{ parameters.ServiceDirectory }}
             TestPipeline: ${{ parameters.TestPipeline }}
 
+      - pwsh: |
+          Write-Host "##vso[task.setvariable variable=DOTNET_ROLL_FORWARD]Major"
+        displayName: Set DOTNET_ROLL_FORWARD to Major globally
```
Comment (danieljurek) [inline eng/pipelines/templates/jobs/ci.tests.yml:189]: This should be done with eng/common changes, not globally set here.

Comment (danieljurek) [reply eng/pipelines/templates/jobs/ci.tests.yml:189]: https://github.com/Azure/azure-sdk-tools/pull/8373

**Comment by antkmsft** [comment]
I compared the files locally, and we need to add prefix to all the macros that are getting defined. In the previous version, we prefixed them all with `_az_`, but if we're touching them anyways, let's change that to `_azure_`?

```cpp
#ifndef _azure_JSON_USE_LEGACY_DISCARDED_VALUE_COMPARISON
#define _azure_JSON_USE_LEGACY_DISCARDED_VALUE_COMPARISON 0
#endif
```
etc, etc.

**Comment by antkmsft** [comment]
@gearama, this should do it:
```powershell
(Get-Content sdk/core/azure-core/inc/azure/core/internal/json/json.hpp) `
.Replace('NLOHMANN_JSON_TO', '_azure_NLOHMANN_JSON_TO') `
.Replace('NLOHMANN_JSON_SERIALIZE_ENUM', '_azure_NLOHMANN_JSON_SERIALIZE_ENUM') `
.Replace('NLOHMANN_JSON_PASTE64', '_azure_NLOHMANN_JSON_PASTE64') `
.Replace('NLOHMANN_JSON_PASTE63', '_azure_NLOHMANN_JSON_PASTE63') `
.Replace('NLOHMANN_JSON_PASTE62', '_azure_NLOHMANN_JSON_PASTE62') `
.Replace('NLOHMANN_JSON_PASTE61', '_azure_NLOHMANN_JSON_PASTE61') `
.Replace('NLOHMANN_JSON_PASTE60', '_azure_NLOHMANN_JSON_PASTE60') `
.Replace('NLOHMANN_JSON_PASTE59', '_azure_NLOHMANN_JSON_PASTE59') `
.Replace('NLOHMANN_JSON_PASTE58', '_azure_NLOHMANN_JSON_PASTE58') `
.Replace('NLOHMANN_JSON_PASTE57', '_azure_NLOHMANN_JSON_PASTE57') `
.Replace('NLOHMANN_JSON_PASTE56', '_azure_NLOHMANN_JSON_PASTE56') `
.Replace('NLOHMANN_JSON_PASTE55', '_azure_NLOHMANN_JSON_PASTE55') `
.Replace('NLOHMANN_JSON_PASTE54', '_azure_NLOHMANN_JSON_PASTE54') `
.Replace('NLOHMANN_JSON_PASTE53', '_azure_NLOHMANN_JSON_PASTE53') `
.Replace('NLOHMANN_JSON_PASTE52', '_azure_NLOHMANN_JSON_PASTE52') `
.Replace('NLOHMANN_JSON_PASTE51', '_azure_NLOHMANN_JSON_PASTE51') `
.Replace('NLOHMANN_JSON_PASTE50', '_azure_NLOHMANN_JSON_PASTE50') `
.Replace('NLOHMANN_JSON_PASTE49', '_azure_NLOHMANN_JSON_PASTE49') `
.Replace('NLOHMANN_JSON_PASTE48', '_azure_NLOHMANN_JSON_PASTE48') `
.Replace('NLOHMANN_JSON_PASTE47', '_azure_NLOHMANN_JSON_PASTE47') `
.Replace('NLOHMANN_JSON_PASTE46', '_azure_NLOHMANN_JSON_PASTE46') `
.Replace('NLOHMANN_JSON_PASTE45', '_azure_NLOHMANN_JSON_PASTE45') `
.Replace('NLOHMANN_JSON_PASTE44', '_azure_NLOHMANN_JSON_PASTE44') `
.Replace('NLOHMANN_JSON_PASTE43', '_azure_NLOHMANN_JSON_PASTE43') `
.Replace('NLOHMANN_JSON_PASTE42', '_azure_NLOHMANN_JSON_PASTE42') `
.Replace('NLOHMANN_JSON_PASTE41', '_azure_NLOHMANN_JSON_PASTE41') `
.Replace('NLOHMANN_JSON_PASTE40', '_azure_NLOHMANN_JSON_PASTE40') `
.Replace('NLOHMANN_JSON_PASTE39', '_azure_NLOHMANN_JSON_PASTE39') `
.Replace('NLOHMANN_JSON_PASTE38', '_azure_NLOHMANN_JSON_PASTE38') `
.Replace('NLOHMANN_JSON_PASTE37', '_azure_NLOHMANN_JSON_PASTE37') `
.Replace('NLOHMANN_JSON_PASTE36', '_azure_NLOHMANN_JSON_PASTE36') `
.Replace('NLOHMANN_JSON_PASTE35', '_azure_NLOHMANN_JSON_PASTE35') `
.Replace('NLOHMANN_JSON_PASTE34', '_azure_NLOHMANN_JSON_PASTE34') `
.Replace('NLOHMANN_JSON_PASTE33', '_azure_NLOHMANN_JSON_PASTE33') `
.Replace('NLOHMANN_JSON_PASTE32', '_azure_NLOHMANN_JSON_PASTE32') `
.Replace('NLOHMANN_JSON_PASTE31', '_azure_NLOHMANN_JSON_PASTE31') `
.Replace('NLOHMANN_JSON_PASTE30', '_azure_NLOHMANN_JSON_PASTE30') `
.Replace('NLOHMANN_JSON_PASTE29', '_azure_NLOHMANN_JSON_PASTE29') `
.Replace('NLOHMANN_JSON_PASTE28', '_azure_NLOHMANN_JSON_PASTE28') `
.Replace('NLOHMANN_JSON_PASTE27', '_azure_NLOHMANN_JSON_PASTE27') `
.Replace('NLOHMANN_JSON_PASTE26', '_azure_NLOHMANN_JSON_PASTE26') `
.Replace('NLOHMANN_JSON_PASTE25', '_azure_NLOHMANN_JSON_PASTE25') `
.Replace('NLOHMANN_JSON_PASTE24', '_azure_NLOHMANN_JSON_PASTE24') `
.Replace('NLOHMANN_JSON_PASTE23', '_azure_NLOHMANN_JSON_PASTE23') `
.Replace('NLOHMANN_JSON_PASTE22', '_azure_NLOHMANN_JSON_PASTE22') `
.Replace('NLOHMANN_JSON_PASTE21', '_azure_NLOHMANN_JSON_PASTE21') `
.Replace('NLOHMANN_JSON_PASTE20', '_azure_NLOHMANN_JSON_PASTE20') `
.Replace('NLOHMANN_JSON_PASTE19', '_azure_NLOHMANN_JSON_PASTE19') `
.Replace('NLOHMANN_JSON_PASTE18', '_azure_NLOHMANN_JSON_PASTE18') `
.Replace('NLOHMANN_JSON_PASTE17', '_azure_NLOHMANN_JSON_PASTE17') `
.Replace('NLOHMANN_JSON_PASTE16', '_azure_NLOHMANN_JSON_PASTE16') `
.Replace('NLOHMANN_JSON_PASTE15', '_azure_NLOHMANN_JSON_PASTE15') `
.Replace('NLOHMANN_JSON_PASTE14', '_azure_NLOHMANN_JSON_PASTE14') `
.Replace('NLOHMANN_JSON_PASTE13', '_azure_NLOHMANN_JSON_PASTE13') `
.Replace('NLOHMANN_JSON_PASTE12', '_azure_NLOHMANN_JSON_PASTE12') `
.Replace('NLOHMANN_JSON_PASTE11', '_azure_NLOHMANN_JSON_PASTE11') `
.Replace('NLOHMANN_JSON_PASTE10', '_azure_NLOHMANN_JSON_PASTE10') `
.Replace('NLOHMANN_JSON_PASTE9', '_azure_NLOHMANN_JSON_PASTE9') `
.Replace('NLOHMANN_JSON_PASTE8', '_azure_NLOHMANN_JSON_PASTE8') `
.Replace('NLOHMANN_JSON_PASTE7', '_azure_NLOHMANN_JSON_PASTE7') `
.Replace('NLOHMANN_JSON_PASTE6', '_azure_NLOHMANN_JSON_PASTE6') `
.Replace('NLOHMANN_JSON_PASTE5', '_azure_NLOHMANN_JSON_PASTE5') `
.Replace('NLOHMANN_JSON_PASTE4', '_azure_NLOHMANN_JSON_PASTE4') `
.Replace('NLOHMANN_JSON_PASTE3', '_azure_NLOHMANN_JSON_PASTE3') `
.Replace('NLOHMANN_JSON_PASTE2', '_azure_NLOHMANN_JSON_PASTE2') `
.Replace('NLOHMANN_JSON_PASTE', '_azure_NLOHMANN_JSON_PASTE') `
.Replace('NLOHMANN_JSON_NAMESPACE_NO_VERSION', '_azure_NLOHMANN_JSON_NAMESPACE_NO_VERSION') `
.Replace('NLOHMANN_JSON_GET_MACRO', '_azure_NLOHMANN_JSON_GET_MACRO') `
.Replace('NLOHMANN_JSON_FROM_WITH_DEFAULT', '_azure_NLOHMANN_JSON_FROM_WITH_DEFAULT') `
.Replace('NLOHMANN_JSON_FROM', '_azure_NLOHMANN_JSON_FROM') `
.Replace('NLOHMANN_JSON_EXPAND', '_azure_NLOHMANN_JSON_EXPAND') `
.Replace('NLOHMANN_JSON_ABI_TAG_LEGACY_DISCARDED_VALUE_COMPARISON', '_azure_NLOHMANN_JSON_ABI_TAG_LEGACY_DISCARDED_VALUE_COMPARISON') `
.Replace('NLOHMANN_JSON_ABI_TAG_DIAGNOSTICS', '_azure_NLOHMANN_JSON_ABI_TAG_DIAGNOSTICS') `
.Replace('NLOHMANN_JSON_ABI_TAGS_CONCAT_EX', '_azure_NLOHMANN_JSON_ABI_TAGS_CONCAT_EX') `
.Replace('NLOHMANN_JSON_ABI_TAGS_CONCAT', '_azure_NLOHMANN_JSON_ABI_TAGS_CONCAT') `
.Replace('NLOHMANN_JSON_ABI_TAGS', '_azure_NLOHMANN_JSON_ABI_TAGS') `
.Replace('NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT', '_azure_NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT') `
.Replace('NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_ONLY_SERIALIZE', '_azure_NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_ONLY_SERIALIZE') `
.Replace('NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE', '_azure_NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE') `
.Replace('NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT', '_azure_NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT') `
.Replace('NLOHMANN_DEFINE_TYPE_INTRUSIVE_ONLY_SERIALIZE', '_azure_NLOHMANN_DEFINE_TYPE_INTRUSIVE_ONLY_SERIALIZE') `
.Replace('NLOHMANN_DEFINE_TYPE_INTRUSIVE', '_azure_NLOHMANN_DEFINE_TYPE_INTRUSIVE') `
.Replace('NLOHMANN_CAN_CALL_STD_FUNC_IMPL', '_azure_NLOHMANN_CAN_CALL_STD_FUNC_IMPL') `
.Replace('NLOHMANN_BASIC_JSON_TPL_DECLARATION', '_azure_NLOHMANN_BASIC_JSON_TPL_DECLARATION') `
.Replace('NLOHMANN_BASIC_JSON_TPL', '_azure_NLOHMANN_BASIC_JSON_TPL') `
.Replace('JSON_USE_LEGACY_DISCARDED_VALUE_COMPARISON', '_azure_JSON_USE_LEGACY_DISCARDED_VALUE_COMPARISON') `
.Replace('JSON_USE_IMPLICIT_CONVERSIONS', '_azure_JSON_USE_IMPLICIT_CONVERSIONS') `
.Replace('JSON_USE_GLOBAL_UDLS', '_azure_JSON_USE_GLOBAL_UDLS') `
.Replace('JSON_TRY', '_azure_JSON_TRY') `
.Replace('JSON_THROW', '_azure_JSON_THROW') `
.Replace('JSON_PRIVATE_UNLESS_TESTED', '_azure_JSON_PRIVATE_UNLESS_TESTED') `
.Replace('JSON_NO_UNIQUE_ADDRESS', '_azure_JSON_NO_UNIQUE_ADDRESS') `
.Replace('JSON_INTERNAL_CATCH', '_azure_JSON_INTERNAL_CATCH') `
.Replace('JSON_INLINE_VARIABLE', '_azure_JSON_INLINE_VARIABLE') `
.Replace('JSON_IMPLEMENT_OPERATOR', '_azure_JSON_IMPLEMENT_OPERATOR') `
.Replace('JSON_HEDLEY_WARN_UNUSED_RESULT_MSG', '_azure_JSON_HEDLEY_WARN_UNUSED_RESULT_MSG') `
.Replace('JSON_HEDLEY_WARN_UNUSED_RESULT', '_azure_JSON_HEDLEY_WARN_UNUSED_RESULT') `
.Replace('JSON_HEDLEY_WARNING', '_azure_JSON_HEDLEY_WARNING') `
.Replace('JSON_HEDLEY_VERSION_ENCODE', '_azure_JSON_HEDLEY_VERSION_ENCODE') `
.Replace('JSON_HEDLEY_VERSION_DECODE_REVISION', '_azure_JSON_HEDLEY_VERSION_DECODE_REVISION') `
.Replace('JSON_HEDLEY_VERSION_DECODE_MINOR', '_azure_JSON_HEDLEY_VERSION_DECODE_MINOR') `
.Replace('JSON_HEDLEY_VERSION_DECODE_MAJOR', '_azure_JSON_HEDLEY_VERSION_DECODE_MAJOR') `
.Replace('JSON_HEDLEY_VERSION', '_azure_JSON_HEDLEY_VERSION') `
.Replace('JSON_HEDLEY_UNREACHABLE_RETURN', '_azure_JSON_HEDLEY_UNREACHABLE_RETURN') `
.Replace('JSON_HEDLEY_UNREACHABLE', '_azure_JSON_HEDLEY_UNREACHABLE') `
.Replace('JSON_HEDLEY_UNPREDICTABLE', '_azure_JSON_HEDLEY_UNPREDICTABLE') `
.Replace('JSON_HEDLEY_UNLIKELY', '_azure_JSON_HEDLEY_UNLIKELY') `
.Replace('JSON_HEDLEY_UNAVAILABLE', '_azure_JSON_HEDLEY_UNAVAILABLE') `
.Replace('JSON_HEDLEY_TI_VERSION_CHECK', '_azure_JSON_HEDLEY_TI_VERSION_CHECK') `
.Replace('JSON_HEDLEY_TI_VERSION', '_azure_JSON_HEDLEY_TI_VERSION') `
.Replace('JSON_HEDLEY_TI_CLPRU_VERSION_CHECK', '_azure_JSON_HEDLEY_TI_CLPRU_VERSION_CHECK') `
.Replace('JSON_HEDLEY_TI_CLPRU_VERSION', '_azure_JSON_HEDLEY_TI_CLPRU_VERSION') `
.Replace('JSON_HEDLEY_TI_CL2000_VERSION_CHECK', '_azure_JSON_HEDLEY_TI_CL2000_VERSION_CHECK') `
.Replace('JSON_HEDLEY_TI_CL2000_VERSION', '_azure_JSON_HEDLEY_TI_CL2000_VERSION') `
.Replace('JSON_HEDLEY_TI_CL430_VERSION_CHECK', '_azure_JSON_HEDLEY_TI_CL430_VERSION_CHECK') `
.Replace('JSON_HEDLEY_TI_CL430_VERSION', '_azure_JSON_HEDLEY_TI_CL430_VERSION') `
.Replace('JSON_HEDLEY_TI_CL7X_VERSION_CHECK', '_azure_JSON_HEDLEY_TI_CL7X_VERSION_CHECK') `
.Replace('JSON_HEDLEY_TI_CL7X_VERSION', '_azure_JSON_HEDLEY_TI_CL7X_VERSION') `
.Replace('JSON_HEDLEY_TI_CL6X_VERSION_CHECK', '_azure_JSON_HEDLEY_TI_CL6X_VERSION_CHECK') `
.Replace('JSON_HEDLEY_TI_CL6X_VERSION', '_azure_JSON_HEDLEY_TI_CL6X_VERSION') `
.Replace('JSON_HEDLEY_TI_ARMCL_VERSION_CHECK', '_azure_JSON_HEDLEY_TI_ARMCL_VERSION_CHECK') `
.Replace('JSON_HEDLEY_TI_ARMCL_VERSION', '_azure_JSON_HEDLEY_TI_ARMCL_VERSION') `
.Replace('JSON_HEDLEY_TINYC_VERSION_CHECK', '_azure_JSON_HEDLEY_TINYC_VERSION_CHECK') `
.Replace('JSON_HEDLEY_TINYC_VERSION', '_azure_JSON_HEDLEY_TINYC_VERSION') `
.Replace('JSON_HEDLEY_SUNPRO_VERSION_CHECK', '_azure_JSON_HEDLEY_SUNPRO_VERSION_CHECK') `
.Replace('JSON_HEDLEY_SUNPRO_VERSION', '_azure_JSON_HEDLEY_SUNPRO_VERSION') `
.Replace('JSON_HEDLEY_STRINGIFY_EX', '_azure_JSON_HEDLEY_STRINGIFY_EX') `
.Replace('JSON_HEDLEY_STRINGIFY', '_azure_JSON_HEDLEY_STRINGIFY') `
.Replace('JSON_HEDLEY_STATIC_CAST', '_azure_JSON_HEDLEY_STATIC_CAST') `
.Replace('JSON_HEDLEY_STATIC_ASSERT', '_azure_JSON_HEDLEY_STATIC_ASSERT') `
.Replace('JSON_HEDLEY_SENTINEL', '_azure_JSON_HEDLEY_SENTINEL') `
.Replace('JSON_HEDLEY_RETURNS_NON_NULL', '_azure_JSON_HEDLEY_RETURNS_NON_NULL') `
.Replace('JSON_HEDLEY_RESTRICT', '_azure_JSON_HEDLEY_RESTRICT') `
.Replace('JSON_HEDLEY_REQUIRE_MSG', '_azure_JSON_HEDLEY_REQUIRE_MSG') `
.Replace('JSON_HEDLEY_REQUIRE_CONSTEXPR', '_azure_JSON_HEDLEY_REQUIRE_CONSTEXPR') `
.Replace('JSON_HEDLEY_REQUIRE', '_azure_JSON_HEDLEY_REQUIRE') `
.Replace('JSON_HEDLEY_REINTERPRET_CAST', '_azure_JSON_HEDLEY_REINTERPRET_CAST') `
.Replace('JSON_HEDLEY_PURE', '_azure_JSON_HEDLEY_PURE') `
.Replace('JSON_HEDLEY_PUBLIC', '_azure_JSON_HEDLEY_PUBLIC') `
.Replace('JSON_HEDLEY_PRIVATE', '_azure_JSON_HEDLEY_PRIVATE') `
.Replace('JSON_HEDLEY_PRINTF_FORMAT', '_azure_JSON_HEDLEY_PRINTF_FORMAT') `
.Replace('JSON_HEDLEY_PREDICT_TRUE', '_azure_JSON_HEDLEY_PREDICT_TRUE') `
.Replace('JSON_HEDLEY_PREDICT_FALSE', '_azure_JSON_HEDLEY_PREDICT_FALSE') `
.Replace('JSON_HEDLEY_PREDICT', '_azure_JSON_HEDLEY_PREDICT') `
.Replace('JSON_HEDLEY_PRAGMA', '_azure_JSON_HEDLEY_PRAGMA') `
.Replace('JSON_HEDLEY_PGI_VERSION_CHECK', '_azure_JSON_HEDLEY_PGI_VERSION_CHECK') `
.Replace('JSON_HEDLEY_PGI_VERSION', '_azure_JSON_HEDLEY_PGI_VERSION') `
.Replace('JSON_HEDLEY_PELLES_VERSION_CHECK', '_azure_JSON_HEDLEY_PELLES_VERSION_CHECK') `
.Replace('JSON_HEDLEY_PELLES_VERSION', '_azure_JSON_HEDLEY_PELLES_VERSION') `
.Replace('JSON_HEDLEY_NULL', '_azure_JSON_HEDLEY_NULL') `
.Replace('JSON_HEDLEY_NO_THROW', '_azure_JSON_HEDLEY_NO_THROW') `
.Replace('JSON_HEDLEY_NO_RETURN', '_azure_JSON_HEDLEY_NO_RETURN') `
.Replace('JSON_HEDLEY_NO_ESCAPE', '_azure_JSON_HEDLEY_NO_ESCAPE') `
.Replace('JSON_HEDLEY_NON_NULL', '_azure_JSON_HEDLEY_NON_NULL') `
.Replace('JSON_HEDLEY_NEVER_INLINE', '_azure_JSON_HEDLEY_NEVER_INLINE') `
.Replace('JSON_HEDLEY_MSVC_VERSION_CHECK', '_azure_JSON_HEDLEY_MSVC_VERSION_CHECK') `
.Replace('JSON_HEDLEY_MSVC_VERSION', '_azure_JSON_HEDLEY_MSVC_VERSION') `
.Replace('JSON_HEDLEY_MESSAGE', '_azure_JSON_HEDLEY_MESSAGE') `
.Replace('JSON_HEDLEY_MCST_LCC_VERSION_CHECK', '_azure_JSON_HEDLEY_MCST_LCC_VERSION_CHECK') `
.Replace('JSON_HEDLEY_MCST_LCC_VERSION', '_azure_JSON_HEDLEY_MCST_LCC_VERSION') `
.Replace('JSON_HEDLEY_MALLOC', '_azure_JSON_HEDLEY_MALLOC') `
.Replace('JSON_HEDLEY_LIKELY', '_azure_JSON_HEDLEY_LIKELY') `
.Replace('JSON_HEDLEY_IS_CONSTEXPR_', '_azure_JSON_HEDLEY_IS_CONSTEXPR_') `
.Replace('JSON_HEDLEY_IS_CONSTANT', '_azure_JSON_HEDLEY_IS_CONSTANT') `
.Replace('JSON_HEDLEY_INTEL_VERSION_CHECK', '_azure_JSON_HEDLEY_INTEL_VERSION_CHECK') `
.Replace('JSON_HEDLEY_INTEL_VERSION', '_azure_JSON_HEDLEY_INTEL_VERSION') `
.Replace('JSON_HEDLEY_INTEL_CL_VERSION_CHECK', '_azure_JSON_HEDLEY_INTEL_CL_VERSION_CHECK') `
.Replace('JSON_HEDLEY_INTEL_CL_VERSION', '_azure_JSON_HEDLEY_INTEL_CL_VERSION') `
.Replace('JSON_HEDLEY_INLINE', '_azure_JSON_HEDLEY_INLINE') `
.Replace('JSON_HEDLEY_IMPORT', '_azure_JSON_HEDLEY_IMPORT') `
.Replace('JSON_HEDLEY_IBM_VERSION_CHECK', '_azure_JSON_HEDLEY_IBM_VERSION_CHECK') `
.Replace('JSON_HEDLEY_IBM_VERSION', '_azure_JSON_HEDLEY_IBM_VERSION') `
.Replace('JSON_HEDLEY_IAR_VERSION_CHECK', '_azure_JSON_HEDLEY_IAR_VERSION_CHECK') `
.Replace('JSON_HEDLEY_IAR_VERSION', '_azure_JSON_HEDLEY_IAR_VERSION') `
.Replace('JSON_HEDLEY_HAS_WARNING', '_azure_JSON_HEDLEY_HAS_WARNING') `
.Replace('JSON_HEDLEY_HAS_FEATURE', '_azure_JSON_HEDLEY_HAS_FEATURE') `
.Replace('JSON_HEDLEY_HAS_EXTENSION', '_azure_JSON_HEDLEY_HAS_EXTENSION') `
.Replace('JSON_HEDLEY_HAS_DECLSPEC_ATTRIBUTE', '_azure_JSON_HEDLEY_HAS_DECLSPEC_ATTRIBUTE') `
.Replace('JSON_HEDLEY_HAS_CPP_ATTRIBUTE_NS', '_azure_JSON_HEDLEY_HAS_CPP_ATTRIBUTE_NS') `
.Replace('JSON_HEDLEY_HAS_CPP_ATTRIBUTE', '_azure_JSON_HEDLEY_HAS_CPP_ATTRIBUTE') `
.Replace('JSON_HEDLEY_HAS_BUILTIN', '_azure_JSON_HEDLEY_HAS_BUILTIN') `
.Replace('JSON_HEDLEY_HAS_ATTRIBUTE', '_azure_JSON_HEDLEY_HAS_ATTRIBUTE') `
.Replace('JSON_HEDLEY_GNUC_VERSION_CHECK', '_azure_JSON_HEDLEY_GNUC_VERSION_CHECK') `
.Replace('JSON_HEDLEY_GNUC_VERSION', '_azure_JSON_HEDLEY_GNUC_VERSION') `
.Replace('JSON_HEDLEY_GNUC_HAS_WARNING', '_azure_JSON_HEDLEY_GNUC_HAS_WARNING') `
.Replace('JSON_HEDLEY_GNUC_HAS_FEATURE', '_azure_JSON_HEDLEY_GNUC_HAS_FEATURE') `
.Replace('JSON_HEDLEY_GNUC_HAS_EXTENSION', '_azure_JSON_HEDLEY_GNUC_HAS_EXTENSION') `
.Replace('JSON_HEDLEY_GNUC_HAS_DECLSPEC_ATTRIBUTE', '_azure_JSON_HEDLEY_GNUC_HAS_DECLSPEC_ATTRIBUTE') `
.Replace('JSON_HEDLEY_GNUC_HAS_CPP_ATTRIBUTE', '_azure_JSON_HEDLEY_GNUC_HAS_CPP_ATTRIBUTE') `
.Replace('JSON_HEDLEY_GNUC_HAS_BUILTIN', '_azure_JSON_HEDLEY_GNUC_HAS_BUILTIN') `
.Replace('JSON_HEDLEY_GNUC_HAS_ATTRIBUTE', '_azure_JSON_HEDLEY_GNUC_HAS_ATTRIBUTE') `
.Replace('JSON_HEDLEY_GCC_VERSION_CHECK', '_azure_JSON_HEDLEY_GCC_VERSION_CHECK') `
.Replace('JSON_HEDLEY_GCC_VERSION', '_azure_JSON_HEDLEY_GCC_VERSION') `
.Replace('JSON_HEDLEY_GCC_NOT_CLANG_VERSION_CHECK', '_azure_JSON_HEDLEY_GCC_NOT_CLANG_VERSION_CHECK') `
.Replace('JSON_HEDLEY_GCC_HAS_WARNING', '_azure_JSON_HEDLEY_GCC_HAS_WARNING') `
.Replace('JSON_HEDLEY_GCC_HAS_FEATURE', '_azure_JSON_HEDLEY_GCC_HAS_FEATURE') `
.Replace('JSON_HEDLEY_GCC_HAS_EXTENSION', '_azure_JSON_HEDLEY_GCC_HAS_EXTENSION') `
.Replace('JSON_HEDLEY_GCC_HAS_DECLSPEC_ATTRIBUTE', '_azure_JSON_HEDLEY_GCC_HAS_DECLSPEC_ATTRIBUTE') `
.Replace('JSON_HEDLEY_GCC_HAS_CPP_ATTRIBUTE', '_azure_JSON_HEDLEY_GCC_HAS_CPP_ATTRIBUTE') `
.Replace('JSON_HEDLEY_GCC_HAS_BUILTIN', '_azure_JSON_HEDLEY_GCC_HAS_BUILTIN') `
.Replace('JSON_HEDLEY_GCC_HAS_ATTRIBUTE', '_azure_JSON_HEDLEY_GCC_HAS_ATTRIBUTE') `
.Replace('JSON_HEDLEY_FLAGS_CAST', '_azure_JSON_HEDLEY_FLAGS_CAST') `
.Replace('JSON_HEDLEY_FLAGS', '_azure_JSON_HEDLEY_FLAGS') `
.Replace('JSON_HEDLEY_FALL_THROUGH', '_azure_JSON_HEDLEY_FALL_THROUGH') `
.Replace('JSON_HEDLEY_END_C_DECLS', '_azure_JSON_HEDLEY_END_C_DECLS') `
.Replace('JSON_HEDLEY_EMSCRIPTEN_VERSION_CHECK', '_azure_JSON_HEDLEY_EMSCRIPTEN_VERSION_CHECK') `
.Replace('JSON_HEDLEY_EMSCRIPTEN_VERSION', '_azure_JSON_HEDLEY_EMSCRIPTEN_VERSION') `
.Replace('JSON_HEDLEY_EMPTY_BASES', '_azure_JSON_HEDLEY_EMPTY_BASES') `
.Replace('JSON_HEDLEY_DMC_VERSION_CHECK', '_azure_JSON_HEDLEY_DMC_VERSION_CHECK') `
.Replace('JSON_HEDLEY_DMC_VERSION', '_azure_JSON_HEDLEY_DMC_VERSION') `
.Replace('JSON_HEDLEY_DIAGNOSTIC_PUSH', '_azure_JSON_HEDLEY_DIAGNOSTIC_PUSH') `
.Replace('JSON_HEDLEY_DIAGNOSTIC_POP', '_azure_JSON_HEDLEY_DIAGNOSTIC_POP') `
.Replace('JSON_HEDLEY_DIAGNOSTIC_DISABLE_UNUSED_FUNCTION', '_azure_JSON_HEDLEY_DIAGNOSTIC_DISABLE_UNUSED_FUNCTION') `
.Replace('JSON_HEDLEY_DIAGNOSTIC_DISABLE_UNKNOWN_PRAGMAS', '_azure_JSON_HEDLEY_DIAGNOSTIC_DISABLE_UNKNOWN_PRAGMAS') `
.Replace('JSON_HEDLEY_DIAGNOSTIC_DISABLE_UNKNOWN_CPP_ATTRIBUTES', '_azure_JSON_HEDLEY_DIAGNOSTIC_DISABLE_UNKNOWN_CPP_ATTRIBUTES') `
.Replace('JSON_HEDLEY_DIAGNOSTIC_DISABLE_DEPRECATED', '_azure_JSON_HEDLEY_DIAGNOSTIC_DISABLE_DEPRECATED') `
.Replace('JSON_HEDLEY_DIAGNOSTIC_DISABLE_CPP98_COMPAT_WRAP_', '_azure_JSON_HEDLEY_DIAGNOSTIC_DISABLE_CPP98_COMPAT_WRAP_') `
.Replace('JSON_HEDLEY_DIAGNOSTIC_DISABLE_CAST_QUAL', '_azure_JSON_HEDLEY_DIAGNOSTIC_DISABLE_CAST_QUAL') `
.Replace('JSON_HEDLEY_DEPRECATED_FOR', '_azure_JSON_HEDLEY_DEPRECATED_FOR') `
.Replace('JSON_HEDLEY_DEPRECATED', '_azure_JSON_HEDLEY_DEPRECATED') `
.Replace('JSON_HEDLEY_C_DECL', '_azure_JSON_HEDLEY_C_DECL') `
.Replace('JSON_HEDLEY_CRAY_VERSION_CHECK', '_azure_JSON_HEDLEY_CRAY_VERSION_CHECK') `
.Replace('JSON_HEDLEY_CRAY_VERSION', '_azure_JSON_HEDLEY_CRAY_VERSION') `
.Replace('JSON_HEDLEY_CPP_CAST', '_azure_JSON_HEDLEY_CPP_CAST') `
.Replace('JSON_HEDLEY_CONST_CAST', '_azure_JSON_HEDLEY_CONST_CAST') `
.Replace('JSON_HEDLEY_CONSTEXPR', '_azure_JSON_HEDLEY_CONSTEXPR') `
.Replace('JSON_HEDLEY_CONST', '_azure_JSON_HEDLEY_CONST') `
.Replace('JSON_HEDLEY_CONCAT_EX', '_azure_JSON_HEDLEY_CONCAT_EX') `
.Replace('JSON_HEDLEY_CONCAT3_EX', '_azure_JSON_HEDLEY_CONCAT3_EX') `
.Replace('JSON_HEDLEY_CONCAT3', '_azure_JSON_HEDLEY_CONCAT3') `
.Replace('JSON_HEDLEY_CONCAT', '_azure_JSON_HEDLEY_CONCAT') `
.Replace('JSON_HEDLEY_COMPCERT_VERSION_CHECK', '_azure_JSON_HEDLEY_COMPCERT_VERSION_CHECK') `
.Replace('JSON_HEDLEY_COMPCERT_VERSION', '_azure_JSON_HEDLEY_COMPCERT_VERSION') `
.Replace('JSON_HEDLEY_CLANG_HAS_WARNING', '_azure_JSON_HEDLEY_CLANG_HAS_WARNING') `
.Replace('JSON_HEDLEY_CLANG_HAS_FEATURE', '_azure_JSON_HEDLEY_CLANG_HAS_FEATURE') `
.Replace('JSON_HEDLEY_CLANG_HAS_EXTENSION', '_azure_JSON_HEDLEY_CLANG_HAS_EXTENSION') `
.Replace('JSON_HEDLEY_CLANG_HAS_DECLSPEC_ATTRIBUTE', '_azure_JSON_HEDLEY_CLANG_HAS_DECLSPEC_ATTRIBUTE') `
.Replace('JSON_HEDLEY_CLANG_HAS_CPP_ATTRIBUTE', '_azure_JSON_HEDLEY_CLANG_HAS_CPP_ATTRIBUTE') `
.Replace('JSON_HEDLEY_CLANG_HAS_BUILTIN', '_azure_JSON_HEDLEY_CLANG_HAS_BUILTIN') `
.Replace('JSON_HEDLEY_CLANG_HAS_ATTRIBUTE', '_azure_JSON_HEDLEY_CLANG_HAS_ATTRIBUTE') `
.Replace('JSON_HEDLEY_BEGIN_C_DECLS', '_azure_JSON_HEDLEY_BEGIN_C_DECLS') `
.Replace('JSON_HEDLEY_ASSUME', '_azure_JSON_HEDLEY_ASSUME') `
.Replace('JSON_HEDLEY_ARRAY_PARAM', '_azure_JSON_HEDLEY_ARRAY_PARAM') `
.Replace('JSON_HEDLEY_ARM_VERSION_CHECK', '_azure_JSON_HEDLEY_ARM_VERSION_CHECK') `
.Replace('JSON_HEDLEY_ARM_VERSION', '_azure_JSON_HEDLEY_ARM_VERSION') `
.Replace('JSON_HEDLEY_ALWAYS_INLINE', '_azure_JSON_HEDLEY_ALWAYS_INLINE') `
.Replace('JSON_HAS_THREE_WAY_COMPARISON', '_azure_JSON_HAS_THREE_WAY_COMPARISON') `
.Replace('JSON_HAS_STATIC_RTTI', '_azure_JSON_HAS_STATIC_RTTI') `
.Replace('JSON_HAS_RANGES', '_azure_JSON_HAS_RANGES') `
.Replace('JSON_HAS_FILESYSTEM', '_azure_JSON_HAS_FILESYSTEM') `
.Replace('JSON_HAS_EXPERIMENTAL_FILESYSTEM', '_azure_JSON_HAS_EXPERIMENTAL_FILESYSTEM') `
.Replace('JSON_HAS_CPP_20', '_azure_JSON_HAS_CPP_20') `
.Replace('JSON_HAS_CPP_17', '_azure_JSON_HAS_CPP_17') `
.Replace('JSON_HAS_CPP_14', '_azure_JSON_HAS_CPP_14') `
.Replace('JSON_HAS_CPP_11', '_azure_JSON_HAS_CPP_11') `
.Replace('JSON_EXPLICIT', '_azure_JSON_EXPLICIT') `
.Replace('JSON_DISABLE_ENUM_SERIALIZATION', '_azure_JSON_DISABLE_ENUM_SERIALIZATION') `
.Replace('JSON_DIAGNOSTICS', '_azure_JSON_DIAGNOSTICS') `
.Replace('JSON_CATCH', '_azure_JSON_CATCH') `
.Replace('JSON_BINARY_READER_MAKE_BJD_TYPES_MAP_', '_azure_JSON_BINARY_READER_MAKE_BJD_TYPES_MAP_') `
.Replace('JSON_BINARY_READER_MAKE_BJD_OPTIMIZED_TYPE_MARKERS_', '_azure_JSON_BINARY_READER_MAKE_BJD_OPTIMIZED_TYPE_MARKERS_') `
.Replace('JSON_ASSERT', '_azure_JSON_ASSERT') `
.Replace('INCLUDE_NLOHMANN_JSON_FWD_HPP_', '_azure_INCLUDE_NLOHMANN_JSON_FWD_HPP_') `
| Set-Content sdk/core/azure-core/inc/azure/core/internal/json/json.hpp
```

**Comment by antkmsft** [comment]
Also,
```cpp
#ifndef INCLUDE_NLOHMANN_JSON_FWD_HPP_
#define INCLUDE_NLOHMANN_JSON_FWD_HPP_
```
and
```cpp
#endif // INCLUDE_NLOHMANN_JSON_FWD_HPP_
```
lines should probably be dropped, no need to prefix `INCLUDE_NLOHMANN_JSON_FWD_HPP_`.

**Comment by gearama** [comment]
@antkmsft done the changes you requested

**Review by antkmsft — APPROVED** [review]
Thank you, @gearama!

Sorry, I just found two more macros that I missed, but that should be it! - `JSON_NO_IO` and `JSON_TEST_KEEP_MACROS`.

They are never getting defined in our json.hpp, but since they are not prefixed, who knows if they will somehow end up being defined during the build process, and in my opinion, it is safer to also prefix them with `_azure_`.

Other than that, before merging, I recommend to sync with @danieljurek on how the changes to CI files are going to go, maybe he needs to merge another PR, or maybe it is fine for us to check in this change with your PR and do the global update to all Azure SDK repos later, and there will be no merge conflicts.
But of course release timing is higher priority.

I am approving the PR - I don't think that I will find anything else, and the changes look right and good to me. Thank you!

**Review by antkmsft — COMMENTED** [review]
Ah, I also think we probably should update `sdk/core/azure-core/test/nlohmann-json-test/*`.

File: sdk/core/azure-core-test/inc/azure/core/test/test_proxy_manager.hpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (ahsonkhan) [reply sdk/core/azure-core-test/inc/azure/core/test/test_proxy_manager.hpp:59]: Why doesn't it work now? Can you share more details or the error you see with using https compared to when it worked previously?

**Comment by ahsonkhan** [comment]
> The diff of the json file looks right, but is a lot. Can you outline the steps to you did to add/update the new file.

I haven't been able to review this PR yet, but given the size, I would love to understand what exact steps you took for the json library update to help make the review process quicker.

**Review by ahsonkhan — CHANGES_REQUESTED** [review]
> > Ah, I also think we probably should update `sdk/core/azure-core/test/nlohmann-json-test/*`.

As @antkmsft mentioned, we should definitely keep the source and tests versions in-sync, so an update of the nlohmann json source should be together with the test update as well.

Please address this before merging, at the very least. I'll try to review the rest, tomorrow, but would like some help in making reviewing this change easier. What should we focus on?

**Comment by antkmsft** [comment]
@ahsonkhan, it does pass the existing tests (both nlohmann JSON and Azure SDK), so I don't think it should be blocked from Beta release at least, but it would be better if we fetch 3.11.3 unit test updates as part of the same PR well.

File: sdk/core/azure-core-test/inc/azure/core/test/test_proxy_manager.hpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (gearama) [reply sdk/core/azure-core-test/inc/azure/core/test/test_proxy_manager.hpp:59]: previously it was working as expected, now the error i see is cannot connect to https://localhost:5001 from curl , no more info as to why. i switched to http as it's what the pipelines use for the start / is alive / logs steps for the test-proxy when they start it. 
The error only happens on macOS 14 previously it was working, and i do not posses a mac dev box to debug the issue,

**Comment by LarryOsterman** [comment]
> > > Ah, I also think we probably should update `sdk/core/azure-core/test/nlohmann-json-test/*`.
> 
> As @antkmsft mentioned, we should definitely keep the source and tests versions in-sync, so an update of the nlohmann json source should be together with the test update as well.
> 
> Please address this before merging, at the very least. I'll try to review the rest, tomorrow, but would like some help in making reviewing this change easier. What should we focus on?

I'd like to make sure that the existing tests run with the newer json library, to be honest. If there are any breaking changes in the nlohmann implementation, the old tests will start failing, but the new tests would have accounted for any breaking changes.

Since our implementation was built around the old implementation, we should keep the old tests for at least the first iteration of this PR.

Once the PR is in and we've run at least a single nightly build on the new implementation with the old tests, we should integrate the new tests. 

Basically, we start by using the old tests to help ensure that the new json library won't break us, then switch to the new tests to ensure that if we have tests covering any new additions to the library.

**Review by LarryOsterman — APPROVED** [review]

**Comment by gearama** [comment]
> > > > Ah, I also think we probably should update `sdk/core/azure-core/test/nlohmann-json-test/*`.
> > 
> > 
> > As @antkmsft mentioned, we should definitely keep the source and tests versions in-sync, so an update of the nlohmann json source should be together with the test update as well.
> > Please address this before merging, at the very least. I'll try to review the rest, tomorrow, but would like some help in making reviewing this change easier. What should we focus on?
> 
> I'd like to make sure that the existing tests run with the newer json library, to be honest. If there are any breaking changes in the nlohmann implementation, the old tests will start failing, but the new tests would have accounted for any breaking changes.
> 
> Since our implementation was built around the old implementation, we should keep the old tests for at least the first iteration of this PR.
> 
> Once the PR is in and we've run at least a single nightly build on the new implementation with the old tests, we should integrate the new tests.
> 
> Basically, we start by using the old tests to help ensure that the new json library won't break us, then switch to the new tests to ensure that if we have tests covering any new additions to the library.

while i would agree with you there are api changes in the internal iml of the tests , the old ones don't compile properly , thus i had to update. 

As mentioned in the description i ran all the CI pipelines that IMHO cover most if not all of the public interface , thus the functionality out of it that we use is covered , if we want to run some coverage tools to determine dead code in the json that we don't use that i would like to do to remove uneeded functionality, only that future updates would be harder to perform as we would need to determine what we removed and where it is and get rid of them again.

**Comment by LarryOsterman** [comment]
> 
> We can talk about it more monday, i did not bring this up thursday as that meeting was too clogged with go lang issues :)

So be it. I was hoping to avoid doing even more work to update the tests, but if the existing tests break, so be it.

**Comment by antkmsft** [comment]
Reminder, in case this got lost - 
> Sorry, I just found two more macros that I missed, but that should be it! - `JSON_NO_IO` and `JSON_TEST_KEEP_MACROS`.

I can now see `JSON_NO_IO` renamed, but not the `JSON_TEST_KEEP_MACROS`.

**Comment by gearama** [comment]
> Reminder, in case this got lost -
> 
> > Sorry, I just found two more macros that I missed, but that should be it! - `JSON_NO_IO` and `JSON_TEST_KEEP_MACROS`.
> 
> I can now see `JSON_NO_IO` prefixed, but the `JSON_TEST_KEEP_MACROS` is still unprefixed.

done, i somehow missed that

**Review by antkmsft — APPROVED** [review]
Re-approving, looks good - thank you!, I think we should merge it. Plus, we've just made all the monthly releases.

File: eng/pipelines/templates/jobs/ci.tests.yml (hunk 4 above)
Comment (ahsonkhan) [reply eng/pipelines/templates/jobs/ci.tests.yml:189]: With https://github.com/Azure/azure-sdk-tools/pull/8373/ and the sync https://github.com/Azure/azure-sdk-for-cpp/pull/5699 merged, do we still need this change?

It seems like the default is "Major", now.

File: sdk/core/azure-core/CHANGELOG.md [hunk 5]
```diff
@@ -20,6 +20,7 @@
 
 - [[#5622]](https://github.com/Azure/azure-sdk-for-cpp/pull/5622) Documentation fix for building the SDK with specific OpenSSL version.  (A community contribution, courtesy of _[ByteYue](https://github.com/ByteYue)_)
 - [[#5515]](https://github.com/Azure/azure-sdk-for-cpp/issues/5515) Add a `ShouldRetry` virtual method to the retry policy to enable customization of service-specific retry logic.
+- Updated JSON library to 3.11.3.
```
Comment (ahsonkhan) [inline sdk/core/azure-core/CHANGELOG.md:23]: We shipped this beta out already.  Move to the `Other changes` section of `1.13.0-beta.2 (Unreleased)`

File: sdk/core/azure-core/test/nlohmann-json-test/CMakeLists.txt [hunk 6]
```diff
@@ -45,10 +45,17 @@ endif()
 #############################################################################
 
 set(files
+    src/make_test_data_available.hpp
+    src/test_utils.hpp
```
Comment (ahsonkhan) [inline sdk/core/azure-core/test/nlohmann-json-test/CMakeLists.txt:49]: It seems like the only uses of `test_utils.hpp` are in test files that we are not including (we commented those out).

https://github.com/search?q=repo%3Anlohmann%2Fjson+test_utils.hpp&type=code

unit-bson.cpp
unit-ubjson.cpp
unit-bjdata.cpp
unit-cbor.cpp
unit-msgpack.cpp

Can we remove this file rather than checking it in?

Also, this header files doesn't seem to be included in the nlohmann.json CMakeLists.txt directly. Do you know how nlohmann is including these headers?

File: sdk/core/azure-core/CHANGELOG.md (hunk 5 above)
Comment (gearama) [reply sdk/core/azure-core/CHANGELOG.md]: good point, done

File: sdk/core/azure-core/test/nlohmann-json-test/CMakeLists.txt [hunk 7]
```diff
@@ -59,12 +66,16 @@ set(files
     src/unit-concepts.cpp
     src/unit-constructor1.cpp
     src/unit-constructor2.cpp
-    src/unit-convenience.cpp
+    #src/unit-convenience.cpp               - Not Required.
```
[the remark this answers is not in the document]
Comment (gearama) [reply sdk/core/azure-core/test/nlohmann-json-test/CMakeLists.txt:69]: i'm getting some weird build errors that cannot fix

File: sdk/core/azure-core/test/nlohmann-json-test/CMakeLists.txt [hunk 8]
```diff
@@ -59,12 +66,16 @@ set(files
...
     src/unit-conversions.cpp
+    src/unit-custom-base-class.cpp
     src/unit-deserialization.cpp
+    src/unit-diagnostics.cpp
+    src/unit-disabled_exceptions.cpp
     src/unit-element_access1.cpp
     src/unit-element_access2.cpp
-    src/unit-inspection.cpp
+    src/unit-hash.cpp
+    #src/unit-inspection.cpp                - Not Required.
```
[the remark this answers is not in the document]
Comment (gearama) [reply sdk/core/azure-core/test/nlohmann-json-test/CMakeLists.txt:78]: same here

File: sdk/core/azure-core/test/nlohmann-json-test/CMakeLists.txt (hunk 6 above)
Comment (gearama) [reply sdk/core/azure-core/test/nlohmann-json-test/CMakeLists.txt:49]: good catch, done

**Comment by ahsonkhan** [comment]
Just to understand, how come we remove `INCLUDE_NLOHMANN_JSON_HPP_` instead of renaming it?

image

**Review by ahsonkhan — APPROVED** [review]
I eye-balled the diff between nlohmann json and our vendored copy, and it looks reasonable.

Seems like most of the changes are covered by:
- Adding the `_azure_` prefix to macros
- Modifying the namespaces
- Clang-format formatting

Thanks for updating the library, @gearama!

File: eng/pipelines/templates/jobs/ci.tests.yml (hunk 4 above)
Comment (ahsonkhan) [reply eng/pipelines/templates/jobs/ci.tests.yml:189]: @gearama in case you missed this:
https://github.com/Azure/azure-sdk-for-cpp/pull/5681#discussion_r1638525904

> With [Azure/azure-sdk-tools#8373](https://github.com/Azure/azure-sdk-tools/pull/8373) and the sync #5699 merged, do we still need this change?
> 
> It seems like the default is "Major", now.

File: eng/pipelines/templates/jobs/ci.tests.yml [hunk 9]
```diff
@@ -184,6 +184,10 @@ jobs:
             ServiceDirectory: ${{ parameters.ServiceDirectory }}
             TestPipeline: ${{ parameters.TestPipeline }}
 
+      - pwsh: |
+          Write-Host "##vso[task.setvariable variable=DOTNET_ROLL_FORWARD]Major"
```
Comment (ahsonkhan) [inline eng/pipelines/templates/jobs/ci.tests.yml:188]: @gearama in case you missed this:
https://github.com/Azure/azure-sdk-for-cpp/pull/5681#discussion_r1638525904

> With [Azure/azure-sdk-tools#8373](https://github.com/Azure/azure-sdk-tools/pull/8373) and the sync #5699 merged, do we still need this change?
> 
> It seems like the default is "Major", now.

**Comment by antkmsft** [comment]
@gearama, could you please drop all the occurrences of
```cpp
/*!
@brief namespace for Niels Lohmann
@see
https://github.com/nlohmann
@since version 1.0.0
*/
```?

The reason is that I used doxygen to generate docs, and what it does is that it ends up attaching `namespace for Niels Lohmann` as a description for `Azure` namespace (not the `Azure::Core::Json::_internal`).

File: eng/pipelines/templates/jobs/ci.tests.yml (hunk 9 above)
Comment (gearama) [reply eng/pipelines/templates/jobs/ci.tests.yml:188]: yes, i discussed it with Daniel separatelly, the basic idea is Scott hardcoded the proxy version that we use in our repo, in order to use the latest version of the proxy that has the framework built in ( to avoid using externaal dep) i have to make update / test the new proxy version. I would rather do it separatelly from this work to not make this PR into a mega convolutes PR with all the changes packed in

File: eng/pipelines/templates/jobs/ci.tests.yml (hunk 4 above)
Comment (gearama) [reply eng/pipelines/templates/jobs/ci.tests.yml:189]: yes, we still need it , the changes made in the test proxy need to be brought inoto our repo , anbd i don't want to pack it in with this change.

File: eng/pipelines/templates/jobs/ci.tests.yml (hunk 9 above)
Comment (ahsonkhan) [reply eng/pipelines/templates/jobs/ci.tests.yml:188]: Ah, that make sense! Thanks

**Review by antkmsft — APPROVED** [review]
