### PR TITLE
Fix link errors when producing a DLL, add UWP compilation support

### LINKED ISSUE #1168: Support for UWP
I noticed that we do not support UWP in the vcpkg cmake file https://github.com/Azure/azure-sdk-for-cpp/blob/1699bb72d5c656965f812468f0ed4e9651f515ac/sdk/core/azure-core/vcpkg/portfile.cmake#L4 and CONTROL file https://github.com/Azure/azure-sdk-for-cpp/blob/1699bb72d5c656965f812468f0ed4e9651f515ac/sdk/core/azure-core/vcpkg/CONTROL#L7

Storage team does have customers ever asking for UWP support. One of them even tried days ago, this sdk now can work with UWP application.

So is there any reason to not support UWP?

### LINKED ISSUE #1234: build error in azure-core on Windows
We do want to support dynamic libraries, right?

Windows 10 Pro Version 2004
Microsoft Visual Studio Community 2019 Version 16.8.2

```cmd
cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/ProgramFiles/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING=ON -DBUILD_STORAGE_SAMPLES=ON -DCMAKE_CXX_FLAGS="/MP /EHsc" -A x64 -DBUILD_SHARED_LIBS=ON
cmake --build .
```

error message:

```
logging.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::Logging::LogClassifications
const Azure::Core::Logging::LogClassification::All" (?All@LogClassification@Logging@Core@Azure@@2VLogClassifications@23
4@B) [C:\Users\Jamis\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
logging.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::Logging::LogClassifications
const Azure::Core::Logging::LogClassification::None" (?None@LogClassification@Logging@Core@Azure@@2VLogClassifications@
234@B) [C:\Users\Jamis\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus const Azur
e::Core::OperationStatus::NotStarted" (?NotStarted@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\azure-s
dk-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation_status.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus con
st Azure::Core::OperationStatus::NotStarted" (?NotStarted@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\
azure-sdk-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus const Azur
e::Core::OperationStatus::Running" (?Running@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\azure-sdk-for
-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation_status.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus con
st Azure::Core::OperationStatus::Running" (?Running@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\azure-
sdk-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus const Azur
e::Core::OperationStatus::Succeeded" (?Succeeded@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\azure-sdk
-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation_status.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus con
st Azure::Core::OperationStatus::Succeeded" (?Succeeded@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\az
ure-sdk-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus const Azur
e::Core::OperationStatus::Cancelled" (?Cancelled@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\azure-sdk
-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation_status.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus con
st Azure::Core::OperationStatus::Cancelled" (?Cancelled@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\az
ure-sdk-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus const Azur
e::Core::OperationStatus::Failed" (?Failed@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\azure-sdk-for-c
pp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
operation_status.obj : error LNK2001: unresolved external symbol "public: static class Azure::Core::OperationStatus con
st Azure::Core::OperationStatus::Failed" (?Failed@OperationStatus@Core@Azure@@2V123@B) [C:\Users\Jamis\Desktop\azure-sd
k-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test.vcxproj]
C:\Users\Jamis\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core\test\ut\Debug\azure-core-test.exe : fatal error LNK1
120: 7 unresolved externals [C:\Users\Jamis\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core\test\ut\azure-core-test
.vcxproj]
```

### LINKED ISSUE #1367: Investigate and fix building and linking azure-identity and azure-core on arm64-windows.
Figure out and fix the linker issue between azure-identity and `DateTime`, specifically the private static `SystemClockEpoch` on arm64-windows.

See for more context:
https://github.com/azure-sdk/vcpkg/pull/3
https://github.com/microsoft/vcpkg/pull/15635

We probably also want to investigate how we can add this configuration in our CI, but that is a separate issue: https://github.com/Azure/azure-sdk-for-cpp/issues/1368

cc @antkmsft

### PR DESCRIPTION
**Pull request by antkmsft**
Fixes #1168.
Fixes #1367.
Fixes #1234.

* Correct compilation without transport adapters - actually a good fix regardless.
  * Transport headers did rely on the macros being defined by Cmake when building the SDK. This will not work when customer consumes the SDK and includes our headers in their project.
  * Also, DefineTransportAdapter would go and override the parameters given to the build (`SET(BUILD_TRANSPORT_WINHTTP ON)`, `SET(BUILD_TRANSPORT_CURL ON)`), which for sure should not be the behavior at least when compiling for VcPkg.

* static variables have still to be marked as dllimport/export (https://cmake.org/cmake/help/v3.13/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html)

### CODE REVIEW

**Comment by vhvb1989** [comment]
> Transport headers did rely on the macros being defined by Cmake when building the SDK.

This was changed some days ago. The header calls a function to get the default transport adapter. Then the cpp file implements that function based on CMake macros

**Comment by vhvb1989** [comment]
Setting milestone to Feb since this looks like still needs some more work to do

**Comment by Jinming-Hu** [comment]
> Setting milestone to Feb since this looks like still needs some more work to do

Are we going to ship on vcpkg for Jan. release?

**Comment by ahsonkhan** [comment]
> Are we going to ship on vcpkg for Jan. release?

Yes.

File: sdk/core/azure-core/inc/azure/core/datetime.hpp [hunk 1]
```diff
@@ -8,6 +8,8 @@
 
 #pragma once
 
+#include <azure/core/export.hpp>
```
Comment (RickWinter) [inline sdk/core/azure-core/inc/azure/core/datetime.hpp:11]:
```suggestion
#include "azure/core/export.hpp"
```

File: sdk/core/azure-core/inc/azure/core/export.hpp [hunk 2]
```diff
@@ -0,0 +1,23 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
```
Comment (RickWinter) [inline sdk/core/azure-core/inc/azure/core/export.hpp:1]: Add this file to core.hpp

File: sdk/core/azure-core/inc/azure/core/logging/logging.hpp [hunk 3]
```diff
@@ -9,6 +9,8 @@
 
 #pragma once
 
+#include <azure/core/export.hpp>
```
Comment (RickWinter) [inline sdk/core/azure-core/inc/azure/core/logging/logging.hpp:12]:
```suggestion
#include "azure/core/export.hpp"
```

File: sdk/core/azure-core/inc/azure/core/operation_status.hpp [hunk 4]
```diff
@@ -9,6 +9,8 @@
 
 #pragma once
 
+#include <azure/core/export.hpp>
```
Comment (RickWinter) [inline sdk/core/azure-core/inc/azure/core/operation_status.hpp:12]:
```suggestion
#include "azure/core/export.hpp"
```

File: sdk/core/azure-core/inc/azure/core/version.hpp [hunk 5]
```diff
@@ -8,6 +8,8 @@
 
 #pragma once
 
+#include <azure/core/export.hpp>
```
Comment (RickWinter) [inline sdk/core/azure-core/inc/azure/core/version.hpp:11]:
```suggestion
#include "azure/core/export.hpp"
```

File: sdk/core/azure-core/src/http/telemetry_policy.cpp [hunk 6]
```diff
@@ -78,6 +78,12 @@ std::string GetOSVersion()
 
 } // namespace
 
+#else
```
Comment (RickWinter) [inline sdk/core/azure-core/src/http/telemetry_policy.cpp:81]: Rather than defining the method twice, put the ifdef in the function

File: sdk/core/azure-core/src/http/transport_policy.cpp [hunk 7]
```diff
@@ -3,6 +3,14 @@
 
 #include "azure/core/http/policy.hpp"
 
+#if defined(BUILD_CURL_HTTP_TRANSPORT_ADAPTER)
+#include <azure/core/http/curl/curl.hpp>
```
Comment (RickWinter) [inline sdk/core/azure-core/src/http/transport_policy.cpp:7]:
```suggestion
#include "azure/core/http/curl/curl.hpp"
```

File: sdk/core/azure-core/src/http/transport_policy.cpp [hunk 8]
```diff
@@ -3,6 +3,14 @@
...
+#endif
+
+#if defined(BUILD_TRANSPORT_WINHTTP_ADAPTER)
+#include <azure/core/http/winhttp/win_http_client.hpp>
```
Comment (RickWinter) [inline sdk/core/azure-core/src/http/transport_policy.cpp:11]:
```suggestion
#include "azure/core/http/winhttp/win_http_client.hpp"
```

**Review by RickWinter — CHANGES_REQUESTED** [review]
Please update the includes to follow our guidelines on "" vs <>

File: sdk/identity/azure-identity/inc/azure/identity/export.hpp [hunk 9]
```diff
@@ -0,0 +1,23 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
```
Comment (RickWinter) [inline sdk/identity/azure-identity/inc/azure/identity/export.hpp:1]: Why two copies on this macro?  Its part of core and core is part of identity.  Just use it from CORE.  Additionally we could make it "AZ_EXPORT" or "AZURE_EXPORT"

**Review by vhvb1989 — APPROVED** [review]

File: sdk/identity/azure-identity/inc/azure/identity/export.hpp (hunk 9 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/inc/azure/identity/export.hpp:1]: No, you don't get it, that's the whole point. We should not reuse, each library has to have its own. So that when you are compiling core, it is seen as `__declspec(dllexport)`. When you are including the very same file from identity, it is seen as `__declspec(dllimport)`.

Comment (antkmsft) [reply sdk/identity/azure-identity/inc/azure/identity/export.hpp:1]: This is a pretty common idiom: https://stackoverflow.com/questions/14980649/macro-for-dllexport-dllimport-switch

**Comment by antkmsft** [comment]
@RickWinter, I addressed your feedback, please take a look!

File: sdk/identity/azure-identity/inc/azure/identity/export.hpp (hunk 9 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/inc/azure/identity/export.hpp:1]: and it is not a copy, they are named correspondingly to a library - `AZ_CORE_EXPORT`, `AZ_IDENTITY_EXPORT` etc.

Comment (RickWinter) [reply sdk/identity/azure-identity/inc/azure/identity/export.hpp:1]: Ah, the naming is confusing since its an import in some cases.

**Review by RickWinter — APPROVED** [review]

**Review by RickWinter — CHANGES_REQUESTED** [review]
Please address "" vs <>.  There are still some instances using the wrong pattern

**Comment by antkmsft** [comment]
@RickWinter , I'm sorry, I actually forgot to push the commit with all the fixes when I pinged you. I pushed it now, here is the diff: https://github.com/Azure/azure-sdk-for-cpp/pull/1346/commits/1fb2756fb25407ab20078f36c0483fdfde18f2da

**Comment by ahsonkhan** [comment]
@antkmsft how confident are we this will build on UWP and arm64? What's the approach for testing and how do we make sure the repo remains green going forward. It is fine if the test automation is outside the scope of this PR, but I would love to understand the testing and our plan for next steps.
Before we merge this, can we create a PR in vcpkg for core and identity based on this change and see if that CI is green?

File: cmake-modules/global_compile_options.cmake [hunk 10]
```diff
@@ -13,6 +13,11 @@ if(MSVC)
 
   #https://stackoverflow.com/questions/37527946/warning-unreferenced-inline-function-has-been-removed
   add_compile_options(/W4 ${WARNINGS_AS_ERRORS_FLAG} /wd5031 /wd4668 /wd4820 /wd4255 /wd4710)
+
+  # Since we could be built as either DLL or a static library, when we are built as static library,
+  # linker does generate a bunch of warnings related to the use of dllimport attribute,
+  # basically, suggesting that its use is unneccessary. We know that.
+  add_link_options(/ignore:4217 /ignore:4286)
```
Comment (ahsonkhan) [inline cmake-modules/global_compile_options.cmake:20]: Can we put this under a condition, so we only ignore these warnings when building as a static library? Is there a way to detect which flavor of the SDK we are building?

File: sdk/core/azure-core/inc/azure/core/export.hpp [hunk 11]
```diff
@@ -0,0 +1,23 @@
...
+ */
+
+// We use CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS which does most of the job for us, but static data
+// members do still need to be declared as __declspec(dllimport) for the client code. (See
+// https://cmake.org/cmake/help/v3.13/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html)
+
+#pragma once
+
+#if defined(_MSC_VER)
+#if defined(AZ_CORE_EXPORTS)
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/export.hpp:16]: When would this be false, i.e. when would `AZ_CORE_EXPORTS` not be defined?

**Comment by antkmsft** [comment]
@ahsonkhan , I built locallu as `x64-windows-static`,, `x64-windows`, `arm64-windows`, `arm-uwp`, `x64-uwp`, `x86-uwp`, and `arm64-uwp`. I can create a PR against the VCPkg repo, referencing my repo, as I did before.

File: sdk/core/azure-core/CMakeLists.txt [hunk 12]
```diff
@@ -7,6 +7,7 @@ project(azure-core LANGUAGES CXX)
 set(CMAKE_CXX_STANDARD 14)
 set(CMAKE_CXX_STANDARD_REQUIRED True)
 set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
+add_compile_definitions(AZ_CORE_EXPORTS)
```
Comment (ahsonkhan) [inline sdk/core/azure-core/CMakeLists.txt:10]: Since this is only relevant for msvc and windows, can we add a windows suffix both here and to the export.hpp file name. Also, export is somewhat generic and could be overloaded or cause confusion:
```suggestion
add_compile_definitions(AZ_CORE_DLL_EXPORTS_WINDOWS)
```

File: sdk/core/azure-core/inc/azure/core.hpp [hunk 13]
```diff
@@ -14,6 +14,7 @@
 #include "azure/core/context.hpp"
 #include "azure/core/credentials.hpp"
 #include "azure/core/datetime.hpp"
+#include "azure/core/export.hpp"
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core.hpp:17]: Any way to test the inclusion of this header within
https://github.com/Azure/azure-sdk-for-cpp/blob/a5f113e647710450870674e2270f75951f36914a/sdk/core/azure-core/test/ut/simplified_header.cpp#L16

File: sdk/core/azure-core/inc/azure/core/datetime.hpp [hunk 14]
```diff
@@ -48,8 +50,7 @@ namespace Azure { namespace Core {
    * @remark This class is supposed to be able to handle a DateTime that comes over the wire.
    */
   class DateTime : public Details::Clock::time_point {
-    static DateTime const SystemClockEpoch;
-
+    AZ_CORE_EXPORT static DateTime const SystemClockEpoch;
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/datetime.hpp:53]: Do we really need this static `DateTime` or is there a way to re-write the implementation to avoid it? What's its purpose?

File: sdk/core/azure-core/CMakeLists.txt [hunk 15]
```diff
@@ -69,6 +70,7 @@ set(
     inc/azure/core/credentials.hpp
     inc/azure/core/datetime.hpp
     inc/azure/core/exception.hpp
+    inc/azure/core/export.hpp
```
Comment (ahsonkhan) [inline sdk/core/azure-core/CMakeLists.txt:73]: Maybe:
```suggestion
    inc/azure/core/dll_export_windows.hpp
```

Do we expect any customer to directly/individually include this header?

File: sdk/core/azure-core/inc/azure/core/export.hpp [hunk 16]
```diff
@@ -0,0 +1,23 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// SPDX-License-Identifier: MIT
+
+/**
+ * @file
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/export.hpp:5]: Consider renaming this and elsewhere to be:
`dll_export_windows.hpp`, or at least `dll_export.hpp`

File: sdk/core/azure-core/inc/azure/core/http/policy.hpp [hunk 17]
```diff
@@ -15,11 +15,6 @@
 #include "azure/core/logging/logging.hpp"
 #include "azure/core/uuid.hpp"
 
-// Need to include the transport adapters offered by the SDK here so anyone can use them by just
-// including policy.hpp
-#include "azure/core/http/curl/curl.hpp"
-#include "azure/core/http/winhttp/win_http_client.hpp"
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/http/policy.hpp:21]: @antkmsft why can we remove this now? @vhvb1989, does the initial reason these were added (from the comments) no longer hold true?

File: sdk/core/azure-core/inc/azure/core/operation_status.hpp [hunk 18]
```diff
@@ -9,6 +9,8 @@
 
 #pragma once
 
+#include "azure/core/export.hpp"
+
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/operation_status.hpp:13]: nit: Is this necessary here? Why?
```suggestion
```

File: sdk/core/azure-core/inc/azure/core/version.hpp [hunk 19]
```diff
@@ -32,7 +34,7 @@ namespace Azure { namespace Core { namespace Details {
     static constexpr int Patch = AZURE_CORE_VERSION_PATCH;
 
     /// Optional pre-release identifier. SDK is in a pre-release state when not empty.
-    static std::string const PreRelease;
+    AZ_CORE_EXPORT static std::string const PreRelease;
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/version.hpp:37]: Once merged, we should add this in the guidelines about statics and update our extensible enum section:
https://azure.github.io/azure-sdk/cpp_implementation.html#enumerations

cc @CaseyCarter

File: sdk/core/azure-core/inc/azure/core/export.hpp [hunk 20]
```diff
@@ -0,0 +1,23 @@
...
+// https://cmake.org/cmake/help/v3.13/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html)
+
+#pragma once
+
+#if defined(_MSC_VER)
+#if defined(AZ_CORE_EXPORTS)
+#define AZ_CORE_EXPORT __declspec(dllexport)
+#else
+#define AZ_CORE_EXPORT __declspec(dllimport)
+#endif
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/export.hpp:20]: I am afraid I am not an expert here, @BillyONeal and @CaseyCarter can you please help review this change as well. Appreciate it!

File: sdk/core/azure-core/src/http/telemetry_policy.cpp [hunk 21]
```diff
@@ -17,13 +16,17 @@
...
+#endif
 
 namespace {
-
 std::string GetOSVersion()
 {
   std::ostringstream osVersionInfo;
 
+#if defined(AZ_PLATFORM_WINDOWS)
+#if !defined(WINAPI_PARTITION_DESKTOP) || WINAPI_PARTITION_DESKTOP
```
Comment (ahsonkhan) [inline sdk/core/azure-core/src/http/telemetry_policy.cpp:29]: Wait I am confused, isn't this `if !A || A` which is always true?

File: sdk/core/azure-core/src/http/transport_policy.cpp [hunk 22]
```diff
@@ -14,8 +22,10 @@ std::shared_ptr<HttpTransport> Azure::Core::Http::Details::GetTransportAdapter()
   return ::AzureSdkGetCustomHttpTransport();
 #elif defined(BUILD_TRANSPORT_WINHTTP_ADAPTER)
   return std::make_shared<Azure::Core::Http::WinHttpTransport>();
-#else
+#elif defined(BUILD_CURL_HTTP_TRANSPORT_ADAPTER)
   return std::make_shared<Azure::Core::Http::CurlTransport>();
+#else
+  return std::shared_ptr<HttpTransport>();
```
Comment (ahsonkhan) [inline sdk/core/azure-core/src/http/transport_policy.cpp:28]: Does this change adhere to the behavior we want? Why do we have this `else` case and what does returning a pointer to an unimplemented `HttpTransport` base class mean?

If the user doesn't explicitly pick anything (i.e. use the SDK right out of the box), we want curl to be used by default on linux/posix.

File: sdk/core/azure-core/inc/azure/core/http/winhttp/win_http_client.hpp [hunk 23]
```diff
@@ -7,8 +7,6 @@
 
 #pragma once
 
-#if defined(BUILD_TRANSPORT_WINHTTP_ADAPTER)
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/http/winhttp/win_http_client.hpp:10]: I am curious what's the benefit of removing this from the header file and push it onto each user who includes it (like the winhttp cpp file)? Trying to understand the motivation of this change.

File: sdk/core/azure-core/test/ut/CMakeLists.txt [hunk 24]
```diff
@@ -66,6 +66,11 @@ if (MSVC)
   #             - 'testing::TestPartResult::Type'
   #           is unscoped. Prefer 'enum class' over 'enum' (Enum.3)
   target_compile_options(azure-core-test PUBLIC /wd26495 /wd26812)
+
+  # Since we could be built as either DLL or a static library, when we are built as static library,
+  # linker does generate a bunch of warnings related to the use of dllimport attribute,
+  # basically, suggesting that its use is unneccessary. We know that.
+  target_link_options(azure-core-test PRIVATE  /ignore:4217 /ignore:4286)
```
Comment (ahsonkhan) [inline sdk/core/azure-core/test/ut/CMakeLists.txt:73]: Is this necessary for tests? We don't ship them. Do we build the tests as both static and dynamic as well?

**Comment by antkmsft** [comment]
@ahsonkhan, I updated the VcPkg test PR to target the changes from this branch: https://github.com/microsoft/vcpkg/pull/15471

File: sdk/core/azure-core/vcpkg/CONTROL [hunk 25]
```diff
@@ -7,17 +7,16 @@ Build-Depends: curl, nlohmann-json
 Description: Microsoft Azure Core SDK for C++
   This library provides shared primitives, abstractions, and helpers for modern Azure SDK client libraries written in the C++.
 Homepage: https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/core/azure-core
-Supports: !uwp
 Default-Features: http
 
 Feature: http
-Build-Depends: azure-core-cpp[core, curl], azure-core-cpp[core, curl, winhttp] (windows)
+Build-Depends: azure-core-cpp[core, curl], azure-core-cpp[core, curl, winhttp] (windows&!uwp)
```
Comment (ahsonkhan) [inline sdk/core/azure-core/vcpkg/CONTROL:13]: So, if winhttp doesn't work for uwp, is the only solution for someone building the SDK on Windows to send HTTP requests, to use curl or their own http stack? We probably want to document that somewhere.

File: cmake-modules/global_compile_options.cmake (hunk 10 above)
Comment (ahsonkhan) [reply cmake-modules/global_compile_options.cmake:20]: nit: In one place where these warnings are ignored, add links to the warning
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4217?view=msvc-160
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4286?view=msvc-160

Or copy the text as a comment:
```cmake
# LNK4217: symbol 'symbol' defined in 'filename_1.obj' is imported by 'filename_2.obj' in function 'function'
# LNK4286: symbol 'symbol' defined in 'filename_1.obj' is imported by 'filename_2.obj'
```

File: sdk/identity/azure-identity/inc/azure/identity/export.hpp (hunk 9 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/inc/azure/identity/export.hpp:1]: That's also idiomatic. The tings I've seen the most do actually look like this:
```
#ifdef xxx_EXPORTS
#define xxx_EXPORT __declspec(dllexport)
#else
#define xxx_EXPORT __declspec(dllimport)
#endif
```

**Review by ahsonkhan — COMMENTED** [review]
Partial review.

File: sdk/identity/azure-identity/inc/azure/identity/export.hpp (hunk 9 above)
Comment (ahsonkhan) [reply sdk/identity/azure-identity/inc/azure/identity/export.hpp:1]: > No, you don't get it, that's the whole point. We should not reuse, each library has to have its own. So that when you are compiling core, it is seen as `__declspec(dllexport)`. When you are including the very same file from identity, it is seen as `__declspec(dllimport)`.

I too was confused by this at first glance before I read your explanation. Anton, consider adding these details and clarifying explanation as a comment.

File: sdk/core/azure-core/src/http/telemetry_policy.cpp (hunk 21 above)
Comment (RickWinter) [reply sdk/core/azure-core/src/http/telemetry_policy.cpp:29]: Good catch :)

**Review by RickWinter — APPROVED** [review]

File: sdk/core/azure-core/src/http/telemetry_policy.cpp (hunk 21 above)
Comment (antkmsft) [reply sdk/core/azure-core/src/http/telemetry_policy.cpp:29]: No, no! What are you talking about? :)
It IS correct.
It says "`if IsDesktop is not DEFINED or if IsDesktop()`". Two different things.
Basically, if you compile on where `WINAPI_PARTITION_DESKTOP` is not defined, it is a pre-UWP-era Windows machine, compile as windows Desktop. Otherwise, if you compile on some Win10 machine, with an SDK that does know about UWP and non-UWP being out there, then ask what `WINAPI_PARTITION_DESKTOP` is telling you. It is supposed to evaluate to true if building for good old Win32 as we know it, and false otherwise.

File: sdk/core/azure-core/CMakeLists.txt (hunk 12 above)
Comment (Jinming-Hu) [reply sdk/core/azure-core/CMakeLists.txt]: I believe things like this will cause issues on Windows sometimes. We only need the dllexport/dllimport for dynamic libraries, not static libraries.

Comment (Jinming-Hu) [reply sdk/core/azure-core/CMakeLists.txt]: You can take reference from what we're doing for cpplite

https://github.com/Azure/azure-storage-cpplite/blob/master/include/storage_EXPORTS.h
https://github.com/Azure/azure-storage-cpplite/blob/be490edaf413dc113d8182cbc7a29140d3a63481/CMakeLists.txt#L157

File: sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/dllexport.hpp [hunk 26]
```diff
@@ -0,0 +1,21 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// SPDX-License-Identifier: MIT
+
+/**
+ * @file
+ * @brief This file defines a macro for DLL export.
+ */
+
+// For explanation, see the comment in azure/core/dllexport.hpp
```
Comment (ahsonkhan) [inline sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/dllexport.hpp:9]: Maybe make the filename: `dll_import_export.hpp`

File: cmake-modules/global_compile_options.cmake (hunk 10 above)
Comment (antkmsft) [reply cmake-modules/global_compile_options.cmake]: Now the warning suppression is not even needed!
We either:
* carry the knowledge the the library was build as DLL via build definitions (fetchcontent case)
* or, for vcpkg, when it is installed, we patch the header. And there is no problem, because VcPkg puts headers from different triplets into different directories.

As a result, it is never the case that you are linking with a static library, but have to deal with a symbol marked as `declspec(dllimport)`. In sttic bilds, they are simply nonexistent, just as before. In fact, they are nonexistent anywhere, but only when Windows DLL gets built.

File: sdk/core/azure-core/CMakeLists.txt (hunk 12 above)
Comment (antkmsft) [reply sdk/core/azure-core/CMakeLists.txt]: I have updated our approach, it is better. You use `defined(_WINDLL)`, and it does not work when customer is building a DLL or exe, but is linking with a static azure SDK library.

The way I put it now is that `declspec(dllimport/export)` only exists in Windows builds when the library is being built as DLL, and is a no-op in all other cases.
Then,
* we either carry the knowledge that the SDK lib was built as Windows DLL via `target_compile_definitions(lib PUBLIC macro)` - this is the case when a customer consumes our library via `fetchcontent()`
* or, when we install the library as a VcPackage, install step would patch the `dll_import_export.hpp` header when the library is being built as Windows DLL. And there is no conflict there, because on VcPkg, if you build for both static and DLL, your headers are in two separate locations of their own.

File: sdk/core/azure-core/vcpkg/CONTROL (hunk 25 above)
Comment (antkmsft) [reply sdk/core/azure-core/vcpkg/CONTROL:13]: WinHTTP supports `WINAPI_FAMILY_SYSTEM`, `WINAPI_FAMILY_SERVER`, `WINAPI_FAMILY_GAMES`, and `WINAPI_FAMILY_DESKTOP_APP` (see `winhttp.h`). When VcPkg builds for "uwp" configuration, it is `WINAPI_FAMILY_PC_APP`, which is none of the above. So, it is not even the case that WinHTTP is only supported on some of the UWP. It isn't supported on any. At least in VcPkg's definition of "uwp". If you think this is still a problem and needs to be documented more broadly, please create a work item or a PR. I am not sure what is the best place to document which platforms does WinHTTP support. But probably it wouldn't be a big surprise for vcpkg users who use `uwp` triplet - in their mind, uwp is `WINAPI_FAMILY_PC_APP`.

File: sdk/core/azure-core/src/http/transport_policy.cpp (hunk 22 above)
Comment (antkmsft) [reply sdk/core/azure-core/src/http/transport_policy.cpp:28]: We have to build in "no transport" configuration, at least for VcPkg. When you tell it to build "azure-core-cpp[core]", it should build an implementation without any transport. Unless we want to make curl a permanent dependency for all configurations, which we don't want to do. But if we do, we ned to remove `curl` vcpkg option, if we always rely on Curl.

File: sdk/core/azure-core/inc/azure/core/datetime.hpp (hunk 14 above)
Comment (antkmsft) [reply sdk/core/azure-core/inc/azure/core/datetime.hpp]: We can avoid, but I see no reason.
With inline functions it is a bit faster. Maybe it is not a bottleneck, but anyways, we can avoid it in this place, but htere are dozens more, especially in the Extensible Enums area, where there is no escape, and this problem must be solved.

File: sdk/core/azure-core/CMakeLists.txt (hunk 15 above)
Comment (antkmsft) [reply sdk/core/azure-core/CMakeLists.txt]: Answering your question, we don't expect the customer to ever include this header.
But for the uber-headers per module, the convention is that core.hpp includes ALL headers regardless of how useful they are (this header will get included regardless, because some other headers DO include it)
BTW, regarding file rename, I did as you suggested.

File: sdk/core/azure-core/inc/azure/core/http/policy.hpp (hunk 17 above)
Comment (antkmsft) [reply sdk/core/azure-core/inc/azure/core/http/policy.hpp:21]: Per our offline discussion, including Victor as well, this is the right move.

File: sdk/core/azure-core/inc/azure/core/operation_status.hpp (hunk 18 above)
Comment (antkmsft) [reply sdk/core/azure-core/inc/azure/core/operation_status.hpp]: Yes, definitions below use it, as we discussed offline

**Comment by Jinming-Hu** [comment]
Hi @antkmsft , thank you for your efforts on resolving this UWP issue. Since you've made some changes to storage code in this PR, we'd appreciate if you can wait for storage team's approval next time.

**Comment by antkmsft** [comment]
I'm so sorry @Jinming-Hu, the PR was open for more than a week, and you commented here, so I was under the impression that you've reviewed the changes, and there were no blockers for you, so I went ahead. I would not want to check it in initially until I heard from you, but later when you commented, and there was no new feedback, I assumed you are ok with it.
