### PR TITLE
fix move to next page in paged response

### LINKED ISSUE #5617: `QueryEntitiesPagedResponse::MoveToNextPage()` in Data Table SDK doesn't work
`QueryEntitiesPagedResponse::MoveToNextPage()` method in Azure Data Tables C++ SDK doesn't move to next page. The reason is probably a bug in `QueryEntitiesPagedResponse::OnNextPage()` method - `NextPartitionKey` is set to `PartitionKey`. In `QueryEntities()`. `PartitionKey` is set to `PartitionKey` in URL, but `NextPartitionKey` from response should be set to `NextPartitionKey` in the URL, as per documentation: https://learn.microsoft.com/en-us/rest/api/storageservices/query-timeout-and-pagination.

**To Reproduce**
- run below code snippet

***Code Snippet***
```
#include <iostream>
#include <azure/data/tables.hpp>
#include <azure/identity/default_azure_credential.hpp>

int main() {
  const std::string tableName = "<your table name>";
  const std:: string storageUrl = "<your storage account URL>";

  auto cred = std::make_shared<Azure::Identity::DefaultAzureCredential>();
  auto tableClient = Azure::Data::Tables::TableClient(
      storageUrl , tableName, cred);

  for (int i = 0; i < 1010; i++)
  {
    auto entity = Azure::Data::Tables::Models::TableEntity();
    entity.SetPartitionKey("partition");
    entity.SetRowKey("rowKey" + std::to_string(i));
    tableClient.AddEntity(entity);
  }

  Azure::Data::Tables::Models::QueryEntitiesOptions options;
  auto response = tableClient.QueryEntities(options);
  std::cout << "number of entities: " << response.TableEntities.size(); // 1000, OK
  std::cout << "first entity row key: " << response.TableEntities[0].GetRowKey().Value; // rowKey0, OK
  std::cout << "last entity row key: " << response.TableEntities.back().GetRowKey().Value; // rowKey99, OK
  
  response.MoveToNextPage();
  std::cout << "number of entities: " << response.TableEntities.size(); // Wrong, got 1000, expected 10
  std::cout << "first entity row key: " << response.TableEntities[0].GetRowKey().Value; // Wrong, got 0, expected rowKey990
  std::cout << "last entity row key: " << response.TableEntities.back().GetRowKey().Value; // Wrong, got 99, expected rowKey999
}
```

**Expected behavior**
`MoveToNextPage()` should move pages, as shown in the code snippet.

**Setup**
 - OS: WSL, Ubuntu 22.04
 - IDE : VS Code
 - Version of the Library used: azure-data-tables-cpp, 1.0.0-beta.2 (pulled from VCPKG)

### PR DESCRIPTION
**Pull request by gearama**
closes #5617 
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

File: sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp [hunk 1]
```diff
@@ -743,6 +743,16 @@ namespace Azure { namespace Data { namespace Tables {
...
+      /**
+       * @brief The next Partition key.
+       *
+       */
+      std::string NextPartitionKey;
+      /**
+       * @brief The next row key.
+       *
+       */
+      std::string NextRowKey;
```
Comment (ahsonkhan) [inline sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp:755]: Should we try to code generation against the rest-api-spec and compare to what we have today, to see if there's other changes we can catch?

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/data-plane/Microsoft.Tables/preview/2019-02-02/table.json

Comment (gearama) [reply sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp:755]: we could i guess, once we're done with the security scramble

Comment (LarryOsterman) [reply sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp:755]: These match the swagger. Other fields in the swagger are:

* Timeout
* ApiVersion
* ClientRequestId
* DataServiceVersion
* Format
* Top
* Select - Present as SelectColuns
* Filter - Present as Filter
* TableName

Fields that are *not* in the swagger:

* PartitionKey
* RowKey

Note that this is a completely naive scan of the swagger definition. These fields may or may not be relevant.

File: sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp [hunk 2]
```diff
@@ -117,6 +117,16 @@ namespace Azure { namespace Data { namespace Tables {
        */
       std::vector<Models::Table> Tables;
 
+      /**
+       * @brief Construct a new Query Tables Paged Response object.
+       *
+       * @param tableServiceClient Table service client.
+       */
+      QueryTablesPagedResponse(std::shared_ptr<TableServiceClient> tableServiceClient)
```
Comment (antkmsft) [inline sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp:125]: Can this be private? If it is only the `Azure::Data::Tables::TableServiceClient` and `Azure::Core::PagedResponse<QueryTablesPagedResponse>` who can/should/expected to create this, we should, I think.

File: sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp [hunk 3]
```diff
@@ -775,6 +795,14 @@ namespace Azure { namespace Data { namespace Tables {
        */
       std::vector<Models::TableEntity> TableEntities;
 
+      /**
+       * @brief Construct a new Query Entities Paged Response object.
+       *
+       * @param tableClient Table client.
+       */
+      QueryEntitiesPagedResponse(std::shared_ptr<TableClient> tableClient)
```
Comment (antkmsft) [inline sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp:803]: Same comment, if we should make this private, if users are not supposed to create instances of these.

**Comment by antkmsft** [comment]
FWIW, here is what code our current codegen would generate for pageable:
* hpp: https://github.com/Azure/autorest.cpp/blob/next/packages/typespec-cpp/test/cadl-ranch/http/payload/pageable/generated/inc/payload/pageable/rest_client.hpp
* cpp: https://github.com/Azure/autorest.cpp/blob/next/packages/typespec-cpp/test/cadl-ranch/http/payload/pageable/generated/src/rest_client.cpp

I didn't find a private constructor there, but the codegen is essentially doing the same by doing this:
```cpp
  ListPagedResponse response{};
  response.m_client = std::make_shared<PageableClient>(*this);
  response.m_options = options;
```

I am not proposing that you necessarily should remove the constructor, but I am more making an argument for the construction being private.

File: sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp (hunk 2 above)
Comment (gearama) [reply sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp]: done

File: sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp [hunk 4]
```diff
@@ -796,15 +786,12 @@ namespace Azure { namespace Data { namespace Tables {
...
 
       /**
-       * @brief Construct a new Query Entities Paged Response object.
+       * @brief Table Client.
        *
-       * @param tableClient Table client.
        */
-      QueryEntitiesPagedResponse(std::shared_ptr<TableClient> tableClient)
-          : m_tableClient(tableClient){};
+      std::shared_ptr<TableClient> m_tableClient;
```
Comment (antkmsft) [inline sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp:792]: hmm, pubic?
Could you rather make `QueryTablesPagedResponse` a `friend` of `QueryEntitiesPagedResponse`, and modify this field then?

And I'm sorry, I think `private` constructor taking shared_ptr was a better idea, because when you declare a constructor, it removes all the public default auto-generated constructor, which is good for the customer, because they are not supposed to create instances of `QueryEntitiesPagedResponse`, other than get them as a copy via move constructor from calling `TableServiceClient::QueryTables()`.

BTW, for the constructor, one suggestion, to add std::move:
```cpp
#include <utility>

QueryEntitiesPagedResponse(std::shared_ptr<TableClient> tableClient)
  : m_tableClient(std::move(tableClient)){};
```

**Review by antkmsft — APPROVED** [review]
I don't know if there is someone knowledgeable who is supposed to ok this PR, and I do not know if you resolved the other feedback from other team members in this PR, and if they are happy, but the part that I more or less understand and commented on, looks good now :)
