### PR TITLE
Keyvault macros deprecate and new names 

### LINKED ISSUE #5588: Symbol name collision with pkcs11.h identifier CKM_RSA_AES_KEY_WRAP
**Describe the bug**
Building an application that includes both `sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp` and OASIS `pkcs11.h` fails due to both defining a symbol named `CKM_RSA_AES_KEY_WRAP`. Namespacing is irrelevant here, as `pkcs11.h` defines a macro.

***Exception or Stack Trace***
gcc compiler error:
```
In file included from /workspaces/azure_kms_pkcs11/pkcs11_compat.h:12,
                 from /workspaces/azure_kms_pkcs11/attributes.h:1,
                 from /workspaces/azure_kms_pkcs11/aws_kms_pkcs11.cpp:11:
/usr/include/p11-kit-1/p11-kit/pkcs11.h:802:42: error: expected unqualified-id before numeric constant
  802 | #define CKM_RSA_AES_KEY_WRAP            (0x1054UL)
      |                                          ^~~~~~~~
/usr/include/p11-kit-1/p11-kit/pkcs11.h:802:42: error: expected ')' before numeric constant
  802 | #define CKM_RSA_AES_KEY_WRAP            (0x1054UL)
      |                                         ~^~~~~~~~
```

**To Reproduce**
```
apt-get install gcc g++ p11-kit libp11-kit-dev
g++ -c snippet.cpp -I/usr/include/p11-kit-1/p11-kit -I<path to azure-sdk-for-cpp>
```

***Code Snippet***
Add the code snippet that causes the issue.

```
#include <pkcs11.h>
#include <azure/keyvault/keys/key_client_models.hpp>
```

**Expected behavior**
pkcs11 and Azure sdk can be used in the same compilation unit.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04
 - IDE : no
 - Version of the Library used: main bd08d226e1726825ee43cff219b3cba45126910d

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by gearama**
closes #5588 
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

File: sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp [hunk 1]
```diff
@@ -316,20 +316,53 @@ namespace Azure { namespace Security { namespace KeyVault { namespace Keys {
     /**
      * @brief Gets the CKM_RSA_AES_KEY_WRAP algorithm.
      *
+     * @deprecated Use KeyEncryptionAlgorithm::CkmRsaAesKeyWrap.
      */
-    AZ_SECURITY_KEYVAULT_KEYS_DLLEXPORT static const KeyEncryptionAlgorithm CKM_RSA_AES_KEY_WRAP;
+    [[deprecated("Use "
```
Comment (LarryOsterman) [inline sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp:321]: Is this sufficient to resolve the customer problem? 

Don't we have to provide a mechanism to disable the existing functions? Or to not include these definitions if they are already defined in the preprocessor?

**Comment by LarryOsterman** [comment]
It might be nice to include a reproduction of the customer scenario so we can confirm that it's fixed by this change (or that the customers scenario *can* be fixed after this change).

File: sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp (hunk 1 above)
Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp:321]: like this ?

**Comment by gearama** [comment]
added repro

File: sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp (hunk 1 above)
Comment (LarryOsterman) [reply sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp:321]: Yes, like this :).

**Review by LarryOsterman — APPROVED** [review]

File: sdk/keyvault/azure-security-keyvault-keys/test/macros-build/macros_build.hpp [hunk 2]
```diff
@@ -0,0 +1,6 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT License.
+
+#define CKM_RSA_AES_KEY_WRAP 1
+#define RSA_AES_KEY_WRAP_256 2
+#define RSA_AES_KEY_WRAP_384 3
```
Comment (LarryOsterman) [inline sdk/keyvault/azure-security-keyvault-keys/test/macros-build/macros_build.hpp:6]: Missing CRLF.

File: sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp [hunk 3]
```diff
@@ -1,17 +1,16 @@
 // Copyright (c) Microsoft Corporation.
 // Licensed under the MIT License.
-
 #include "azure/keyvault/keys/key_client_models.hpp"
 #include "private/key_constants.hpp"
 
 namespace Azure { namespace Security { namespace KeyVault { namespace Keys {
 
-  const KeyEncryptionAlgorithm KeyEncryptionAlgorithm::CKM_RSA_AES_KEY_WRAP(
+  const KeyEncryptionAlgorithm KeyEncryptionAlgorithm::CkmRsaAesKeyWrap(
```
Comment (antkmsft) [inline sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp:8]: Instead of renaming, let's also allocate the deprecated ones here?

This way, if customer still uses the now deprecated `KeyEncryptionAlgorithm::CKM_RSA_AES_KEY_WRAP`, they only get a warning from compiler, but not a linker error.

And if we want to be extra bulletproof, we could put (**only in this file**) `#undef CKM_RSA_AES_KEY_WRAP` and the same for the other two, before the first `#include`, so that even if CKM_RSA_AES_KEY_WRAP is defined when this very .cpp file is building, we forcefully undef it (and it should be safe to do so, because that undeffing will only affect building this .cpp file. But maybe undeffing is an overkill.

But I do recommend to still allocate `KeyEncryptionAlgorithm::CKM_RSA_AES_KEY_WRAP` so that if the customer does not have CKM_RSA_AES_KEY_WRAP, and uses a deprecated value, their code builds and links (even with the deprecation warning).

**Review by antkmsft — APPROVED** [review]
Oh, I was going to recommend so many great ideas, if only they work! Apparently this is the best that we can hope for.
Sorry for the `()` mis-suggestion earlier - I forgot it only works for function-style macros. Unfortunate!

File: sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp [hunk 4]
```diff
@@ -1,17 +1,16 @@
 // Copyright (c) Microsoft Corporation.
 // Licensed under the MIT License.
-
```
Comment (ahsonkhan) [inline sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp:3]: nit: keep this new line between license text and include headers

File: sdk/keyvault/azure-security-keyvault-keys/test/macros-build/CMakeLists.txt [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+set(CMAKE_CXX_STANDARD_REQUIRED True)
+
+add_executable (
+  macros-build
+  macros_build.cpp
+  macros_build.hpp)
+
+create_per_service_target_build_for_sample(keyvault macros-build)
+
+target_link_libraries(macros-build PRIVATE azure-security-keyvault-keys)
```
Comment (ahsonkhan) [inline sdk/keyvault/azure-security-keyvault-keys/test/macros-build/CMakeLists.txt:17]: Is this included anywhere to be built/run in CI, as a test? Should we have this as a gtest test, with an EXPECT for the value?

File: sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt [hunk 6]
```diff
@@ -138,6 +138,8 @@ create_code_coverage(keyvault azure-security-keyvault-keys azure-security-keyvau
 get_az_version("${CMAKE_CURRENT_SOURCE_DIR}/src/private/package_version.hpp")
 generate_documentation(azure-security-keyvault-keys ${AZ_LIBRARY_VERSION})
 
+add_subdirectory(test/macros-build)
+
```
Comment (ahsonkhan) [inline sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt:142]: I imagine this should only be built if `BUILD_TESTING` is true. Move inside the if?

File: sdk/keyvault/azure-security-keyvault-keys/test/macros-build/macros_build.cpp [hunk 7]
```diff
@@ -0,0 +1,33 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT License.
+
+/**
+ * @brief Tests the ability to build when certain macros are defined outside the keyvault
+ * code
```
Comment (ahsonkhan) [inline sdk/keyvault/azure-security-keyvault-keys/test/macros-build/macros_build.cpp:6]: nit:
```suggestion
 * code.
```

File: sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp [hunk 8]
```diff
@@ -312,24 +312,59 @@ namespace Azure { namespace Security { namespace KeyVault { namespace Keys {
...
     explicit KeyEncryptionAlgorithm(std::string value) : ExtendableEnumeration(std::move(value)) {}
-
+#ifndef CKM_RSA_AES_KEY_WRAP
     /**
      * @brief Gets the CKM_RSA_AES_KEY_WRAP algorithm.
      *
+     * @deprecated Use KeyEncryptionAlgorithm::CkmRsaAesKeyWrap.
      */
-    AZ_SECURITY_KEYVAULT_KEYS_DLLEXPORT static const KeyEncryptionAlgorithm CKM_RSA_AES_KEY_WRAP;
+    [[deprecated("Use "
```
Comment (ahsonkhan) [inline sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp:321]: I'd recommend adding a changelog entry to inform customers of this extensible enum rename.

**Review by ahsonkhan — DISMISSED** [review]
Move tests to the appropriate CMakeLists.txt location, add a CL entry, and consider updating the test project be a runnable gtest (or clarify intent).

Otherwise, looks good.

File: sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp (hunk 3 above)
Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp:9]: when trying to initialize here i got build breaks due to the deprecated flag. 
i tried disabling the warning but that works only on msvc, 
i tried initializing it in class but that doesn't work for static const members . so the only choice i had was to remove the inits from here

Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp:34]: done

File: sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md [hunk 9]
```diff
@@ -6,6 +6,12 @@
 
 ### Breaking Changes
 
+- Deprecated KeyEncryptionAlgorithm::CKM_RSA_AES_KEY_WRAP in favor of KeyEncryptionAlgorithm::CkmRsaAesKeyWrap;
+
+- Deprecated KeyEncryptionAlgorithm::RSA_AES_KEY_WRAP_256 in favor of KeyEncryptionAlgorithm::RsaAesKeyWrap256;
+
+- Deprecated KeyEncryptionAlgorithm::RSA_AES_KEY_WRAP_384 in favor of KeyEncryptionAlgorithm::RsaAesKeyWrap384;
```
Comment (ahsonkhan) [inline sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md:13]: We typically don't have new lines between the list of changes (I am not sure if it would break any of the parsing scripts on release).

Also, suggesting to add back-ticks along with period instead of semi-colons.

```suggestion
- Deprecated `KeyEncryptionAlgorithm::CKM_RSA_AES_KEY_WRAP` in favor of `KeyEncryptionAlgorithm::CkmRsaAesKeyWrap`.
- Deprecated `KeyEncryptionAlgorithm::RSA_AES_KEY_WRAP_256` in favor of `KeyEncryptionAlgorithm::RsaAesKeyWrap256`.
- Deprecated `KeyEncryptionAlgorithm::RSA_AES_KEY_WRAP_384` in favor of `KeyEncryptionAlgorithm::RsaAesKeyWrap384`.
```

File: sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp [hunk 10]
```diff
@@ -5,7 +5,17 @@
 #include "private/key_constants.hpp"
 
 namespace Azure { namespace Security { namespace KeyVault { namespace Keys {
-
+// Disable deprecation warning
```
Comment (ahsonkhan) [inline sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp:8]: I like this comment :)

File: sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt (hunk 6 above)
Comment (ahsonkhan) [reply sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt:142]: This test directory is still being add outside of when `BUILD_TESTING` is true.

Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt:142]: yes, it's a build test, i argue it needs to always be tested , especially since we have magic flags in the build to check to make deprecated warnings as errors

File: sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp (hunk 10 above)
Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/src/key_encryption_algorithm.cpp:8]: me too, i goth the code block from larry

File: sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md (hunk 9 above)
Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md]: thank you for the code snippet, merged it, looks better than my version :)

File: sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt (hunk 6 above)
Comment (ahsonkhan) [reply sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt:142]: > yes, it's a build test, i argue it needs to always be tested

Agreed. We should be building/testing this to confirm the fix. All our tests run with `BUILD_TESTING` turned on/in CI.

For maintainability, I recommend adding anything related to the `test` directory only when `BUILD_TESTING` is true. Otherwise, if we don't keep that invariant true, we could see unintended CI failures.

Also, **more importantly**, I don't think we should be shipping this macros-build app along with the test directory to our end customers, as part of the product.

Can you confirm if we package this up and ship the SDK to customers, when they install the package, they don't get this test app on disk? If they do, we **definitely** need to move this to the `BUILD_TESTING` if check a few lines below in the CMakeLists.txt. We don't want to ship this to customers, right?

Any reason, that I might not be aware, that would prevent us from moving this `add_subdirectory` in that if-block? To be clear, in here:
https://github.com/Azure/azure-sdk-for-cpp/blob/7d7946110219f9b6d2971cddb444973988ca8d15/sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt#L143-L152

**Review by ahsonkhan — CHANGES_REQUESTED** [review]
I still think we shouldn't be shipping the macro-build test app as part of the SDK. Unless I am missing something (which is quite possible), please move it to `BUILD_TESTING`. Let me know :)

That is the only blocker.

File: sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt (hunk 6 above)
Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt]: i moved it

**Review by ahsonkhan — APPROVED** [review]
LGTM. Thanks!

**Comment by LarryOsterman** [comment]
> I still think we shouldn't be shipping the `macro-build` test app as part of the SDK, to end customers. Unless I am missing something (which is quite possible), please move it to `BUILD_TESTING`. Let me know :)
> 
> That is the only blocker.

I agree with Ahson on this one - if it's conditionally under the BUILD_TESTING macro, then it won't be built on customer machines when they download the SDK. If it's not under BUILD_TESTING, it will be built on every customers machine, which seems unnecessary.

**Comment by gearama** [comment]
> > I still think we shouldn't be shipping the `macro-build` test app as part of the SDK, to end customers. Unless I am missing something (which is quite possible), please move it to `BUILD_TESTING`. Let me know :)
> > That is the only blocker.
> 
> I agree with Ahson on this one - if it's conditionally under the BUILD_TESTING macro, then it won't be built on customer machines when they download the SDK. If it's not under BUILD_TESTING, it will be built on every customers machine, which seems unnecessary.

Done.

**Comment by gearama** [comment]
/azo run cpp - core - ci
