### PR TITLE
AuthenticationException: derives from std::exception

### LINKED ISSUE #1178: AuthenticationExeption should inherit std::exception straight
This issue is a change request from the API review: https://apiview.dev/Assemblies/Review/6f5301c273ee4eda8d35487a898439a6

### PR DESCRIPTION
**Pull request by antkmsft**
Closes #1178

### CODE REVIEW

**Review by RickWinter — APPROVED** [review]

File: sdk/core/azure-core/inc/azure/core/credentials.hpp [hunk 1]
```diff
@@ -64,13 +64,13 @@ namespace Azure { namespace Core {
   /**
    * @brief An exception that gets thrown when authentication error occurs.
    */
-  class AuthenticationException : public std::runtime_error {
+  class AuthenticationException : public std::exception {
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/credentials.hpp:67]: Do we have tests that verify we are throwing AuthException from the right base type? We should add one since we want to prevent a future code change that changes this back to fail CI.

**Review by ahsonkhan — APPROVED** [review]
Add a test please that verifies AuthenticationException derives from std::exception. Looks good otherwise.

File: sdk/core/azure-core/inc/azure/core/credentials.hpp [hunk 2]
```diff
@@ -64,13 +64,13 @@ namespace Azure { namespace Core {
...
   public:
     /**
      * @brief Construct with message string.
      *
      * @param msg Message string.
      */
-    explicit AuthenticationException(std::string const& msg) : std::runtime_error(msg) {}
+    explicit AuthenticationException(std::string const& msg) : std::exception(msg.c_str()) {}
```
Comment (vhvb1989) [inline sdk/core/azure-core/inc/azure/core/credentials.hpp:74]: std::exception doesn't have a constructor that takes char* or string

If you want to derive rirectly from std::exception you need to implement the default method what() and save the msg inside the AuthenticationException.

So, maybe create an AzureCoreException that derives from std::exception where we store the msg and implement what().
Then we use that one instead of std::exception. 
Otherwise, if our exceptions will derive from std::exception, we will need to define/implement the same in most of them

**Review by vhvb1989 — COMMENTED** [review]
No idea why this works on MSCV.
There is no string or char* constructor for std::exception

File: sdk/core/azure-core/inc/azure/core/credentials.hpp (hunk 1 above)
Comment (antkmsft) [reply sdk/core/azure-core/inc/azure/core/credentials.hpp:67]: This will be covered once #271 gets in.

File: sdk/core/azure-core/inc/azure/core/credentials.hpp (hunk 2 above)
Comment (antkmsft) [reply sdk/core/azure-core/inc/azure/core/credentials.hpp]: Thank you Victor, you are right, that constructor is not defined in standard. For now, I'll get away with overriding `what()` - I don't think we reached agreement on bas class for AzureSDK exceptions, but I am personally support the idea.
