### PR TITLE
Identity: Credentials to accept a wider variety of token responses

### LINKED ISSUE #4723: ImdsManagedIdentitySource (Managed Identity authentication) exception when parsing the identity endpoint response
**Describe the bug**
Hello,

I'm hitting an issue with the Managed Identity authentication (ManagedIdentityCredential class). I'm getting the following exception when trying to obtain an access token:
GetToken(): [json.exception.type_error.302] type must be number, but is string

The exception comes from the TokenCredentialImpl::ParseToken method in token_credential_impl.cpp when trying to obtain the expiresInPropertyName value from parsed json. It looks like the code expects json to contain a number, but the identity endpoint to which the request is sent returns a string instead.

***Exception or Stack Trace***
OLEDB sandbox.exe!`Azure::Identity::_detail::TokenCredentialImpl::GetToken'::`1'::catch$20() Line 136	C++
[External Code]	
OLEDB sandbox.exe!Azure::Identity::_detail::TokenCredentialImpl::GetToken(const Azure::Core::Context & context, const std::function<std::unique_ptr<Azure::Identity::_detail::TokenCredentialImpl::TokenRequest,std::default_delete<Azure::Identity::_detail::TokenCredentialImpl::TokenRequest>> __cdecl(void)> & createRequest, const std::function<std::unique_ptr<Azure::Identity::_detail::TokenCredentialImpl::TokenRequest,std::default_delete<Azure::Identity::_detail::TokenCredentialImpl::TokenRequest>> __cdecl(enum Azure::Core::Http::HttpStatusCode,Azure::Core::Http::RawResponse const &)> & shouldRetry) Line 125	C++
OLEDB sandbox.exe!Azure::Identity::_detail::ImdsManagedIdentitySource::GetToken::__l2::<lambda_1>::operator()() Line 360	C++
[External Code]	
OLEDB sandbox.exe!Azure::Identity::_detail::TokenCache::GetToken(const std::string & scopeString, std::chrono::duration<__int64,std::ratio<1,10000000>> minimumExpiration, const std::function<Azure::Core::Credentials::AccessToken __cdecl(void)> & getNewToken) Line 116	C++
OLEDB sandbox.exe!Azure::Identity::_detail::ImdsManagedIdentitySource::GetToken(const Azure::Core::Credentials::TokenRequestContext & tokenRequestContext, const Azure::Core::Context & context) Line 359	C++
OLEDB sandbox.exe!Azure::Identity::ManagedIdentityCredential::GetToken(const Azure::Core::Credentials::TokenRequestContext & tokenRequestContext, const Azure::Core::Context & context) Line 60	C++
OLEDB sandbox.exe!main() Line 46	C++

**To Reproduce**
The client application is very simple:
`Azure::Core::Context context;
Azure::Core::Credentials::TokenRequestContext tokenRequestContext;
Azure::Core::Credentials::AccessToken accessToken;
tokenRequestContext.Scopes.push_back("https://database.windows.net");
Azure::Identity::ManagedIdentityCredential managedIdentityCredential;
try
{
    accessToken = managedIdentityCredential.GetToken(tokenRequestContext, context);
}
catch (const std::exception& e)
{
    std::cout << "Exception caught: " << e.what() << std::endl;
}
`
Please note that variables such as MSI_ENDPOINT, MSI_SECRET, IDENTITY_ENDPOINT, IDENTITY_HEADER are not defined in my environment, so the CreateManagedIdentitySource function (managed_identity_credential.cpp) uses the ImdsManagedIdentitySource implementation which targets the "http://169.254.169.254/metadata/identity/oauth2/token" endpoint.

**Expected behavior**
The library should be able to correctly parse the json response from the identity endpoint.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio
 - 1.4.0

**Additional context**
The example response from the endpoint is as follows:
`{
    "access_token": "...",
    "client_id": "...",
    "expires_in": "84671",
    "expires_on": "1687364401",
    "ext_expires_in": "86399",
    "not_before": "1687277701",
    "resource": "https://database.windows.net",
    "token_type": "Bearer"
}`

Please note that the "expires_in" property has a string value.
Here's another response when using the ClientSecretCredential class (different endpoint):
`{
    "token_type": "Bearer",
    "expires_in": 86399,
    "ext_expires_in": 86399,
    "access_token": "..."
}`

In this case, the "expires_in" value is a number (which is what the TokenCredentialImpl::ParseToken method expects).

**Information Checklist**
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by antkmsft**
Closes #4723.

### CODE REVIEW

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 1]
```diff
@@ -163,27 +165,76 @@ AccessToken TokenCredentialImpl::ParseToken(
...
+        accessToken.ExpiresOn += std::chrono::seconds(
+            parsedJson[expiresInPropertyName].get<std::chrono::seconds::duration::rep>());
+
+        return accessToken;
+      }
+      catch (std::exception const&)
+      {
+        try
+        {
+          // 'expires_in' as numeric string (seconds until expiration)
```
Comment (LarryOsterman) [inline sdk/identity/azure-identity/src/token_credential_impl.cpp:184]: expires_on as numeric string?

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 2]
```diff
@@ -163,27 +165,76 @@ AccessToken TokenCredentialImpl::ParseToken(
...
+          parsedJson[expiresOnPropertyName].get<std::string>(), DateTime::DateFormat::Rfc3339);
+    }
+    catch (std::exception const&)
     {
-      accessToken.ExpiresOn = Azure::DateTime::Parse(
-          parsedJson[expiresOnPropertyName].get<std::string>(),
-          Azure::DateTime::DateFormat::Rfc3339);
+      try
+      {
+        // 'expires_on' as number (posix time representing an absolute timestamp)
```
Comment (LarryOsterman) [inline sdk/identity/azure-identity/src/token_credential_impl.cpp:219]: Similar comment to the above.  It seems weird to see these nested try/catch statements, can't you check the values (and the type of the value) instead of depending on the JSON parser to throw?

**Review by LarryOsterman — CHANGES_REQUESTED** [review]

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 1 above)
Comment (LarryOsterman) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:184]: In other words, I think the comment here is incorrect.

Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:184]: The comment is correct. We read `parsedJson[expiresInPropertyName]`.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 3]
```diff
@@ -163,27 +165,76 @@ AccessToken TokenCredentialImpl::ParseToken(
...
     if (parsedJson.contains(expiresInPropertyName))
     {
-      accessToken.ExpiresOn
-          = std::chrono::system_clock::now()
-          + std::chrono::seconds(
-                parsedJson[expiresInPropertyName].get<std::chrono::seconds::duration::rep>());
+      try
+      {
+        // 'expires_in' as number (seconds until expiration)
+        accessToken.ExpiresOn += std::chrono::seconds(
```
[the remark this answers is not in the document]
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:175]: We do check if it exists - `if (parsedJson.contains(expiresInPropertyName))` a few lines above.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 4]
```diff
@@ -152,44 +154,96 @@ AccessToken TokenCredentialImpl::ParseToken(
...
     }
-    else if (expiresOnPropertyName.empty())
+
+    if (expiresIn.is_string())
     {
-      ThrowMissingJsonPropertyError(expiresInPropertyName);
+      try
+      {
+        // 'expires_in' as numeric string (seconds until expiration)
+        accessToken.ExpiresOn += std::chrono::seconds(std::stoi(expiresIn.get<std::string>()));
```
Comment (LarryOsterman) [inline sdk/identity/azure-identity/src/token_credential_impl.cpp:187]: Is `std::stoi` the right function to call here? Or would `std::stol` be a better choice?

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 5]
```diff
@@ -152,44 +154,96 @@ AccessToken TokenCredentialImpl::ParseToken(
...
+
+        return accessToken;
+      }
+      catch (std::exception const&)
```
Comment (LarryOsterman) [inline sdk/identity/azure-identity/src/token_credential_impl.cpp:191]: Under what circumstances would `stol` throwing be allowed? If there's a string value of expiresIn which *isn't* a number, shouldn't we be rejecting the token?

**Review by LarryOsterman — APPROVED** [review]

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 6]
```diff
@@ -152,44 +154,96 @@ AccessToken TokenCredentialImpl::ParseToken(
     std::string const& expiresInPropertyName,
     std::string const& expiresOnPropertyName)
 {
-  try
+  auto const parsedJson = Azure::Core::Json::_internal::json::parse(jsonString);
```
[the remark this answers is not in the document]
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:157]: Everything from the credentials ultimately gets wrapped into `AuthenticationException` so it would be clear for the user call to `client.DoOperation()` whether the error is with authentication or with the response itself.
We could take the message, but I don't think they are more informative - at least we indicate where the problem is and with what property.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 4 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:187]: Expiration is in seconds, and `2147483647` seconds is 68+ years, so I think it is ok to throw if the number can't be parsed as int32.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 7]
```diff
@@ -152,44 +154,96 @@ AccessToken TokenCredentialImpl::ParseToken(
...
+      }
+      catch (std::exception const&)
+      {
+        // stoi() has thrown, we may throw later.
+      }
     }
-    else if (!parsedJson.contains(expiresOnPropertyName))
+  }
+
+  if (expiresOnPropertyName.empty())
```
[the remark this answers is not in the document]
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:198]: It used to be the case that part of the credentials would only attempt to read `expires_in`. I now defaulted them to read the both by default, although you still can construct a credential that would read only the `expires_in`. Later, if we confirm that `expires_on` is specified for every response kind, we may refactor to simplify this code and to always expect some kind of `expires_on` property (for some responses, they are `expiresIn` and `expiresOn` (Azure CLI), for others - `expires_in` and `expires_on` (rest of the credentials)).

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 5 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:191]: There still can be a readable value in `expires_on`, so we don't throw just yet. The scenario being - some server starts returning floats in `expires_in`.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (ahsonkhan) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:157]: > Is it ok for the `nlohmann::json` exception that would be thrown by the call to `json::parse` to be bubbled up to the customer?

I would say no since this is an implementation detail, though I suspect we may be leaking some exceptions in edge cases, which we'd want to wrap. We shouldn't rely on the error messages on a library which we consider implementation and are free to change under the covers.

This is relevant in codegen as well. For example: 
https://github.com/Azure/autorest.cpp/pull/246#issuecomment-1605125152
