### PR TITLE
Fix CPU spinning when curl_easy_send returns 0 bytes on SSL socket writes

### LINKED ISSUE #6817: High latencies observed at the SDK entry point during Cloud operations
ask: We are currently investigating high latencies observed at the SDK entry point during Cloud operations. Our measurements indicate that these latencies occur when performing Put() operations via the Azure SDK. There have been suggestions that the elevated latencies may be related to CPU utilization within the I/O stack, which appears to be actively engaged in Cloud Put() activities.
 
This observation seems counterintuitive because our understanding is that Put() calls should primarily wait for server-side acknowledgment of successful completion and therefore should not consume significant CPU resources on the client side. However, profiling consistently shows that I/O threads are on CPU, executing within the SDK, specifically in Put() calls, with the top of the stack being:
 
Azure::Core::Http::CurlConnection::SendBuffer()
 
Integration Details
 
SDK Version: azure-identity-1.5.1
SDK is using the C++ interfaces, as described in [https://learn.microsoft.com/en-us/azure/storage/blobs/quickstart-blobs-c-plus-plus?tabs=managed-ide…](https://learn.microsoft.com/en-us/azure/storage/blobs/quickstart-blobs-c-plus-plus?tabs=managed-ide%E2%80%A6)
 
- The main entry point from Rubrik code into the SDK for putting a BlockBlok into a container, that we see as occupying the CPU is: 
 
          - Azure::Response<Models::UploadBlockBlobResult> Upload(Azure::Core::IO::BodyStream& content, const UploadBlockBlobOptions& options = UploadBlockBlobOptions(), const Azure::Core::Context& context = Azure::Core::Context()) const
 
- Have attached a detailed thread stack of what it looks like from Upload(), all the way to Azure::Core::Http::CurlConnection::SendBuffer(), in case that is helpful, please see attached file, 

[thread_stack_bt_upload_sendbuffer.txt](https://github.com/user-attachments/files/23364412/thread_stack_bt_upload_sendbuffer.txt)

 
- For completeness, the corresponding Get() interface we use is:
          - Azure::Response<Models::DownloadBlobToResult> DownloadTo(uint8_t* buffer, size_t bufferSize, const DownloadBlobToOptions& options = DownloadBlobToOptions(), const Azure::Core::Context& context = Azure::Core::Context()) const
 
Key Observations
Threads executing SendBuffer() are consistently in the ‘R’ state (as seen in top -H output), indicating active CPU usage.
This behavior raises questions about why these threads are spinning on CPU rather than being idle while awaiting server acknowledgment.
Request to SDK Team:
 
We seek clarity on the following points:
Root Cause Analysis:
Why are threads in SendBuffer() consuming CPU cycles during Put() operations? Is this expected behavior or indicative of an underlying issue?
Latency Attribution:
How can we measure and differentiate latencies within the SDK layer versus lower-level factors (e.g., network delays) that may contribute to overall high latencies observed at the SDK entry point?
 
Goal is to disambiguate SDK-level delays from external factors to better understand and optimize performance.

### PR DESCRIPTION
**Pull request by harshitkr12**
**Summary:**

Why ?
When uploading blobs to Azure Storage over HTTPS (SSL/TLS), `curl_easy_send()` can return `CURLE_OK` with 0 bytes sent. This would lead to a retry without delay immediately, causing a tight CPU-spinning loop.

What ?
Added a 10ms sleep when `curl_easy_send()` returns `CURLE_OK` with 0 bytes sent to prevent rapid retries and allow the OS scheduler to run other threads.

**Test Plan:**
```
cmake --build .
ctest -R "azure-core" --output-on-failure
>> 100% tests passed, 0 tests failed out of 459
```

Fixes #6817

### CODE REVIEW

File: sdk/core/azure-core/src/http/curl/curl.cpp [hunk 1]
```diff
@@ -637,7 +640,15 @@ CURLcode CurlConnection::SendBuffer(
...
         case CURLE_OK: {
-          sentBytesTotal += sentBytesPerRequest;
+          if (sentBytesPerRequest == 0)
+          {
+            // When curl_easy_send returns CURLE_OK but sends 0 bytes (which can happen on SSL
+            // sockets), add a small delay to prevent rapid retries that keep the CPU busy
+            // without making progress. This allows the scheduler to run other threads.
+            std::this_thread::sleep_for(std::chrono::milliseconds(10));
+          } else {
+            sentBytesTotal += sentBytesPerRequest;
```
Comment (ashu-tripathi-rubrik) [inline sdk/core/azure-core/src/http/curl/curl.cpp]: Given that the else case is only avoiding the 0 case anyways, might be easier (for code readability purposes), to omit this else part alltogether.

Comment (harshitkr12) [reply sdk/core/azure-core/src/http/curl/curl.cpp]: Fixed

**Comment by antkmsft** [comment]
Thank you! I am approving the pull request, it looks good to me. I'd like @LarryOsterman to review before merging.

@LarryOsterman, if you will be doing the next release (it is probably January 8, unless @ronniegeraghty says it is a week after), please make sure that the changelog has an entry for this fix, as well as the acknowledgements section + credit after the fix line, similar to the other fixes that we've taken.
The upcoming release should probably be the beta.

I am going to follow up with Rubrik in the issue letting them know how they can start consuming it right away.

File: sdk/core/azure-core/src/http/curl/curl.cpp [hunk 2]
```diff
@@ -637,6 +640,13 @@ CURLcode CurlConnection::SendBuffer(
       switch (sendResult)
       {
         case CURLE_OK: {
+          if (sentBytesPerRequest == 0)
+          {
+            // When curl_easy_send returns CURLE_OK but sends 0 bytes (which can happen on SSL
+            // sockets), add a small delay to prevent rapid retries that keep the CPU busy
+            // without making progress. This allows the scheduler to run other threads.
+            std::this_thread::sleep_for(std::chrono::milliseconds(10));
```
Comment (RickWinter) [inline sdk/core/azure-core/src/http/curl/curl.cpp:648]: `std::this_thread::yield` will give up the time slice to other like or higher priority threads. Does curl actually need the thread to suspend (sleep) in case?

Comment (agabhin) [reply sdk/core/azure-core/src/http/curl/curl.cpp:648]: Documentation of `this_thread::yield`: https://en.cppreference.com/w/cpp/thread/yield.html

> Provides a **hint** to the implementation to reschedule the execution of threads, allowing other threads to run.

Note that it is only a hint.

Also, note Linux CFS scheduler behavior https://www.kernel.org/doc/html/latest/scheduler/sched-design-CFS.html

> CFS’s task picking logic is based on this p->se.vruntime value and it is thus very simple: it always tries to run the task with the smallest p->se.vruntime value (i.e., the task which executed least so far). CFS always tries to split up CPU time between runnable tasks as close to “ideal multitasking hardware” as possible.

This means - since Linux CFS (Completely Fair Scheduler) tries to be "fair," if your thread has yielded a lot recently, yield might effectively be a "no-op" (do nothing) if the scheduler decides you still haven't used your "fair share" of time compared to others, or if no other thread of the same priority is waiting.



- `this_thread::yield` will maybe yield the cpu but keep the thread in Running state and let OS sched decide what to do
-  `this_thread::sleep_for` will move it to Blocked state which is much better in this scenario and implicitly includes yielding the cpu.

**Conclusion**
- Using `this_thread::yield` in this context is risky and might not solve the cpu spin problem. Standard sleep is safer and better.

-- Abhinav
