### PR TITLE
Per-credential-instance token cache

### LINKED ISSUE #4129: Should not be able to get key vault secret using bad credentials.
**Describe the bug**
First, I use the correct credentials to obtain the secret from the key vault. 
Next, within the same program execution, I change the client secret to an incorrect value. 
Finally, when I attempt to obtain the secret from the key vault with the incorrect credentials, I am able to obtain the secret. This should fail with 401 - unauthorized error.
NOTE: when using SDK version 12.5.0, this bug is not present. 
When using latest git clone, the bug appears. 
The latest commit in this version is `13213977b3f7089e8595ff116b890688bee0dacf`
This new issue seems to be caused by pull request #4024 

***Exception or Stack Trace***
no exception

**To Reproduce**
Compile the enclosed sample program.
Set the environment variables to match your key vault secret name, path and credentials.
Run the program.

***Code Snippet***
This code snippet is a modified version of the sample provided with the SDK:
sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample1-basic-operations
(I added the ".txt" suffix to the file since github wouldn't let me upload a ".cpp" file, remove the ".txt" suffix before compiling.)

[sample1_basic_operations.cpp.txt](https://github.com/Azure/azure-sdk-for-cpp/files/10077825/sample1_basic_operations.cpp.txt)

**Expected behavior**
The attempt to access the key vault should fail with 401-unauthorized error when using incorrect client secret.

**Screenshots**
sdt56068_________ ./sample1-basic-operations
Using good client secret, Secret is returned with name extfsazureconnector and value ?sv=2019-12-12&ss=b&srt=sco&sp=rwdlacx&se=2023-02-13T08:43:10Z&st=2021-01-13T00:43:10Z&spr=https&sig=A6wQT7yGR%2BSrbUTIDiDupEhkDLbDx3wv54LCAYA%2BUbw%3D
Using bad client secret, Secret is returned with name extfsazureconnector and value ?sv=2019-12-12&ss=b&srt=sco&sp=rwdlacx&se=2023-02-13T08:43:10Z&st=2021-01-13T00:43:10Z&spr=https&sig=A6wQT7yGR%2BSrbUTIDiDupEhkDLbDx3wv54LCAYA%2BUbw%3D

**Setup (please complete the following information):**
 Suse Linux SLES15, service pack 4
 - IDE : [e.g. IntelliJ]
Command line build using vcpkg
GCC g++ (SUSE Linux) 7.5.0
No IDE used

sdt56068_________ make
[ 59%] Built target azure-core
[ 72%] Built target azure-security-keyvault-secrets
[ 77%] Built target get-env-helper
[ 95%] Built target azure-identity
Consolidate compiler generated dependencies of target sample1-basic-operations
[ 95%] Building CXX object sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample1-basic-operations/CMakeFiles/sample1-basic-operations.dir/sample1_basic_operations.cpp.o
[100%] Linking CXX executable sample1-basic-operations
[100%] Built target sample1-basic-operations

 - Version of the Library used
 git clone from recent repo.
 most recent commit in this clone is `13213977b3f7089e8595ff116b890688bee0dacf`

**Additional context**
This code used to work as expected when we were using SDK version 12.5.0
Due to a critical bug in this version, we started using a git clone version to continue our development.
This new issue seems to be caused by pull request #4024 
If there are additional steps I need to take to flush the token cache, please provide them.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by antkmsft**
Closes #4129.

There isn't much new, unreviewed code. Token Cache works as before, but now every credential instance has it (instead of a single static one), and cache key is now only a single string (scopes), instead of {TenantID, ClientID, AuthorityHost, Scopes}.
Plus, this PR adds token cache to recently added AzureCliCredential, and to ClientCertificateCredential - so now all credential types do use token caching.

### CODE REVIEW

File: sdk/identity/azure-identity/inc/azure/identity/detail/token_cache.hpp [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+  private:
+    TokenCache(TokenCache const&) = delete;
+    TokenCache& operator=(TokenCache const&) = delete;
+
+    static bool IsFresh(
+        std::shared_ptr<CacheValue> const& item,
+        DateTime::duration minimumExpiration,
+        std::chrono::system_clock::time_point now);
+
+    std::shared_ptr<CacheValue> GetOrCreateValue(
```
Comment (gearama) [inline sdk/identity/azure-identity/inc/azure/identity/detail/token_cache.hpp:60]: add a comment here that it will return value from cache, or create the entry if ti is not found

**Review by gearama — APPROVED** [review]

**Comment by ahsonkhan** [comment]
We should add a test case for this, so we don't regress the issue:
https://github.com/Azure/azure-sdk-for-cpp/issues/4129#issuecomment-1330134083

File: sdk/identity/azure-identity/CHANGELOG.md [hunk 2]
```diff
@@ -12,6 +12,9 @@
 
 ### Other Changes
 
+- Changed token cache mode to per-credential-instance. In order to get benefits from token caching, share the same credential between multiple client instances.
```
Comment (ahsonkhan) [inline sdk/identity/azure-identity/CHANGELOG.md:15]: This can go into a bug fix.
