### PR TITLE
Kv cleanup

### LINKED ISSUE #6510: KeyVault cleanup and commented out code
**Describe the bug**
We need to cleanup the code in keyvault after the move to generated code. There are some strings that are now unused, and some serialization code. As discussed previously i left that behind as the timeline was tight in getting it done and since we are releasing betas i can get that cleanup done in the next release cycle.
Also i need to figure out how to deal with the .Name in certificates witch is sanitized away since it is derived from the IdUrl which gets wiped out by the test proxy. 
***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### PR DESCRIPTION
**Pull request by gearama**
closes #6510
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

File: sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp [hunk 1]
```diff
@@ -788,14 +786,15 @@ TEST_F(KeyVaultCertificateClientTest, DownloadImportPkcs)
     options.Policy.ContentType = CertificateContentType::Pkcs12;
     options.Policy.Exportable = true;
     options.Properties.Name = importName;
+    options.Properties.PreserveCertificateOrder = true;
     auto imported = client.ImportCertificate(importName, options).Value;
-    // TODO: 6510
-    //    EXPECT_EQ(imported.Properties.Name, importName);
```
[the remark this answers is not in the document]
Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp:793]: bacause the name is not returned as part of the response, it is calculated out of the ID url ( https://<ValutUrl>/<service>/<Name> or with an extra /<Version>) the issue is that the test proxy sanitizes the URL ("Sanitized"  word instead of the URL so we can't really calculate anything there. I didn't want to special case this behavior and have effectively two tests one for test proxy one for live. We check for other things in there so we can verify we get a valid response.

**Review by antkmsft — APPROVED** [review]

File: sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_options.hpp [hunk 2]
```diff
@@ -29,7 +29,7 @@ namespace Azure { namespace Security { namespace KeyVault { namespace Certificat
      * @brief Service Version used.
      *
      */
-    std::string ApiVersion{"7.5"};
+    std::string ApiVersion{"7.6-preview.2"};
```
Comment (RickWinter) [inline sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_options.hpp:32]: Is the expectation that we won't ship another Stable release before this goes stable?

File: sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_test.cpp [hunk 3]
```diff
@@ -53,136 +53,6 @@ TEST(KeyVaultKeyClientUnitTest, GetUrl)
   EXPECT_EQ(url, keyClient.GetUrl());
 }
 
-TEST(KeyReleaseOptionsUnitTest, None)
```
Comment (RickWinter) [inline sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_test.cpp:56]: Why are we getting rid of all these tests?

File: sdk/keyvault/azure-security-keyvault-keys/src/private/key_constants.hpp [hunk 4]
```diff
@@ -13,48 +13,17 @@ namespace Azure { namespace Security { namespace KeyVault { namespace Keys { nam
...
-  constexpr static const char RecoverableDaysPropertyName[] = "recoverableDays";
-  constexpr static const char RecoveryLevelPropertyName[] = "recoveryLevel";
-  constexpr static const char HsmPlatformPropertyName[] = "hsmPlatform";
-
-  /***************** Key Request Parameters *****************/
-  constexpr static const char KeyTypePropertyName[] = "kty";
-  constexpr static const char KeySizePropertyName[] = "key_size";
-  constexpr static const char KeyOpsPropertyName[] = "key_ops";
-  constexpr static const char CurveNamePropertyName[] = "crv";
-  constexpr static const char PublicExponentPropertyName[] = "public_exponent";
```
Comment (RickWinter) [inline sdk/keyvault/azure-security-keyvault-keys/src/private/key_constants.hpp:42]: Do these all go away because of the serializer cleanup?

File: sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_options.hpp (hunk 2 above)
Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_options.hpp:32]: yeah, everyone is doing betas till then

File: sdk/keyvault/azure-security-keyvault-keys/src/private/key_constants.hpp (hunk 4 above)
Comment (gearama) [reply sdk/keyvault/azure-security-keyvault-keys/src/private/key_constants.hpp:42]: yes, and because they are defined in the generated code
