### PR TITLE
Fixed #5536, fixed a test deadlock discovered while testing the fix for 5536, added some diagnostics for uAMQP to help track the problem.

### LINKED ISSUE #5536: Intermittent test failure for AMQP LinkAttachDetachMultipleOneSession - Message receiver link detached
`Validate Win2022_Win32Api_release_curl_x86`

I don't see any logs marked as "error" or "failed" so it isn't clear what went wrong here without deciphering each logged step.

This is logged as an `[INFO]`:
>  [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(344):: Message receiver disconnected: Error {null}

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3697516&view=logs&j=e725447c-1a69-585a-f6f0-491e0d04b156&t=4dce952d-fbd4-5508-085e-a15346a8cf0a
```text
024-04-15T18:41:45.1416638Z test 563
2024-04-15T18:41:45.1417622Z         Start 563: azure-core-amqp.TestLinks.LinkAttachDetachMultipleOneSession
2024-04-15T18:41:45.1418302Z 
2024-04-15T18:41:45.1419315Z 563: Test command: D:\a\_work\1\s\build\sdk\core\azure-core-amqp\test\ut\Release\azure-core-amqp-tests.exe "--gtest_filter=TestLinks.LinkAttachDetachMultipleOneSession" "--gtest_also_run_disabled_tests"
2024-04-15T18:41:45.1420267Z 563: Working Directory: D:/a/_work/1/s/build/sdk/core/azure-core-amqp/test/ut
2024-04-15T18:41:45.1420943Z 563: Test timeout computed to be: 10000000
2024-04-15T18:41:45.1502435Z 563: Note: Google Test filter = TestLinks.LinkAttachDetachMultipleOneSession
2024-04-15T18:41:45.1503378Z 563: [==========] Running 1 test from 1 test suite.
2024-04-15T18:41:45.1504119Z 563: [----------] Global test environment set-up.
2024-04-15T18:41:45.1504679Z 563: [----------] 1 test from TestLinks
2024-04-15T18:41:45.1505177Z 563: [ RUN      ] TestLinks.LinkAttachDetachMultipleOneSession
2024-04-15T18:41:45.1543921Z 563: 
2024-04-15T18:41:45.1545186Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\session_tests.cpp(120):: Trying Test port: 49176
2024-04-15T18:41:45.1555886Z 563: [2024-04-***T18:41:45.***51933Z T: 1616] INFO  : Unknown port specified, assuming socket connection transport.
2024-04-15T18:41:45.1558116Z 563: [2024-04-***T18:41:45.***52472Z T: 1616] DEBUG : Create socket transport for host localhost port: 49176
2024-04-15T18:41:45.1561771Z 563: [2024-04-***T18:41:45.***53808Z T: 1616] DEBUG : Connection 767e88f6-c4ca-42e1-bfc4-a00327411bca state changed from CONNECTION_STATE_START to CONNECTION_STATE_START
2024-04-15T18:41:45.1562916Z 563: 
2024-04-15T18:41:45.1563913Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(596):: Wait 5 seconds for listener to start.
2024-04-15T18:41:45.1564800Z 563: 
2024-04-15T18:41:45.1565981Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(576):: Start test listener on port 49176
2024-04-15T18:41:45.1566915Z 563: 
2024-04-15T18:41:45.1567944Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(578):: listener started
2024-04-15T18:41:45.1568880Z 563: 
2024-04-15T18:41:45.1570016Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(602):: Listener running.
2024-04-15T18:41:45.1605172Z 563: [2024-04-***T18:41:45.***99384Z[ T: 2024-04-***T18:41:45.***99579Z T: 9480] WARN  : File: D:\a\_work\1\s\build\_deps\vcpkg-src\buildtrees\azure-c-shared-utility\src\d9ae13ea55-d48f7a9441.clean\src\dns_resolver_sync.c:50 Func: _dns_resolver_create: NULL hostname
2024-04-15T18:41:45.1606692Z 563: 
2024-04-15T18:41:45.1609132Z 563: 1616[  INFO ]]  DEBUGD:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(679): : : File: D:\a\_work\1\s\sdk\core\azure-core-amqp\vendor\azure-uamqp-c\src\connection.c:412 Func: _send_header: -> Header (AMQP 0.1.0.0)
2024-04-15T18:41:45.1610567Z 563: OnSocketAccepted - Socket connection received.
2024-04-15T18:41:45.1611674Z 563: [2024-04-***T18:41:45.1601438Z
2024-04-15T18:41:45.1613022Z 563:  T: 1616] [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(699):: Connection State changed. Connection: Mock Server for LinkAttachDetachMultipleOneSession Old state : Start New state: Start
2024-04-15T18:41:45.1614511Z 563: [2024-04-***T18:41:45.1602201Z T: 9480] DEBUG : ConnectionImpl::Listen: 00A311C0 ID: Mock Server for LinkAttachDetachMultipleOneSession
2024-04-15T18:41:45.1615398Z 563: DEBUG
2024-04-15T18:41:45.1616613Z 563: [  INFO ] :  Connection 767e88f6-c4ca-42e1-bfc4-a00327411bca state changed from CONNECTION_STATE_START to CONNECTION_STATE_HDR_SENTD:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(699):
2024-04-15T18:41:45.1617835Z 563: : Connection State changed. Connection: Mock Server for LinkAttachDetachMultipleOneSession Old state : Start New state: HeaderExchanged
2024-04-15T18:41:45.1618692Z 563: 
2024-04-15T18:41:45.1619942Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(699):: Connection State changed. Connection: Mock Server for LinkAttachDetachMultipleOneSession Old state : HeaderExchanged New state: OpenSent
2024-04-15T18:41:45.1622383Z 563: [2024-04-***T18:41:45.1603365Z T: 1616] DEBUG : Connection 767e88f6-c4ca-42e1-bfc4-a00327411bca state changed from CONNECTION_STATE_HDR_SENT to CONNECTION_STATE_START
2024-04-15T18:41:45.1623868Z 563: [2024-04-***T18:41:45.1605351Z T: 1616] DEBUG : Try to enable async operation on connection: 00A2AF10 ID: 767e88f6-c4ca-42e1-bfc4-a00327411bca count: 0
2024-04-15T18:41:45.1625209Z 563: [2024-04-***T18:41:45.1606410Z T: 1616] DEBUG : Enabled async operation on connection: 00A2AF10 ID: 767e88f6-c4ca-42e1-bfc4-a00327411bca
2024-04-15T18:41:45.1626535Z 563: [2024-04-***T18:41:45.1607489Z T: 1616] DEBUG : Try to enable async operation on connection: 00A2AF10 ID: 767e88f6-c4ca-42e1-bfc4-a00327411bca count: 1
2024-04-15T18:41:45.2639779Z 563: [2024-04-***T18:41:45.2636540Z T: 2400] DEBUG : File: D:\a\_work\1\s\sdk\core\azure-core-amqp\vendor\azure-uamqp-c\src\connection.c:927 Func: _connection_byte_received: <- Header (AMQP 0.1.0.0)
2024-04-15T18:41:45.2641465Z 563: [2024-04-***T18:41:45.2637343Z T: 2400] DEBUG : Connection 767e88f6-c4ca-42e1-bfc4-a00327411bca state changed from CONNECTION_STATE_START to CONNECTION_STATE_HDR_EXCH
2024-04-15T18:41:45.2643187Z 563: [2024-04-***T18:41:45.2638206Z T: 2400] DEBUG : 65535:-> [OPEN]* {767e88f6-c4ca-42e1-bfc4-a00327411bca,localhost,4294967295,65535,60000,NULL,NULL,NULL,NULL,{}}
2024-04-15T18:41:45.2645043Z 563: [2024-04-***T18:41:45.2639044Z T: 2400] DEBUG : Connection 767e88f6-c4ca-42e1-bfc4-a00327411bca state changed from CONNECTION_STATE_HDR_EXCH to CONNECTION_STATE_OPEN_SENT
2024-04-15T18:41:45.2646514Z 563: [2024-04-***T18:41:45.2640032Z T: 2400] DEBUG : 0:<- [OPEN]* {Mock Server for LinkAttachDetachMultipleOneSession,localhost,4294967295,65535,120000,NULL,NULL,NULL,NULL,{}}
2024-04-15T18:41:45.2647965Z 563: [2024-04-***T18:41:45.2640638Z T: 2400] DEBUG : Connection 767e88f6-c4ca-42e1-bfc4-a00327411bca state changed from CONNECTION_STATE_OPEN_SENT to CONNECTION_STATE_OPENED
2024-04-15T18:41:45.2649227Z 563: [2024-04-***T18:41:45.264***60Z T: 2400] DEBUG : 0:-> [BEGIN]* {NULL,0,1,1,4294967295}
2024-04-15T18:41:45.3732803Z 563: 
2024-04-15T18:41:45.3735816Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(699):: Connection State changed. Connection: Mock Server for LinkAttachDetachMultipleOneSession Old state : OpenSent New state: Opened
2024-04-15T18:41:45.3736975Z 563: 
2024-04-15T18:41:45.3738112Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(712):: OnNewEndpoint - Incoming endpoint created, create session.
2024-04-15T18:41:45.3739392Z 563: [2024-04-***T18:41:45.3731821Z T: 2400] DEBUG : 0:<- [BEGIN]* {0,0,10000,1,4294967295}
2024-04-15T18:41:45.3740651Z 563: [2024-04-***T18:41:45.3733592Z T: 2400] DEBUG : 0:-> [ATTACH]* {KeepConnectionAlive,0,true,0,0,* {MyTarget},* {TestReceiver},NULL,NULL,NULL,0}
2024-04-15T18:41:45.3742083Z 563: [2024-04-***T18:41:45.3734537Z T: 2400] DEBUG : 0:-> [ATTACH]* {MySession,1,false,0,0,* {MySource},* {MyTarget},NULL,NULL,0,0}
2024-04-15T18:41:45.3742950Z 563: 
2024-04-15T18:41:45.3744069Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(352):: Link MySession, State Changed. OldState: Detached NewState: HalfAttachedAttachSent
2024-04-15T18:41:45.4827808Z 563: [2024-04-***T18:41:45.4824412Z T: 2400] WARN  : File: D:\a\_work\1\s\sdk\core\azure-core-amqp\vendor\azure-uamqp-c\src\amqpvalue.c:2265 Func: _amqpvalue_clone: NULL value
2024-04-15T18:41:45.4829263Z 563: 
2024-04-15T18:41:45.4831394Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(740):: OnLinkAttached for name: KeepConnectionAlive Source : Source{ Address: MyTarget, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Target : Target{ Address: TestReceiver, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Role: Receiver
2024-04-15T18:41:45.4833094Z 563: 
2024-04-15T18:41:45.4835675Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(75):: MockServiceEndpoint::OnLinkAttached for name: MyTarget Source : Source{ Address: MyTarget, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Target : Target{ Address: TestReceiver, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false}
2024-04-15T18:41:45.4837128Z 563: 
2024-04-15T18:41:45.4838162Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(83):: Role is receiver, create sender.
2024-04-15T18:41:45.4839006Z 563: 
2024-04-15T18:41:45.4840055Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(86):: No sender found, create new sender for KeepConnectionAlive
2024-04-15T18:41:45.4841571Z 563: [2024-04-***T18:41:45.4828096Z T: 2400] DEBUG : Opening message sender. Authenticate if needed with audience: Target{ Address: TestReceiver, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false}
2024-04-15T18:41:45.4842907Z 563: [2024-04-***T18:41:45.4828443Z T: 2400] DEBUG : No credential, returning empty token.
2024-04-15T18:41:45.4844090Z 563: [2024-04-***T18:41:45.4828812Z T: 2400] DEBUG : Message sender state changed from Idle(1) to Opening(2).
2024-04-15T18:41:45.4844949Z 563: 
2024-04-15T18:41:45.4846123Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(354):: MockServiceEndpoint(MyTarget) Message Sender State changed.Old state : Idle New state: Opening
2024-04-15T18:41:45.4847593Z 563: [2024-04-***T18:41:45.4830094Z T: 2400] DEBUG : Opening message sender. Enable async operation.
2024-04-15T18:41:45.4848899Z 563: [2024-04-***T18:41:45.4830872Z T: 2400] DEBUG : Message sender state changed from Opening(2) to Open(3).
2024-04-15T18:41:45.4849775Z 563: 
2024-04-15T18:41:45.4851016Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(354):: MockServiceEndpoint(MyTarget) Message Sender State changed.Old state : Opening New state: Open
2024-04-15T18:41:45.4852574Z 563: [2024-04-***T18:41:45.4831681Z T: 2400] WARN  : File: D:\a\_work\1\s\sdk\core\azure-core-amqp\vendor\azure-uamqp-c\src\amqpvalue.c:2265 Func: _amqpvalue_clone: NULL value
2024-04-15T18:41:45.4853527Z 563: 
2024-04-15T18:41:45.4855057Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(740):: OnLinkAttached for name: MySession Source : Source{ Address: MySource, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Target : Target{ Address: MyTarget, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Role: Sender
2024-04-15T18:41:45.4856278Z 563: 
2024-04-15T18:41:45.4857832Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(75):: MockServiceEndpoint::OnLinkAttached for name: MyTarget Source : Source{ Address: MySource, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Target : Target{ Address: MyTarget, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false}
2024-04-15T18:41:45.4859234Z 563: 
2024-04-15T18:41:45.4860214Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(109):: Role is sender, create receiver.
2024-04-15T18:41:45.4861049Z 563: 
2024-04-15T18:41:45.4862099Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(112):: No receiver found, create new receiver for MySession
2024-04-15T18:41:45.4863326Z 563: [2024-04-***T18:41:45.4836266Z T: 2400] DEBUG : MessageReceiver: Subscribe to link detach on:009D7138
2024-04-15T18:41:45.4864157Z 563: 
2024-04-15T18:41:45.4865134Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(120):: Open new message receiver.
2024-04-15T18:41:45.4866267Z 563: [2024-04-***T18:41:45.4836890Z T: 2400] DEBUG : No credential, returning empty token.
2024-04-15T18:41:45.4867478Z 563: [2024-04-***T18:41:45.4838069Z T: 2400] DEBUG : Message receiver state change MESSAGE_RECEIVER_STATE_IDLE -> MESSAGE_RECEIVER_STATE_OPENING
2024-04-15T18:41:45.4868778Z 563: [2024-04-***T18:41:45.4839073Z T: 2400] DEBUG : Opening message receiver. Start async
2024-04-15T18:41:45.4869984Z 563: [2024-04-***T18:41:45.4840016Z T: 2400] DEBUG : Message receiver state change MESSAGE_RECEIVER_STATE_OPENING -> MESSAGE_RECEIVER_STATE_OPEN
2024-04-15T18:41:45.4870843Z 563: 
2024-04-15T18:41:45.4871983Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(324):: MockServiceEndpoint(MyTarget): Message Receiver State changed.Old state : Opening New state: Open
2024-04-15T18:41:45.4873434Z 563: [2024-04-***T18:41:45.4841409Z T: 2400] DEBUG : 0:<- [ATTACH]* {KeepConnectionAlive,0,false,0,0,* {TestReceiver},* {MyTarget},NULL,NULL,0,184467440737095516***}
2024-04-15T18:41:45.4874626Z 563: [2024-04-***T18:41:45.4842162Z T: 2400] DEBUG : 0:-> [FLOW]* {0,1,0,1,0,0,10000}
2024-04-15T18:41:45.4875872Z 563: [2024-04-***T18:41:45.4844992Z T: 2400] DEBUG : 0:<- [ATTACH]* {MySession,1,true,0,0,* {MyTarget},* {MySource},NULL,NULL,NULL,184467440737095516***,NULL,NULL,{}}
2024-04-15T18:41:45.4876806Z 563: 
2024-04-15T18:41:45.4877914Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(352):: Link MySession, State Changed. OldState: HalfAttachedAttachSent NewState: Attached
2024-04-15T18:41:45.4879139Z 563: [2024-04-***T18:41:45.4846501Z T: 2400] DEBUG : 0:<- [FLOW]* {0,10000,0,1,1,0,10000}
2024-04-15T18:41:45.4879914Z 563: 
2024-04-15T18:41:45.4880868Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(335):: Link Flow On on link MySession
2024-04-15T18:41:45.4881682Z 563: 
2024-04-15T18:41:45.4882621Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(335):: Link Flow On on link MySession
2024-04-15T18:41:45.4883737Z 563: [2024-04-***T18:41:45.4848378Z T: 1616] DEBUG : 0:-> [TRANSFER]* {1,0,<01 00 00 00>,0,false,false}
2024-04-15T18:41:45.5922708Z 563: 
2024-04-15T18:41:45.5924378Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(334):: MockServiceEndpoint(MyTarget) Received a message Message: <
2024-04-15T18:41:45.5927177Z 563:     Header{durable=false, priority=4, firstAcquirer=false, deliveryCount=0}
2024-04-15T18:41:45.5928180Z 563:     MessageProperties {MessageId: <null>}, deliveryTag=<01 00 00 00>
2024-04-15T18:41:45.5928986Z 563:     Body: [AmqpValue, type=String
2024-04-15T18:41:45.5929664Z 563: >
2024-04-15T18:41:45.5930643Z 563: [2024-04-***T18:41:45.5919390Z T: 2400] DEBUG : 0:<- [DISPOSITION]* {true,0,0,true,* {}}
2024-04-15T18:41:45.5931672Z 563: [2024-04-***T18:41:45.5920444Z T: 1616] 
2024-04-15T18:41:45.5932576Z 563: DEBUG : [  INFO ]0:-> [DETACH]* {1,true}
2024-04-15T18:41:45.5933652Z 563:  D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(281):: Received message on link MySession
2024-04-15T18:41:45.5934738Z 563: : [  INFO ]Message: < 
2024-04-15T18:41:45.5936038Z 563: D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(352)::     Link Header{MySessiondurable=, State Changed. OldState: falseAttached, priority= NewState: 4HalfAttachedAttachSent, firstAcquirer=
2024-04-15T18:41:45.5937086Z 563: false, deliveryCount=0}
2024-04-15T18:41:45.5938353Z 563:     [2024-04-***T18:41:45.5921685Z T: MessageProperties {1616MessageId: <null>] }DEBUG, deliveryTag= : Try to disable async operation on connection: 00A2AF10 ID: 767e88f6-c4ca-42e1-bfc4-a00327411bca count: 2
2024-04-15T18:41:45.5939342Z 563: <01 00 00 00>
2024-04-15T18:41:45.5940044Z 563:     Body: [AmqpValue, type=String
2024-04-15T18:41:45.5940834Z 563: >
2024-04-15T18:41:45.5941459Z 563: 
2024-04-15T18:41:45.5942477Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(301):: Message received on link MySession: Message: <
2024-04-15T18:41:45.5943459Z 563:     Header{durable=false, priority=4, firstAcquirer=false, deliveryCount=0}
2024-04-15T18:41:45.5944380Z 563:     MessageProperties {MessageId: <null>}, deliveryTag=<01 00 00 00>
2024-04-15T18:41:45.5945277Z 563:     Body: [AmqpValue, type=String
2024-04-15T18:41:45.5945945Z 563: >
2024-04-15T18:41:45.7015040Z 563: 
2024-04-15T18:41:45.7016903Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(344):: Message receiver disconnected: Error {null}
2024-04-15T18:41:45.7019180Z 563: 
2024-04-15T18:41:45.7020886Z 563: 
2024-04-15T18:41:45.7022560Z 563: [2024-04-***T18:41:45.7011833Z[  INFO ] T: 2400 ] WARN  : D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(301):Message receiver link detached: : : 
2024-04-15T18:41:45.7023712Z 563: Receiver disconnected: MySession
2024-04-15T18:41:45.7025082Z 563: [[2024-04-***T18:41:45.7012433Z2024-04-***T18:41:45.7012395Z T:  T: 93522400] ] DEBUGDEBUG :  : Lock for Closing message receiver.Message receiver state change MESSAGE_RECEIVER_STATE_OPEN -> MESSAGE_RECEIVER_STATE_IDLE
2024-04-15T18:41:45.7026146Z 563: 
2024-04-15T18:41:45.7026770Z 563: 
2024-04-15T18:41:45.7027902Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(324):: MockServiceEndpoint(MyTarget): Message Receiver State changed.Old state : Open New state: Idle
2024-04-15T18:41:45.7029163Z 563: [2024-04-***T18:41:45.7013929Z T: 2400] DEBUG : 0:<- [DETACH]* {1,true}
2024-04-15T18:41:45.7029938Z 563: 
2024-04-15T18:41:45.7031047Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(352):: Link MySession, State Changed. OldState: HalfAttachedAttachSent NewState: Detached
2024-04-15T18:41:45.7032310Z 563: [2024-04-***T18:41:45.7018675Z T: 9352] DEBUG : Wait for receiver detach to complete. Current state: Idle
2024-04-15T18:41:45.7033479Z 563: [2024-04-***T18:41:45.7019012Z T: 9352] DEBUG : Receiver unsubscribe from link detach event on 009D7138
2024-04-15T18:41:45.7034796Z 563: [2024-04-***T18:41:45.7019190Z T: 1616] [2024-04-***T18:41:45.7019390ZDEBUG T: 9352]  : DEBUG : 0:-> [ATTACH]* {MySession2,1,false,0,0,* {MySource},* {MyTarget},NULL,NULL,0,0}
2024-04-15T18:41:45.7035804Z 563: Closing message receiver. Stop async
2024-04-15T18:41:45.7036495Z 563: 
2024-04-15T18:41:45.7037596Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(352):: Link MySession2, State Changed. OldState: Detached NewState: HalfAttachedAttachSent
2024-04-15T18:41:45.7038985Z 563: [2024-04-***T18:41:45.7020207Z T: 1616] DEBUG : Try to enable async operation on connection: 00A2AF10 ID: 767e88f6-c4ca-42e1-bfc4-a00327411bca count: 1
2024-04-15T18:41:45.8107735Z 563: [2024-04-***T18:41:45.8105232Z T: 2400] WARN  : File: D:\a\_work\1\s\sdk\core\azure-core-amqp\vendor\azure-uamqp-c\src\amqpvalue.c:2265 Func: _amqpvalue_clone: NULL value
2024-04-15T18:41:45.8108896Z 563: 
2024-04-15T18:41:45.8110496Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(740):: OnLinkAttached for name: MySession2 Source : Source{ Address: MySource, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Target : Target{ Address: MyTarget, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Role: Sender
2024-04-15T18:41:45.8111909Z 563: 
2024-04-15T18:41:45.8114337Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(75):: MockServiceEndpoint::OnLinkAttached for name: MyTarget Source : Source{ Address: MySource, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false} Target : Target{ Address: MyTarget, Durable: None, Expiry Policy: session-end, Timeout: 0, Dynamic: false}
2024-04-15T18:41:45.8116496Z 563: 
2024-04-15T18:41:45.8118610Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(109):: Role is sender, create receiver.
2024-04-15T18:41:45.8120046Z 563: 
2024-04-15T18:41:45.8121361Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(112):: No receiver found, create new receiver for MySession2
2024-04-15T18:41:45.8122639Z 563: [2024-04-***T18:41:45.8108529Z T: 2400] DEBUG : MessageReceiver: Subscribe to link detach on:009D6EF8
2024-04-15T18:41:45.8123598Z 563: 
2024-04-15T18:41:45.8124538Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(120):: Open new message receiver.
2024-04-15T18:41:45.8125610Z 563: [2024-04-***T18:41:45.8110399Z T: 2400] DEBUG : No credential, returning empty token.
2024-04-15T18:41:45.8126760Z 563: [2024-04-***T18:41:45.8110767Z T: 2400] DEBUG : Message receiver state change MESSAGE_RECEIVER_STATE_IDLE -> MESSAGE_RECEIVER_STATE_OPENING
2024-04-15T18:41:45.8127873Z 563: [2024-04-***T18:41:45.8111484Z T: 2400] DEBUG : Opening message receiver. Start async
2024-04-15T18:41:45.8129016Z 563: [2024-04-***T18:41:45.8113374Z T: 2400] DEBUG : Message receiver state change MESSAGE_RECEIVER_STATE_OPENING -> MESSAGE_RECEIVER_STATE_OPEN
2024-04-15T18:41:45.8129831Z 563: 
2024-04-15T18:41:45.8130910Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(324):: MockServiceEndpoint(MyTarget): Message Receiver State changed.Old state : Opening New state: Open
2024-04-15T18:41:45.8132282Z 563: [2024-04-***T18:41:45.8114478Z T: 2400] DEBUG : 0:<- [ATTACH]* {MySession2,1,true,0,0,* {MyTarget},* {MySource},NULL,NULL,NULL,184467440737095516***,NULL,NULL,{}}
2024-04-15T18:41:45.8133129Z 563: 
2024-04-15T18:41:45.8134159Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(352):: Link MySession2, State Changed. OldState: HalfAttachedAttachSent NewState: Attached
2024-04-15T18:41:45.8135307Z 563: [2024-04-***T18:41:45.81***395Z T: 2400] DEBUG : 0:<- [FLOW]* {1,9999,0,1,1,0,10000}
2024-04-15T18:41:45.8136028Z 563: 
2024-04-15T18:41:45.8136925Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(335):: Link Flow On on link MySession2
2024-04-15T18:41:45.8137689Z 563: 
2024-04-15T18:41:45.8138582Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(335):: Link Flow On on link MySession2
2024-04-15T18:41:45.8139609Z 563: [2024-04-***T18:41:45.8118019Z T: 1616] DEBUG : 0:-> [DETACH]* {1,true}
2024-04-15T18:41:45.8140330Z 563: 
2024-04-15T18:41:45.8141350Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(352):: Link MySession2, State Changed. OldState: Attached NewState: HalfAttachedAttachSent
2024-04-15T18:41:45.8142649Z 563: [2024-04-***T18:41:45.8118895Z T: 1616] DEBUG : Try to disable async operation on connection: 00A2AF10 ID: 767e88f6-c4ca-42e1-bfc4-a00327411bca count: 2
2024-04-15T18:41:45.9201455Z 563: 
2024-04-15T18:41:45.9203889Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(344):: Message receiver disconnected: Error {null}
2024-04-15T18:41:45.9205239Z 563: 
2024-04-15T18:41:45.9208444Z 563: [2024-04-***T18:41:45.9199666Z T: 2400] WARN  : Message receiver link detached: : 
2024-04-15T18:41:45.9210154Z 563: [2024-04-***T18:41:45.9200211Z T: 2400] DEBUG : Message receiver state change MESSAGE_RECEIVER_STATE_OPEN -> MESSAGE_RECEIVER_STATE_IDLE
2024-04-15T18:41:45.9211552Z 563: 
2024-04-15T18:41:45.9212741Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(324):: MockServiceEndpoint(MyTarget): Message Receiver State changed.Old state : Open New state: Idle
2024-04-15T18:41:45.9214277Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\mock_amqp_server.hpp(301):: Receiver disconnected: MySession2
2024-04-15T18:41:45.9215342Z 563: [2024-04-***T18:41:45.9203390Z T: 9352] DEBUG : Lock for Closing message receiver.
2024-04-15T18:41:45.9216029Z 563: 
2024-04-15T18:41:45.9232561Z 563: [2024-04-***T18:41:45.9204858Z T: 2400] DEBUG : 0:<- [DETACH]* {1,true}
2024-04-15T18:41:45.9233468Z 563: 
2024-04-15T18:41:45.9234563Z 563: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\link_tests.cpp(352):: Link MySession2, State Changed. OldState: HalfAttachedAttachSent NewState: Detached
2024-04-15T18:41:50.6669368Z 416/510 Test #563: azure-core-amqp.TestLinks.LinkAttachDetachMultipleOneSession ......................................***Failed    5.52 sec
```

### PR DESCRIPTION
**Pull request by LarryOsterman**
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp [hunk 1]
```diff
@@ -175,6 +175,15 @@ namespace Azure { namespace Core { namespace Amqp { namespace _internal {
      */
     std::pair<std::shared_ptr<const Models::AmqpMessage>, Models::_internal::AmqpError>
     TryWaitForIncomingMessage();
+#if _azure_TESTING_BUILD
+    // There is a deadlock associated with the link polling if it is enabled from an AMQP event
+    // callback. To work around this, link polling is disabled when creating a message receiver from
+    // an existing link endpoint. This method should be calledto enable it at a time when it is
```
Comment (ahsonkhan) [inline sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp:181]:
```suggestion
    // an existing link endpoint. This method should be called to enable it at a time when it is
```

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp [hunk 2]
```diff
@@ -175,6 +175,15 @@ namespace Azure { namespace Core { namespace Amqp { namespace _internal {
...
+    // safer to enable link polling.
+
+    // This is a test hook and should not be used outside of test code.
+    void EnableLinkPolling();
```
Comment (ahsonkhan) [inline sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp:185]: Should this be private, since it is a test hook only?

File: sdk/core/azure-core-amqp/test/ut/mock_amqp_server.hpp [hunk 3]
```diff
@@ -764,6 +760,29 @@ namespace Azure { namespace Core { namespace Amqp { namespace Tests {
...
+      std::string m_connectionId;
+      std::thread m_serverThread;
+      std::uint16_t m_testPort;
+
+      // For each incoming message source, we create a queue of messages intended for that
+      // message source.
+      //
+      // Each message queue is keyed by the message-id.
+      // std::map < std::string, MessageLinkComponents> m_linkMessageQueues;
+      Azure::Core::Context m_listenerContext; // Used to cancel the listener if necessary.
```
Comment (ahsonkhan) [inline sdk/core/azure-core-amqp/test/ut/mock_amqp_server.hpp:785]: Remove the commented out code snippets?

File: sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/link.c [hunk 4]
```diff
@@ -801,11 +802,12 @@ LINK_HANDLE link_create(SESSION_HANDLE session, const char* name, role role, AMQ
                 }
                 else
                 {
+                    (void)memcpy(result->name, name, name_length + 1);
```
Comment (ahsonkhan) [inline sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/link.c:805]: Why was this move necessary? Could you add a comment explaining so that someone doesn't accidentally re-order it.

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp (hunk 2 above)
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp:185]: I guess. Not sure it matters though.

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp (hunk 1 above)
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp]: Please look at the most current iteration :).

File: sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/link.c (hunk 4 above)
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/link.c:805]: The move was necessary because in C, it's important to initialize variables as soon as possible. Otherwise there is allocated but uninitialized memory that can potentially be accessed.

Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/link.c:805]: After writing the comment explaining this change, I realized that it fell into the same category of comment as `foo = 1; // Assign 1 to foo`. And I really dislike that style of comments.

**Review by antkmsft — APPROVED** [review]
Thank you! I'm glad to see this fixed. It must not have been easy to repro this.

Add changelog?

BTW, for automatic issue linking and integration, I think you need to put `Fixes #5536` in the PR description, not to the title.

File: sdk/core/azure-core-amqp/src/amqp/message_receiver.cpp [hunk 5]
```diff
@@ -541,9 +578,15 @@ namespace Azure { namespace Core { namespace Amqp { namespace _detail {
       bool shouldWaitForClose = m_currentState == _internal::MessageReceiverState::Closing
           || m_currentState == _internal::MessageReceiverState::Open;
 
-      Common::_detail::GlobalStateHolder::GlobalStateInstance()->RemovePollable(
-          m_link); // This will ensure that the link is cleaned up on the next poll()
-
+      {
+        std::unique_lock<std::mutex> lock{m_MutableState};
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/src/amqp/message_receiver.cpp:582]:
```suggestion
        std::unique_lock<std::mutex> lock{m_mutableState};
```

File: sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/connection.c [hunk 6]
```diff
@@ -2481,6 +2481,23 @@ int connection_set_remote_idle_timeout_empty_frame_send_ratio(CONNECTION_HANDLE
...
+    {
+		LogError("NULL connection");
+		result = NULL;
+	}
+    else
+    {
+		result = connection->container_id;
+	}
+
+	return result;
```
[the remark this answers is not in the document]
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/connection.c:2498]: uAMQP uses tabs, not spaces.

File: sdk/core/azure-core-amqp/src/amqp/message_receiver.cpp [hunk 7]
```diff
@@ -541,9 +578,15 @@ namespace Azure { namespace Core { namespace Amqp { namespace _detail {
...
+        if (m_linkPollingEnabled)
+        {
+          Common::_detail::GlobalStateHolder::GlobalStateInstance()->RemovePollable(
```
[the remark this answers is not in the document]
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/src/amqp/message_receiver.cpp:585]: It's under a lock, and this is the only code which calls RemovePollable. How would moving the linkPollingEnabled = false before the RemovePollable fix anything?

[the remark this answers is not in the document]
Comment (antkmsft) [reply sdk/core/azure-core-amqp/src/amqp/message_receiver.cpp:585]: Should this get called from a separate thread (which it probably shouldn't based on your question), an if that happens while in `RemovePollable()` then execution of another thread will once again enter inside `if (m_linkPollingEnabled)`, however if we set it to false before calling, there is less chance of this happening. Okay, I realized, even then it is too fragile without atomics and mutexes, and we'd need more than what I am suggesting to enable it, and this must never be getting called concurrently. So I retract my suggestion.

[the remark this answers is not in the document]
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/src/amqp/message_receiver.cpp:585]: ??? There *is* a mutex here - the `m_mutableState` mutex, and it's held as of line 582. 

I originally wrote the code without the mutex and then realized that I had a concurrency problem, so I added the m_mutableState mutex to cover this case. 

Currently the only state covered by the `m_mutableState` mutex is the `m_linkPollingEnabled` field in the struct. 

Note that there *is* a possible deadlock here, because AddPollable and RemovePollable both take the global pollables lock, AND the RemovePollable blocks waiting on any polling operations to complete. So if you attempt to call AddPollable or RemovePollable while holding any common locks, you can have a deadlock (in fact, that's *exactly* the reason that the `EnableLinkPolling` method was added - we had a case where we could call `AddPollable` while holding the connection lock which triggeed a deadlock.

**Comment by ahsonkhan** [comment]
This PR is doing a few things. For my edification, either in the PR description, or as a reply, can you please summarize the root cause of the underlying issue, and highlight how this PR is fixing it? It would be helpful in reviewing the most relevant parts.

**Comment by LarryOsterman** [comment]
> This PR is doing a few things. For my edification, either in the PR description, or as a reply, can you please summarize the root cause of the underlying issue, and highlight how this PR is fixing it? It would be helpful in reviewing the most relevant parts.

IMHO the PR is doing one thing: Making the link test reliable. And most of the root causes are laid out in the text of the PR.

But here's a summary of the fixes:

* Fixed a use-after-free error caused by unprotected access to a uAMQP API, specifically the `link_create` and `link_create_from_endpoint` APIs.
* Fixed a deadlock caused by calling AddPollable while holding the connection lock.
* Fixed a case in uAMQP where functions were called on a link before setting the value of the `name` field
* Fixed an uninitialized member field in uAMQP, which could lead to freeing uninitialized memory.
* Fixed a bug in uAMQP where the `session_set_link_endpoint_callback` method was not called from `link_create_from_endpoint`.

All these fixes were found either when running the test lots of times, or by diagnostics added trying to track down the bugs.
