### PR TITLE
Transaction insert replace

### LINKED ISSUE #5618: `TableClient::SubmitTransaction()` doesn't work for `TransactionActionType` `InsertReplace`
**Describe the bug**
`TableClient::SubmitTransaction()` with `TransactionStep.Action` set to `InsertReplace` doesn't insert entities. It works fine with action `Add`, or when using `Upsert` method without transaction.

**To Reproduce**
- run the code snippet

***Code Snippet***
```
#include <iostream>
#include <azure/data/tables.hpp>
#include <azure/identity/default_azure_credential.hpp>

int main() {
  auto cred = std::make_shared<Azure::Identity::DefaultAzureCredential>();
  std::string tableName = "<your table name>";
  std::string storageUrl= "<your storage account url>";
  auto tableClient = Azure::Data::Tables::TableClient(storageUrl, tableName, cred);
  auto serviceClient = Azure::Data::Tables::TableServiceClient(storageUrl, cred);
  serviceClient.CreateTable(tableName);

  auto transaction = std::vector<Azure::Data::Tables::Models::TransactionStep>(1);
  auto entity = Azure::Data::Tables::Models::TableEntity();
  entity.SetPartitionKey("partition");
  entity.SetRowKey("rowKey");
  transaction[0].Entity = entity;
  transaction[0].Action = Azure::Data::Tables::Models::TransactionActionType::InsertReplace;
  tableClient.SubmitTransaction(transaction);

  auto response = tableClient.QueryEntities();
  std::cout << "returned " << response.TableEntities.size() << " entities"; // got 0, expected 1
}
```

**Expected behavior**
Expected to insert 1 entity, as per code snippet

**Setup**
OS: WSL, Ubuntu 22.04
IDE : VS Code
Version of the Library used: azure-data-tables-cpp, 1.0.0-beta.2 (pulled from VCPKG)

### PR DESCRIPTION
**Pull request by gearama**
closes #5618 
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

**Review by antkmsft — APPROVED** [review]

File: sdk/tables/azure-data-tables/src/tables_clients.cpp [hunk 1]
```diff
@@ -1111,3 +1113,32 @@ std::string TableClient::PrepUpdateEntity(
...
+{
+  std::string payload = Serializers::UpdateEntity(entity);
+  std::string returnValue = "--" + changesetId + "\n";
+  returnValue += "Content-Type: application/http\n";
+  returnValue += "Content-Transfer-Encoding: binary\n\n";
+
+  returnValue += "PATCH " + m_url.GetAbsoluteUrl() + "/" + m_tableName + PartitionKeyFragment
+      + entity.GetPartitionKey().Value + RowKeyFragment + entity.GetRowKey().Value + ClosingFragment
+      + " HTTP/1.1\n";
+  returnValue += "Content-Type: application/json\n";
```
Comment (ahsonkhan) [inline sdk/tables/azure-data-tables/src/tables_clients.cpp:1129]: I see you have this pattern elsewhere, so consider this a broader question.

A lot of this string construction looks like it is building out a request object, with http method, request line, content-type, etc.

Is it feasible to use our `Azure::Core::Http::Request` type to build out this string?
https://github.com/Azure/azure-sdk-for-cpp/blob/7db4f3ac1c98d624373c138ddd19d8c7ff50e17a/sdk/core/azure-core/inc/azure/core/http/http.hpp#L182

Comment (gearama) [reply sdk/tables/azure-data-tables/src/tables_clients.cpp:1129]: it's not quite a request it's a mangled string that looks ugly. i'll look into it though
