### PR TITLE
Fixed libcurl connection pool to use `Connection` response header values

### LINKED ISSUE #5450: HTTP Error 400. The request verb is invalid
**Describe the bug**
After a recent vcpkg upgrade we started to see error "400 - The request verb is invalid" when doing a request to blob storage after a failed attempt to upload to a blob that doesn't exist. I was able to get to a minimum code sample that reproduces the issue. When we try to upload data to a blob that doesn't exist, we get an exception. If we catch the exception and try to do some other blob operation, for example, we want to create a container, the new operation fails with error 400 - The request verb is invalid. 

***Exception or Stack Trace***

```
Exception: 404 The specified container does not exist.
The specified container does not exist.
RequestId:3bcbc36d-601e-0055-5a54-766ea1000000
Time:2024-03-14T21:16:12.6286930Z
Request ID: 3bcbc36d-601e-0055-5a54-766ea1000000
terminate called after throwing an instance of 'Azure::Storage::StorageException'
  what():  400 Bad Request
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Verb</h2>
<hr><p>HTTP Error 400. The request verb is invalid.</p>
</BODY></HTML>

Request ID: 
Aborted
```

**To Reproduce**
Run the provided code

***Code Snippet***
```
#include <iostream>

#include <azure/core.hpp>
#include <azure/storage/blobs.hpp>

std::string GetConnectionString() {
  return std::getenv("AZURE_STORAGE_CONNECTION_STRING");
}

int main() {
  const std::string connectionString = GetConnectionString();

  auto serviceClient =
      Azure::Storage::Blobs::BlobServiceClient::CreateFromConnectionString(
          connectionString);
  auto blobClient = serviceClient.GetBlobContainerClient("notexists")
                        .GetBlockBlobClient("test");

  std::string val = "some_content";
  try {
    blobClient.UploadFrom(reinterpret_cast<const uint8_t *>(val.data()),
                          val.size());
  } catch (const std::exception &e) {
    std::cout << "Exception: " << e.what() << std::endl;
  }

  auto serviceClient2 =
      Azure::Storage::Blobs::BlobServiceClient::CreateFromConnectionString(
          connectionString);
  serviceClient2.GetBlobContainerClient("create2").CreateIfNotExists();
}
```

**Expected behavior**
The call to create container "create2" should succeed.

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: [e.g. iOS]: Ubuntu-22.04 in WSL
 - IDE : [e.g. IntelliJ]: VS Code
 - Version of the Library used: Should be the latest vcpkg 
   - azure-identity-cpp: 1.6.0
   - azure-storage-blobs-cpp: 12.10.0

**Additional context**

The sample provided here fails with the latest vcpkg. In our codebase it fails with vcpkg ref "002c5b065927a6142dd7858813f25a10947094d8" from Feb 29, 2024.

I tried to debug the network calls with Fiddler and it was tricky to make it work from WSL to Windows, but I noticed that the PUT call to upload data to the blob that doesn't exist failed with 408 when proxied through Fiddler. The content-length header was set to 12, but no data were sent. I am wondering if the follow-up request could be prefixed by those 12 bytes that were not sent with the PUT request. It's just my idea, I wasn't able to inspect the failing request.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by antkmsft**
Fixes #5450.

I propose for us to revert #5308 first (which is done by a sibling PR  #5472), and then immediately release a GA patch/minor version, and then to merge this change, and release a beta.

### CODE REVIEW

**Comment by Jinming-Hu** [comment]
I don't understand how this fixed #5450.

Can we add another check? If status code is not 2xx, and request header contains `Expect: 100-continue` and request body length is not zero, we don't reuse the connection.

**Comment by antkmsft** [comment]
@Jinming-Hu, do you know of some spec that defines the behavior that you're referring to, so we can implement it the best?
The one I put in here, comes from the HTTP specs and RFCs (I put the links in comments above the lines I modified), but there are many addendums, I could have missed something related to 100-continue.
Do you know if WinHTTP implements the behavior you're describing?

**Comment by Jinming-Hu** [comment]
@antkmsft I agree your implementation is compliant to the standard. But Azure services are not compliant, and this is not the only issue (I've seen others). As Azure SDK, we better be compatible with Azure services.

**Comment by antkmsft** [comment]
@Jinming-Hu, I 100% agree with you, and I do not want for the SDK to be unreliable when talking to Azure, not at all.
I just don't understand if the interaction with Azure is not compliant, how come we don't see a problem when using WinHTTP, which does not have this special logic, and must only adhere to standard.
And the second question remains - do you have any references - documentation, or code in other language SDKs, which has this extra logic, which we could use as a reference. At this moment, I only have spoken word and this very implementation that contains this knowledge, plus no tests. Please understand, my no means I am implying that if these do not exist, your point is not valid, and I would not want to check in something that introduces more problems. I am just trying to figure this out, for the implementation become better, not worse. I want to have a code that you'll genuinely agree on, after we sort out all these questions, if necessary.
Plus, a side question - you see this PR, I just replaced the logic of "httpCode < 200 && httpCode >= 300" by looking into "Connection" header instead. I did not remove any existing handling of "100-Continue". Do you think it will break the current handling of "100-Continue"?

If you want, we can take this offline, if that will be faster and easier to discuss. Once again, I am not trying to force this on Storage, you have nothing to worry about, you don't need to be prepared to defend it if the things really can't work the other way. I am just trying to bring clarity, for both of us. If it is Storage-specific, we can look into the transport to have "Storage Mode", where it would work one way for the Storage, and maybe the other way for everything else, if it is only Storage who works this way. Other good thing that may be an outcome of this, is if we put more comments/references/tests on how things should work, so the next time someone modifies transport, they are aware on how to not break Storage, and don't accidentally break you.
But as I said, if it really works this way, I don't understand how it works successfully on WinHTTP and in other language SDKs.

**Comment by Jinming-Hu** [comment]
Hi @antkmsft , winhttp transport or any other language SDKs do not use `100-continue` at all, that's why we don't see the issue anywhere else.

> Plus, a side question - you see this PR, I just replaced the logic of "httpCode < 200 && httpCode >= 300" by looking into "Connection" header instead. I did not remove any existing handling of "100-Continue". Do you think it will break the current handling of "100-Continue"?

Your code change looks fine to me. But I cannot answer this question before it's fully tested. As I said, Azure services are not 100% compliant to standard. I don't know if server side will always send `Connection: close` header when it wants to terminate current session, but it looks to me you've made this assumption in this PR.

Anyway, since you mentioned you desired to fix issue #5450 in this PR. Let me add some details of the situation and explain why it doesn't fix as expected.
1. Storage SDK sends a PUT request with a non-empty request body (which means `Content-Length` request header is not `0`, let's say it's `6`) and `Expect: 100-continue` request header, but it doesn't send the header unless server returns `100 Continue` status code.
2. Storage service returns 4xx status code and response headers, but it doesn't want to close this connection, so there's no `Connection: close` in response headers.
3. Now both client and server agree to continue using this connection. But they do not agree in the current status of this connection.
    1. Client side thinks the previous request is finished because it has received a status code and response headers. It should send a new HTTP request if there's any.
    2. Server side thinks the previous request is not finished because it hasn't received the request body. I tend to think this is a bug of server-side.
4. Client side sends a new request, for example, 
    ```
    HEAD /whatever/path HTTP/1.1
    host: foo.bar.com
    ...
    ```
5. Server side takes the first 6 bytes (`HEAD /`) of the send request and thinks this is the request body of the first request and discard it.
6. Server side keeps reading the remaining data on the wire and thinks the first part (`whatever/path`) is an HTTP verb. It fails the request with 400 invalid verb.

**Review by LarryOsterman — APPROVED** [review]

**Comment by antkmsft** [comment]
@Jinming-Hu and @LarryOsterman, please check out the latest iteration (commit https://github.com/Azure/azure-sdk-for-cpp/pull/5473/commits/8d81706f60abc26399ee8161c32ebba183bea341).

**Review by Jinming-Hu — APPROVED** [review]

**Comment by antkmsft** [comment]
FYI @mchelnokov

File: sdk/core/azure-core/src/http/curl/curl.cpp [hunk 1]
```diff
@@ -2129,13 +2223,11 @@ std::unique_ptr<CurlNetworkConnection> CurlConnectionPool::ExtractOrCreateCurlCo
...
-    HttpStatusCode lastStatusCode)
+    bool httpKeepAlive)
 {
-  auto code = static_cast<std::underlying_type<Http::HttpStatusCode>::type>(lastStatusCode);
-  if ((code < 200 || code >= 300) && lastStatusCode != HttpStatusCode::NotFound)
+  if (!httpKeepAlive)
   {
-    // A handler with previous response with Error can't be re-use.
-    return;
+    return; // The server has asked us to not re-use this connection.
```
Comment (mchelnokov) [inline sdk/core/azure-core/src/http/curl/curl.cpp:2230]: One more note: When the server returns 500 (Operation Timeout) or 503 (Server Busy) responses, does it set the "Connection: close" header? This is important because in such cases, the recommended application behavior is to reconnect to minimize the use of the (most likely) overloaded node.

Comment (antkmsft) [reply sdk/core/azure-core/src/http/curl/curl.cpp:2230]: Thank you Mykhailo, this makes good sense. Let me to address this in a follow-up PR, so that the team members can review comment on that idea separately, while we don't hold this PR.

File: sdk/core/azure-core/src/http/curl/curl.cpp [hunk 2]
```diff
@@ -874,6 +874,100 @@ CURLcode CurlSession::ReadStatusLineAndHeadersFromRawResponse(
...
+  // 4. Client side sends a new request, for example,
+  //    HEAD /whatever/path HTTP/1.1
+  //    host: foo.bar.com
+  //    ...
+  // 5. Server side takes the first 6 bytes (HEAD /) of the send request and thinks this is the
+  // request body of the first request and discard it.
+  // 6. Server side keeps reading the remaining data on the wire and thinks the first part
+  // (whatever/path) is an HTTP verb. It fails the request with 400 invalid verb.
+  bool non2xxAfter100ContinueWithNonzeroContentLength = false;
+  {
```
[the remark this answers is not in the document]
Comment (antkmsft) [reply sdk/core/azure-core/src/http/curl/curl.cpp:906]: Thanks! This is good feedback. Let me to address it in the follow-up PR that I will make shortly, so we could potentially debate the better place for the code, while this logic, that I got the green light for, can be checked in.
I do agree, the place you suggesting seems like more natural place to detect the condition, the only difference being that if "100-continue" is set in some other place in code, and the verb is not "PUT", then it may not detect it, but from what I see, we are not doing that anywhere in our code, other than that place inside libcurl transport adapter.

File: sdk/core/azure-core/src/http/curl/curl.cpp (hunk 1 above)
Comment (Jinming-Hu) [reply sdk/core/azure-core/src/http/curl/curl.cpp:2230]: > to reconnect to minimize the use of the (most likely) overloaded node.

Throttling doesn't necessarily mean the node is overloaded. It usually means the usage exceeds account limit. Theoretically all nodes share the same throttling configuration, so connecting to another node won't help.

Comment (mchelnokov) [reply sdk/core/azure-core/src/http/curl/curl.cpp:2230]: Sure about the throttling, but it doesn’t cover all cases of the 5xx errors. They may arise due to hardware or connectivity issues, occurring either on the storage or gateway nodes, or from unexpected load spikes generated by other tenants. Reconnecting can expedite issue resolution, as the balancer will likely select a healthier node.

Comment (antkmsft) [reply sdk/core/azure-core/src/http/curl/curl.cpp:2230]: Do you think it makes sense to verify this on practice, and measure perf with 500/503 being auto-closed vs relying on Connection: close header, so that maybe it does not make a difference?

Comment (antkmsft) [reply sdk/core/azure-core/src/http/curl/curl.cpp:2230]: FWIW, `Connection` header is in the allow-list for logging, so [if logging is on](https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/core/azure-core#troubleshooting), it also could be possible to see what the values are.

File: sdk/core/azure-core/src/http/curl/curl.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (antkmsft) [reply sdk/core/azure-core/src/http/curl/curl.cpp:906]: @mchelnokov, I made another PR - https://github.com/antkmsft/azure-sdk-for-cpp/pull/1. Would you say it reflects the idea you had in mind?

@Jinming-Hu, would you prefer the logic from this PR, or from https://github.com/antkmsft/azure-sdk-for-cpp/pull/1?
I realize that, for better, or for worse, it is not a 100% equivalent condition-wise.

File: sdk/core/azure-core/src/http/curl/curl.cpp (hunk 1 above)
Comment (mchelnokov) [reply sdk/core/azure-core/src/http/curl/curl.cpp:2232]: Well, it would be great to verify this situation in practice, but it's sooo rare that I doubt it can be properly reproduced. Throttling can be reproduced, but it's not the exact situation I'm worried about (the hardware issue with the node that wasn't caught on time). I would like to examine the behavior in other client libraries (for example, the .NET one). What do they do with the connection when a 5xx error is received?

Comment (antkmsft) [reply sdk/core/azure-core/src/http/curl/curl.cpp:2232]: From what I can see, other language SDKs do not implement connection pools - they fully delegate it all to HTTP transport, kind of how we also do it here with WinHTTP transport. Any such transport is what you get with standard libs with the language, and it would not have any Azure-specific logic. I think it would implement standard handling of HTTP protocol, and would rely on `Connection` header in combination with HTTP version in the response, and would not take the HTTP response code into consideration.
If you want, you can try to find it yourself - https://github.com/orgs/Azure/repositories?language=&q=%22azure-sdk-for%22&sort=&type=public. I'll also ask people around me, on the occasion, and if I find anything interesting, I'll try to let you know.
