### PR TITLE
AzureCliCredential to treat datetime without TZ info as local time.

### LINKED ISSUE #5075: az cli returns expiresOn in local time but sdk assumes c++ time
**Describe the bug**
When using an AzureCliCredential, the `ExpiresOn` field is parsed from the the output of the call
```
az account get-access-token --output json --scope "https://storage.azure.com/.default"
```
which returns the field `expiresOn` in local time but does not add time zone information. However, `Azure::DateTime` assumes - when no time zone information is present - that the date is in UTC.

The `IsFresh` method of Azure::TokenCache then compares the parsed `ExpiresOn` with `Azure::DateTime(std::chrono::system_clock::now())` which is UTC time thus yielding a wrong comparison.

***Exception or Stack Trace***
-

**To Reproduce**
Inject the following debug code in `TokenCache::IsFresh` in `token_cache.cpp`:
```
  const DateTime end_point = DateTime(now) + minimumExpiration;
  std::cout << "lhs: " << item->AccessToken.ExpiresOn.ToString() << " rhs: " << end_point.ToString() << std::endl;
```
Then call any api using the `AzureCliCredential` that requires a token.

***Code Snippet***
-

**Expected behavior**
The AzureCliCredential should correctly take the time zone information into account.

**Screenshots**
-

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04
 - IDE : VsCode
 - Version of the Library used: Azure Identity `1.6.0-beta.1` and Azure Core `1.10.2`

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by antkmsft**
Closes #5075.

This is not a replacement for #5180, because that one will work only if the user has the new version of Azure CLI installed.

Obsoletes #5076.

### CODE REVIEW

File: sdk/core/azure-core/inc/azure/core/datetime.hpp [hunk 1]
```diff
@@ -324,6 +340,52 @@ namespace Core { namespace _internal {
      */
     ~PosixTimeConverter() = delete;
   };
+
+  /**
+   * @brief Provides additional methods for #Azure::DateTime.
+   *
+   */
+  class DateTimeExtensions final {
```
Comment (RickWinter) [inline sdk/core/azure-core/inc/azure/core/datetime.hpp:348]: This could be a private method.  Or if we want to expose it to customers then its a public method.  Why the complexity of a friend class?

Comment (antkmsft) [reply sdk/core/azure-core/inc/azure/core/datetime.hpp:348]: If it is a private method, then how would we call it from Core Tests, and from Identity's TokenCredentialImpl?
I'd rather not expose it to customers - no need for that, no need to commit to support it, and making no breaking changes.
So, `Core::_internal::DateTimeExtensions::Parse()` seems ideal to me - it is internal API that is shared between SDK libraries, but it is not available to the public. And I don't know how to achieve that without friends.

File: sdk/core/azure-core/src/datetime.cpp [hunk 2]
```diff
@@ -729,6 +744,30 @@ DateTime DateTime::Parse(std::string const& dateTime, DateFormat format)
...
+          ? *localTimeToUtcDiffSeconds
+          : static_cast<int>(std::difftime(
+              std::mktime(std::localtime(&timeTNow)), std::mktime(std::gmtime(&timeTNow))));
+      // LCOV_EXCL_STOP
+#ifdef _MSC_VER
+#pragma warning(pop)
+#endif
+
+      localDiffHours = static_cast<int8_t>(utcDiffSeconds / (60 * 60));
+      localDiffMinutes = static_cast<int8_t>((utcDiffSeconds % (60 * 60)) / 60);
```
Comment (ahsonkhan) [inline sdk/core/azure-core/src/datetime.cpp:768]: I am wary of such logic, especially if it implies daylight saving time isn't honored (and hence a token that is actually expired, isn't refreshed).

Is it only 2 hours within a year where this calculation would be wrong?

File: sdk/core/azure-core/CHANGELOG.md [hunk 3]
```diff
@@ -14,6 +14,7 @@
 ### Other Changes
 
 - [[#4756]] (https://github.com/Azure/azure-sdk-for-cpp/issues/4756) `BearerTokenAuthenticationPolicy` now uses shared mutex lock for read operations.
+- Added internal provisions for extended `Azure::DateTime` parsing.
```
Comment (antkmsft) [inline sdk/core/azure-core/CHANGELOG.md:17]: Detect TZ offset in Identity, and append "+/-HH:MM" to the datetime that az cli returns.

File: sdk/core/azure-core/inc/azure/core/datetime.hpp (hunk 1 above)
Comment (antkmsft) [reply sdk/core/azure-core/inc/azure/core/datetime.hpp]: BTW, the new iteration no longer needs to use friends.

File: sdk/core/azure-core/CHANGELOG.md (hunk 3 above)
Comment (antkmsft) [reply sdk/core/azure-core/CHANGELOG.md]: Done.

File: sdk/identity/azure-identity/src/azure_cli_credential.cpp [hunk 4]
```diff
@@ -127,6 +129,25 @@ std::string AzureCliCredential::GetAzCommand(std::string const& scopes, std::str
...
+#pragma warning(push)
+// warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s
+// instead.
+#pragma warning(disable : 4996)
+#endif
+  // LCOV_EXCL_START
+  auto const timeTNow = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
+
+  return static_cast<int>(
+      std::difftime(std::mktime(std::localtime(&timeTNow)), std::mktime(std::gmtime(&timeTNow))));
```
Comment (ahsonkhan) [inline sdk/identity/azure-identity/src/azure_cli_credential.cpp:144]: Why cast to int rather than keep as double throughout? Consider adding a comment justifying why this is OK to do here.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 5]
```diff
@@ -192,13 +194,39 @@ std::string TokenAsDiagnosticString(
...
+  if (utcDiffSeconds == 0)
+  {
+    return {};
+  }
+
+  std::ostringstream os;
+  if (utcDiffSeconds >= 0)
+  {
+    os << '+';
+  }
```
Comment (ahsonkhan) [inline sdk/identity/azure-identity/src/token_credential_impl.cpp:209]: nit: It should never be == 0 at this point, right?
```suggestion
  if (utcDiffSeconds > 0)
  {
    os << '+';
  }
```

Unless, you think `+00:00` is a safer choice than `-00:00` which would be the "else" case, otherwise.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 6]
```diff
@@ -309,13 +337,14 @@ AccessToken TokenCredentialImpl::ParseToken(
       }
     }
 
+    auto const tzOffsetStr = TimeZoneOffsetAsString(utcDiffSeconds);
     if (expiresOn.is_string())
     {
       auto const expiresOnAsString = expiresOn.get<std::string>();
       for (auto const& parse : {
-               std::function<DateTime(std::string const&)>([](auto const& s) {
+               std::function<DateTime(std::string const&)>([&](auto const& s) {
```
Comment (ahsonkhan) [inline sdk/identity/azure-identity/src/token_credential_impl.cpp:345]: Why is this change to add `[&]` needed now?

File: sdk/identity/azure-identity/src/token_credential_impl.cpp [hunk 7]
```diff
@@ -309,13 +337,14 @@ AccessToken TokenCredentialImpl::ParseToken(
...
                  // 'expires_on' as RFC3339 date string (absolute timestamp)
-                 return DateTime::Parse(s, DateTime::DateFormat::Rfc3339);
+                 return DateTime::Parse(s + tzOffsetStr, DateTime::DateFormat::Rfc3339);
```
Comment (ahsonkhan) [inline sdk/identity/azure-identity/src/token_credential_impl.cpp:347]: We should check and only add a `tzOffsetStr` **IF** the string doesn't already have a `+XX:XX` info at the end, to avoid malforming the date string.

Comment (ahsonkhan) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:347]: I am assuming this PR will adjust a bit after https://github.com/Azure/azure-sdk-for-cpp/pull/5180 is merged.

File: sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp [hunk 8]
```diff
@@ -60,6 +61,8 @@ class AzureCliTestCredential : public AzureCliCredential {
     return m_command;
   }
 
+  int GetLocalTimeToUtcDiffSeconds() const override { return m_localTimeToUtcDiffSeconds; }
```
Comment (ahsonkhan) [inline sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp:64]: This isn't being used anywhere (and I am not sure why it's private).

File: sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp [hunk 9]
```diff
@@ -570,6 +575,40 @@ TEST(AzureCliCredential, StrictIso8601TimeFormat)
       DateTime::Parse("2022-08-24T00:43:08.000000Z", DateTime::DateFormat::Rfc3339));
 }
 
+TEST(AzureCliCredential, LocalTime)
+{
+  constexpr auto Token = "{\"accessToken\":\"ABCDEFGHIJKLMNOPQRSTUVWXYZ\","
+                         "\"expiresOn\":\"2023-12-07 00:43:08\"}";
```
Comment (ahsonkhan) [inline sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp:581]: What happens if the input expiresOn within the JSON has trailing space (or some other semantic text that is typically ignored), and looks like this:
`"\"expiresOn\":\"2023-12-07 00:43:08   \"}"`

I imagine, this would previously work OK, but now the DateTime parser won't handle it, once the local time is appended after the spaces.

**Review by ahsonkhan — COMMENTED** [review]
Otherwise, lgtm.

Holding off approval until after https://github.com/Azure/azure-sdk-for-cpp/pull/5180 is merged.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 5 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:209]: We should never get `== 0` here, but should we ever get here, I think, `+00:00` is aesthetically better.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 6 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp:345]: That's because we capture `tzOffsetStr` by reference.

File: sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp (hunk 8 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp:64]: TokenCredentialImpl calls it: https://github.com/Azure/azure-sdk-for-cpp/pull/5179/files#diff-cc522e423ed15512dfbcccd5a21748c22c948f10b8b779f8201718aed16f98fcR353

This is private virtual, which means that the base class may still call it, but not the classes who inherit AzureCliTestCredential (should there be any).

File: sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp (hunk 9 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp:631]: If they start giving bad outputs, we can build some vandal-proofness, but I believe failing is not the worst option.
I do not expect them to start returning values with spaces at the end, though.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 7 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp]: Azure CLI team is not expected to change format of this field - they will forever keep it as is for compatibility - https://github.com/Azure/azure-cli/issues/19700#issuecomment-1784671351.
If only they could, they would add `Z` and return as UTC timestamp, or add `+HH:MM` of a time zone, this whole sage would've been over, and there would've been no need to add `expires_on` field.

File: sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp (hunk 8 above)
Comment (ahsonkhan) [reply sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp:64]: Oh right, it's virtual (hence the override). Got it.

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 7 above)
Comment (ahsonkhan) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp]: Can't `token_credential_impl.cpp` be used for other credentials beyond azure cli credential, in the future?

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 6 above)
Comment (ahsonkhan) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp]: And just out of curiosity around benefits/drawbacks, why do we capture it by reference?

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 7 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp]: It can and should, however, I don't expect it being used with non-0 `utcDiffSeconds`.
As `ParseToken()`'s comment says, "`No credential other than AzureCliCredential (which gets timestamps as local time without time zone) should need to set it.`"

**Review by ahsonkhan — APPROVED** [review]
This is a much cleaner and isolated fix (without requiring extra parsing logic in `DateTime` within `Azure::Core`). Appreciate it!

File: sdk/identity/azure-identity/src/token_credential_impl.cpp (hunk 6 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/src/token_credential_impl.cpp]: References are less expensive, they are basically pointers, and if we capture by value, we are copying the string - so in case strings are not copyable-on-write (which is very likely), we end up allocating memory and then strcopy.

File: sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp (hunk 9 above)
Comment (antkmsft) [reply sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp:631]: BTW, if we ever need to do this, one way of doing it would be to parse it, and then do a ToString(), then remove `Z` at the end, then append a TZ offset string, and then parse again.
Should there be a TZ offset, it would be harder to detect it, without writing a parser, so I think if that is ever the case, the best course of action would be the initial state of this PR, when it was the DateTime's parser who would append TZ offset IF there is no offset or `Z` specified, and would ignore it otherwise.
