### PR TITLE
AMQP Session related fixes.

### LINKED ISSUE #5052: Fix uAMQP session channel disconnect to not remove a channel until the session is fully closed, not half closed.
commented code

_Originally posted by @RickWinter in https://github.com/Azure/azure-sdk-for-cpp/pull/5018#discussion_r1369265384_

### PR DESCRIPTION
**Pull request by LarryOsterman**
Fixes #5052 and #5296.

There are two main fixes in this pull request:
1. Don't release a channel when the END performative is sent, instead wait until the response END performative is received.
2. Send a BEGIN performative when a session begin is sent if the underlying connection is already open.

This also lays the foundation for adding AMQP support for DETACH and TRANSPORT performatives - currently only used during tests, but if/when a C++ AMQP stack is built, these will be used for that.

This also adds LINK tests to create a sender link on a session to force a session to do *something* after it is created.

Finally, it re-enables *most* of the multi-threaded Eventhubs test cases since the underlying bugs that prevented them from working have now been fixed.

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp [hunk 1]
```diff
@@ -166,7 +167,7 @@ namespace Azure { namespace Core { namespace Amqp { namespace _internal {
    */
   class ConnectionEvents {
   protected:
-    ~ConnectionEvents(){};
+    virtual ~ConnectionEvents(){};
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp:170]: Out of curiosity, why is this needed? Normally, non-virtual protected destructors don't cause problems.

Comment (antkmsft) [inline sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp:170]: Super nit: `virtual ~ConnectionEvents() = default;`

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp [hunk 2]
```diff
@@ -181,27 +182,28 @@ namespace Azure { namespace Core { namespace Amqp { namespace _internal {
...
-      (void)endpoint;
-      return false;
-    }
+    virtual void OnIOError(Connection const& connection) = 0;
+  };
 
-    /** @brief called when an I/O error has occurred on the connection.
+  class ConnectionEndpointEvents {
+  protected:
+    virtual ~ConnectionEndpointEvents(){};
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp:194]: Super nit (but it is never a problem, just a matter of preference, if you like it, then append it):
```suggestion
    virtual ~ConnectionEndpointEvents() = default;
```

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/models/performatives/amqp_detach.hpp [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+     */
+    class AmqpDetach {
+    public:
+      AmqpDetach() = default;
+
+      uint32_t Handle{};
+      bool Closed{};
+      AmqpError Error;
+    };
+}}}}}} // namespace Azure::Core::Amqp::Models::_internal::Performatives
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/models/performatives/amqp_detach.hpp:30]:
```suggestion
}}}}}} // namespace Azure::Core::Amqp::Models::_internal::Performatives

```

File: sdk/core/azure-core-amqp/src/amqp/link.cpp [hunk 4]
```diff
@@ -85,16 +95,53 @@ namespace Azure { namespace Core { namespace Amqp { namespace _detail {
...
+  {
+    return m_impl->Transfer(payload, context);
+  }
+
   void Link::Detach(
       bool close,
       std::string const& errorCondition,
       std::string const& errorDescription,
-      Models::AmqpValue& info)
+      const Models::AmqpValue& info)
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/src/amqp/link.cpp:109]: Do you want to put it as Yoda const for consistency? :)

File: sdk/core/azure-core-amqp/test/ut_uamqp/CMakeLists.txt [hunk 5]
```diff
@@ -30,7 +30,7 @@ add_executable(azure-core-amqp-uamqp-tests
   uamqp_header_tests.cpp
   uamqp_insertion_tests.cpp
   uamqp_message_tests.cpp
- "uamqp_properties_tests.cpp")
+ "uamqp_properties_tests.cpp" "uamqp_performatives_tests.cpp")
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/test/ut_uamqp/CMakeLists.txt:33]:
```suggestion
  uamqp_properties_tests.cpp
  uamqp_performatives_tests.cpp
)
```

**Review by antkmsft — APPROVED** [review]
You most likely need to add a changelog entry?

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp (hunk 1 above)
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp:170]: Either Clang or Gcc get upset if they encounter a non-virtual destructor in a base class.

There are 3 options to fix it:
1. Add `virtual` to the base class destructor.
2. Mark the derived class as `final`
3. Add a destructor to the derived class (for an events class that isn't a problem because there's no base class state to be torn).

I figured that #1 was the easiest way of making the compiler happy.

File: sdk/core/azure-core-amqp/CHANGELOG.md [hunk 6]
```diff
@@ -6,12 +6,16 @@
 
 The `Close` method on AMQP Message Sender and Message Receiver now blocks until the client receives a `DETACH` response from the remote node.
 
+
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/CHANGELOG.md:9]:
```suggestion
```

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp [hunk 7]
```diff
@@ -3,6 +3,7 @@
 
 #pragma once
 
+#include "amqp_settle_mode.hpp"
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp:6]:
```suggestion
#include "azure/core/amqp/internal/amqp_settle_mode.hpp"
```

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_sender.hpp [hunk 8]
```diff
@@ -3,6 +3,7 @@
 
 #pragma once
 
+#include "amqp_settle_mode.hpp"
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_sender.hpp:6]:
```suggestion
#include "azure/core/amqp/internal/amqp_settle_mode.hpp"
```

File: sdk/core/azure-core-amqp/src/amqp/message_sender.cpp [hunk 9]
```diff
@@ -37,6 +37,24 @@ namespace Azure { namespace Core { namespace Amqp { namespace _detail {
...
+        stream << "Settled";
+        break;
+      case SenderSettleMode::Unsettled:
+        stream << "Unsettled";
+        break;
+      case SenderSettleMode::Mixed:
+        stream << "Mixed";
+        break;
+      default:
+        throw std::runtime_error("Unknown message sender settle state.");
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/src/amqp/message_sender.cpp:54]: Given that these operators are mostly used for logs, do you think it would be better to print "UNKNOWN" instead of throwing?

Let's say we added a new value, and did not update this operator. Tested with the log message never occurring, or with logs disabled. Shipped it, and it breaks for customer with logs enabled.

This would apply to all similar `operator <<`, if they are throwing as well.

File: sdk/core/azure-core-amqp/test/ut_uamqp/uamqp_value_tests.cpp [hunk 10]
```diff
@@ -0,0 +1,218 @@
...
+  }
+  // MOCKABLE_FUNCTION(, AMQP_VALUE, amqpvalue_create_array);
+  {
+    _detail::UniqueAmqpValueHandle handle{amqpvalue_create_array()};
+
+    AmqpValue value{_detail::AmqpValueFactory::FromUamqp(handle)};
+    GTEST_LOG_(INFO) << "Handle Type: " << amqpvalue_get_type(handle.get())
+                     << " Value: " << static_cast<AMQP_VALUE>(handle.get());
+  }
+}
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/test/ut_uamqp/uamqp_value_tests.cpp:218]:
```suggestion
}

```

File: sdk/core/azure-core-amqp/test/ut/link_tests.cpp [hunk 11]
```diff
@@ -176,43 +185,76 @@ namespace Azure { namespace Core { namespace Amqp { namespace Tests {
...
       auto result = m_receiveLinkQueue.WaitForResult(context);
-      return std::move(std::get<0>(*result));
+      return std::get<0>(*result);
+    }
+
+    void Cleanup()
+    {
+      if (m_link)
+      {
+        //        m_link->Detach(true, {}, {}, {});
```
Comment (antkmsft) [inline sdk/core/azure-core-amqp/test/ut/link_tests.cpp:245]:
```suggestion
        // m_link->Detach(true, {}, {}, {});
```
Or, if it is not needed, better remove it?

**Review by antkmsft — APPROVED** [review]

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp (hunk 7 above)
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp:6]: Why use an absolute path to the file when it's in the same directory as the header?

There doesn't seem to be any reason to force a full path on headers, especially if they're in the same directory.

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_sender.hpp (hunk 8 above)
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_sender.hpp:6]: Same comment. There does not appear to be a consistent standard w.r.t. using the full path for include file names in the repo.

File: sdk/core/azure-core-amqp/src/amqp/message_sender.cpp (hunk 9 above)
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/src/amqp/message_sender.cpp:54]: Better solution: Remove the default: case entirely.

If a new value is added, the compiler will complain that not all possible branches are taken.

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp (hunk 7 above)
Comment (antkmsft) [reply sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp:6]: If they are installed, I think there could be cases when it makes difference between local file in the same directory, and the installed location.
We use the absolute pattern everywhere anyways, so at least for consistency.

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_sender.hpp (hunk 8 above)
Comment (antkmsft) [reply sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_sender.hpp:6]: In this repo we use full paths everywhere in `/inc`. Only the `/src` uses the relative paths.

File: sdk/core/azure-core-amqp/src/amqp/message_sender.cpp (hunk 9 above)
Comment (antkmsft) [reply sdk/core/azure-core-amqp/src/amqp/message_sender.cpp]: Maybe, but would they go out of their way? Technically, they don't have to - it is a valid C++ code to not have all values covered. You'll just get an empty string, compiler may think this is exactly what you wanted.
If at least one in our CI does that, I guess we're good.

File: sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp (hunk 7 above)
Comment (LarryOsterman) [reply sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_receiver.hpp:6]: My point is that we don't appear to do that. There are multiple places where we include files with relative paths.
