### PR TITLE
clang-13 version of cstdlib doesn't define integer types in global na…

### LINKED ISSUE #5007: azure-core build failure with gcc 13
**Describe the bug**
Issue raised on vcpkg page here: https://github.com/microsoft/vcpkg/issues/34272

***Exception or Stack Trace***
see attached build log

**To Reproduce**
git clone https://github.com/microsoft/vcpkg
./vcpkg/bootstrap-vcpkg.sh
./vcpkg/vcpkg install azure-core-cpp

**Expected behavior**
clean compile

**Screenshots**

**Setup (please complete the following information):**
 - OS: gentoo Linux
 - IDE : gcc 13.2.1

[install-x64-linux-dbg-out.log](https://github.com/Azure/azure-sdk-for-cpp/files/12811035/install-x64-linux-dbg-out.log)

### PR DESCRIPTION
**Pull request by LarryOsterman**
…mespace

Fixes #5007 

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

### CODE REVIEW

File: sdk/core/azure-core/inc/azure/core/base64.hpp [hunk 1]
```diff
@@ -10,8 +10,9 @@
 #pragma once
 
 #include <algorithm>
-#include <cstdint>
+#include <cstdint> // defines std::uint8_t
 #include <stdexcept>
+#include <stdint.h> // deprecated, defines uint8_t in global namespace.
```
Comment (ahsonkhan) [inline sdk/core/azure-core/inc/azure/core/base64.hpp:15]: When do we include both in our code? What are the types or methods that trigger the issue?

Comment (LarryOsterman) [reply sdk/core/azure-core/inc/azure/core/base64.hpp:15]: This issue applies to ALL types of the form `.int*_t` that have this issue (and a bunch of other random types defined in stdint.h), not just uint8_t (although that is the only type referenced in base64).

Theoretically this applies to any place we include cstdint, but this is the only one that customers are complaining about.

We need both of them because the integer types are deprecated in the global namespace. And apparently some C++ runtime libraries have followed through and removed the deprecated types from cstdint.

Anton has suggested (and I agree with him) that we should move all the integer types to use the std::xxx form. But for now, we can resolve the specific customer issue with a targeted fix.

**Comment by LarryOsterman** [comment]
Ping :).

**Comment by ahsonkhan** [comment]
> Anton has suggested (and I agree with him) that we should move all the integer types to use the std::xxx form. 

That sounds like a great solution and one we can put in the SDK guidelines.

File: eng/pipelines/templates/stages/platform-matrix.json [hunk 2]
```diff
@@ -167,6 +167,34 @@
...
+        "Ubuntu22": {
+          "OSVmImage": "MMSUbuntu22.04",
+          "Pool": "azsdk-pool-mms-ubuntu-2204-general",
+          "VCPKG_DEFAULT_TRIPLET": "x64-linux",
+          "BuildArgs": "-j 10",
+          "RunProxyTests": true
+        }
+      },
+      "BuildSettings": {
+        "clang-13": {
```
Comment (ahsonkhan) [inline eng/pipelines/templates/stages/platform-matrix.json:181]: Can you confirm that this step is failing in CI before your fix?

File: eng/pipelines/templates/stages/platform-matrix.json [hunk 3]
```diff
@@ -167,6 +167,34 @@
...
+          "CXX": "/usr/bin/clang++-13"
+        },
+        "clang-15": {
+          "AptDependencies": "clang-15",
+          "CC": "/usr/bin/clang-15",
+          "CXX": "/usr/bin/clang++-15"
+        },
+        "included_debug": {
+          "CMAKE_BUILD_TYPE": "Debug",
+          "CmakeArgs": " -DBUILD_TESTING=ON -DBUILD_PERFORMANCE_TESTS=ON -DRUN_LONG_UNIT_TESTS=ON",
```
Comment (ahsonkhan) [inline eng/pipelines/templates/stages/platform-matrix.json:193]: Should we be building samples too?

File: eng/pipelines/templates/stages/platform-matrix.json [hunk 4]
```diff
@@ -167,6 +167,34 @@
         }
       }
     },
+    {
+      "StaticConfigs": {
+        "Ubuntu22": {
```
Comment (ahsonkhan) [inline eng/pipelines/templates/stages/platform-matrix.json:172]: What's the name of the pipeline run corresponding to this?

Comment (LarryOsterman) [reply eng/pipelines/templates/stages/platform-matrix.json:172]: platform-matrix.json is used for the "cpp - <service> - ci" pipelines.

File: eng/pipelines/templates/stages/platform-matrix.json (hunk 3 above)
Comment (LarryOsterman) [reply eng/pipelines/templates/stages/platform-matrix.json:193]: Maybe? My primary focus for this PR is vcpkg, which doesn't build samples (or tests).

File: eng/pipelines/templates/stages/platform-matrix.json (hunk 2 above)
Comment (LarryOsterman) [reply eng/pipelines/templates/stages/platform-matrix.json:181]: I can confirm that this step is NOT failing in CI before my fix.

The customer reported problem requires a particular version of cstdlib but I don't know where their version of cstdlib came from.

File: eng/pipelines/templates/stages/platform-matrix.json [hunk 5]
```diff
@@ -167,6 +167,34 @@
...
+          "OSVmImage": "MMSUbuntu22.04",
+          "Pool": "azsdk-pool-mms-ubuntu-2204-general",
+          "VCPKG_DEFAULT_TRIPLET": "x64-linux",
+          "BuildArgs": "-j 10",
+          "RunProxyTests": true
+        }
+      },
+      "BuildSettings": {
```
Comment (danieljurek) [inline eng/pipelines/templates/stages/platform-matrix.json:180]: Move the entries inside this `BuildSettings` inside the `BuildSettings` of the object starting at line 136 and delete the rest of this object (that is, put them in after line 167). This will result in the same matrix. 

The math here is `StaticConfigs * BuildSettings` and the `StaticConfigs` for both the entry starting at line 170 and the entry starting at line 136 are the same.

**Review by danieljurek — APPROVED** [review]
EngSys changes LGTM

**Review by RickWinter — APPROVED** [review]
Add a comment that we will remove the header in future cleanup.  Otherwise LGTM

**Review by ahsonkhan — APPROVED** [review]
Fingers crossed this fixes the customer's `vcpkg install` issue :)

File: sdk/core/azure-core/inc/azure/core/uuid.hpp [hunk 6]
```diff
@@ -11,8 +11,9 @@
 #include "azure/core/platform.hpp"
 
 #include <array>
-#include <cstdint>
+#include <cstdint> // defines std::uint8_t
 #include <cstring>
+#include <stdint.h> // deprecated, defines uint8_t in global namespace.
```
Comment (LarryOsterman) [inline sdk/core/azure-core/inc/azure/core/uuid.hpp:16]:
```suggestion
#include <stdint.h> // deprecated, defines uint8_t in global namespace. TODO: Remove in the future when references to uint8_t and friends are removed.
```

File: sdk/core/azure-core/inc/azure/core/base64.hpp (hunk 1 above)
Comment (LarryOsterman) [inline sdk/core/azure-core/inc/azure/core/base64.hpp:15]:
```suggestion
#include <stdint.h> // deprecated, defines uint8_t in global namespace. TODO: Remove when uint8_t in the global namespace is removed.
```
