### PR TITLE
Nullable::Emplace() to set HasValue()

### LINKED ISSUE #5172: Nullable::Emplace doesn't set m_hasValue = true
**Describe the bug**
`Azure::Nullable::Emplace` creates an object as `m_value` but forgets to set `m_hasValue = true`.

***Code Snippet***
```
Azure::Nullable<int> x;
x.Emplace(42);
assert(x.HasValue());
```

**Expected behavior**
`Emplace` should actually engage the `Nullable` object, just like `std::optional::emplace`.

**Setup (please complete the following information):**
The bug still exists in trunk at the time of my writing: https://github.com/Azure/azure-sdk-for-cpp/blob/1b2e58f7437f93324e5b4a56a5c04625d867f7a4/sdk/core/azure-core/inc/azure/core/nullable.hpp#L220

### PR DESCRIPTION
**Pull request by antkmsft**
Closes #5172.
This is consistent with `std::optional`: https://godbolt.org/z/8T41ceeG4

### CODE REVIEW

**Review by RickWinter — APPROVED** [review]

File: sdk/core/azure-core/test/ut/nullable_test.cpp [hunk 1]
```diff
@@ -99,6 +99,34 @@ TEST(Nullable, ValueAssignment)
...
+    EXPECT_EQ(y.Value(), 0);
+  }
+
+  {
+    Azure::Nullable<int> z = 42;
+    EXPECT_TRUE(z.HasValue());
+    EXPECT_EQ(z.Value(), 42);
+    EXPECT_EQ(z.Emplace(), 0);
+    EXPECT_TRUE(z.HasValue());
+    EXPECT_EQ(z.Value(), 0);
```
Comment (ahsonkhan) [inline sdk/core/azure-core/test/ut/nullable_test.cpp:126]: Is there any scenario where a `Nullable<T>` that has a value assigned to it (i.e. `HasValue()` is true) changes to be value-less, i.e. `HasValue()` returns false?

Comment (antkmsft) [reply sdk/core/azure-core/test/ut/nullable_test.cpp:126]: There is no syntax to emplace with lack-of-value, not even the parameterless `emplace()`.

Comment (LarryOsterman) [reply sdk/core/azure-core/test/ut/nullable_test.cpp:126]: I suspect that if you assign a Nullable<T> with a default constructed Nullable<T>, I believe it will change to valueless.

But that's a strange behavior in the context of nullable.

Comment (ahsonkhan) [reply sdk/core/azure-core/test/ut/nullable_test.cpp:126]: `Reset()` has the semantics I was looking for (both in our `Nullable<T>` and `std::optional`), which sets `HasValue` to false.
